### ISSUE TITLE
audio support

### ISSUE THREAD

**Issue by ecatn** [myspaghetti/macos-virtualbox#178]
Hi, sucessfully installed majave vm and everything except audio is working fine, in the readme opencore is mentioned, how is it supposed to be used with my installation, i.e. how to I install it?
Many thanks/ec

**Comment by myspaghetti** [comment]
No support is offered for OpenCore configuration. [OpenCore specifies how to install and configure it.](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pd) You place `BOOTx64.efi` in `/ESP/EFI/BOOT` and place `OpenCore.efi` and `config.plist` in `/ESP/EFI/OC`. OpenCore can be loaded from the VirtualBox EFI Internal Shell with `fs0:\EFI\BOOT\BOOTx64.efi` or `load fs0:\EFI\OC\OpenCore.efi`

I recommend you try to get [FileVault working with OpenCore](https://github.com/myspaghetti/macos-guest-virtualbox/issues/158) at first, and then you can try getting audio to work.

**Comment by myspaghetti** [comment]
No support is offered for OpenCore configuration. [OpenCore specifies how to install and configure it.](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) You place `BOOTx64.efi` in `/ESP/EFI/BOOT` and place `OpenCore.efi` and `config.plist` in `/ESP/EFI/OC`. OpenCore can be loaded from the VirtualBox EFI Internal Shell with `fs0:\EFI\BOOT\BOOTx64.efi` or `load fs0:\EFI\OC\OpenCore.efi`

I recommend you try to get [FileVault working with OpenCore](https://github.com/myspaghetti/macos-guest-virtualbox/issues/158) at first, and then you can try getting audio to work.

**Comment by myspaghetti** [comment]
Looks like VirtualBox virtualizes either SigmaTel STAC9221 (Intel HD Audio) or SigmaTel STAC9700,83,84 (ICH AC97) which isn't currently supported by [AppleALC](https://github.com/acidanthera/AppleALC). If you're a kernel or driver developer, you can look at the existing AppleALC SigmaTel devices, [STAC9200](https://github.com/acidanthera/AppleALC/tree/master/Resources/STAC9200) and [STAC9872AK](https://github.com/acidanthera/AppleALC/tree/master/Resources/STAC9872AK), and probably get an idea how to implement STAC9700 or STAC9221.
