### ISSUE TITLE
Partitionning fails (cannot create filesystem on/dev/rdisk0s2 : resource busy)

### ISSUE THREAD

**Issue by fhob** [myspaghetti/macos-virtualbox#200]
Please see attached screenshot, and toubleshoot.txt

Thanks for your support.

[troubleshoot.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4581514/troubleshoot.txt)

![VirtualBox_macOS_05_05_2020_16_54_49](https://user-images.githubusercontent.com/11962208/81080616-3b37da00-8ef1-11ea-9f9b-c0b0c95fdddc.png)

**Comment by myspaghetti** [comment]
Marked issue #128 `/sbin/newfs_hfs failed with error 256 (resource busy)` as duplicate.

I suspect this issue has to do with the CPU configuration, [as riverar put it](https://github.com/myspaghetti/macos-guest-virtualbox/issues/128#issuecomment-619776136), the virtual machine could be "relying on processor features that are claimed to be present via forced cpuidset (but aren't actually present on the host)"

For anyone experiencing this issue, please attach the output of the following command:
```
./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`
````
After attaching `troubleshoot.txt`, please run the following command:
```
VBoxManage modifyvm "macOS" --cpuidremoveall
```
And afterward, run ***one*** of the following commands then run the script, and if it fails run another one of these commands and then run the script, and so on:
```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-2635QM"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i5-3570"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-5600U"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```

**Comment by myspaghetti** [comment]
@fhob thankfully, in this particular case, the issue is that `InstallESDDmg.pkg` is damaged. The md5sum of Mojave `InstallESDDmg.pkg` version `10.14.4.0.0.1552634279` should be `137a58cf2f9497b0800f775d31edfcc8`. The download was damaged somewhere after the 5,000,000,000th byte - part 00, 01, 02, 03, and 04 are correct, so you can either truncate the file and resume the download from the 5000000001st byte or you can delete the entire file and redownload it. The rest of the files have been downloaded correctly.

Anyone else reporting this issue, please provide `troubleshoot.txt` so it can be quickly investigated.

**Comment by fhob** [comment]
Work after Win10 Hyper-v disabled

**Comment by sochisic** [comment]
I have same issue even after disabled Win10 Hyper-v

Tried all cpu profiles already...but I have no idea what I need to do next.

**Comment by myspaghetti** [comment]
@sochisic please provide the output of `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`

**Comment by sochisic** [comment]
[troubleshoot.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4610887/troubleshoot.txt)
![terminal](https://user-images.githubusercontent.com/23560931/81587199-60c85600-93bf-11ea-98af-cd005c59cecd.PNG)

**Comment by myspaghetti** [comment]
@sochisic the log says VT-x/AMD-V is not available. Make sure Hyper-V, Windows Sandbox, WSL2, and other Windows features that use virtualization are turned off.

**Comment by sochisic** [comment]
@myspaghetti looks like you right, I applied commands below and it was successful, and now It is still installing and passed this step already

dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
bcdedit /set hypervisorlaunchtype off_
