### ISSUE TITLE
Can't complete the installation.

### ISSUE THREAD

**Issue by lucadima15** [myspaghetti/macos-virtualbox#207]
Hello.

The script, when launched, ends with this messages and doesn't create the vdi file.

###########################################################

Splitting the several-GB InstallESDDmg.pkg into 1GB parts because
VirtualBox hasn't implemented UDF/HFS VISO support yet and macOS
doesn't support ISO 9660 Level 3 with files larger than 2GB.
creazione di 'Catalina_InstallESD.part00'
creazione di 'Catalina_InstallESD.part01'
creazione di 'Catalina_InstallESD.part02'
creazione di 'Catalina_InstallESD.part03'
creazione di 'Catalina_InstallESD.part04'
creazione di 'Catalina_InstallESD.part05'
creazione di 'Catalina_InstallESD.part06'
creazione di 'Catalina_InstallESD.part07'

Downloading open-source APFS EFI drivers used for VirtualBox 6.0 and 5.2
...even though VirtualBox version 6.1 or higher is detected.
Archive:  AppleSupport-v2.0.4-RELEASE.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of AppleSupport-v2.0.4-RELEASE.zip or
        AppleSupport-v2.0.4-RELEASE.zip.zip, and cannot find AppleSupport-v2.0.4-RELEASE.zip.ZIP, period.

stage: create_nvram_files

stage: create_macos_installation_files_viso
Creating EFI startup script

Creating VirtualBox 6 virtual ISO containing the
installation files from swcdn.apple.com

stage: create_basesystem_virtual_disk
Converting BaseSystem.dmg to BaseSystem.img
./macos-guest-virtualbox.sh: riga 642: dmg2img: comando non trovato
Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseSystem.vdi"...
VBoxManage.exe: error: Cannot open file "Catalina_BaseSystem.img": VERR_FILE_NOT_FOUND
Failed to create "Catalina_BaseSystem.vdi".
Exiting.

**Comment by myspaghetti** [comment]
You're having write issues on your working directory.

**Comment by myspaghetti** [comment]
Duplicate of  #283, fixed in version 0.96.6
