### ISSUE TITLE
Audio tutorial?

### ISSUE THREAD

**Issue by gerroon** [myspaghetti/macos-virtualbox#209]
Hi

Would it be possible to make a basic tutorial on how to get the audio going? I know the Readme mentions about Opencore but there is not much info on how to go about it.

**Comment by myspaghetti** [comment]
For audio, use OpenCore with either [AppleALC](https://github.com/acidanthera/AppleALC) or VoodooHDA. They require configuration files for the virtual audio devices provided by VirtualBox. VirtualBox virtualizes SigmaTel STAC9221 (Intel HD Audio) and SigmaTel STAC9700,83,84 (ICH AC97). Neither device currently has its configuration available for AppleALC or VoodooHDA.

If you're a kernel or driver developer, you can look at the existing AppleALC SigmaTel devices, [STAC9200](https://github.com/acidanthera/AppleALC/tree/master/Resources/STAC9200) and [STAC9872AK](https://github.com/acidanthera/AppleALC/tree/master/Resources/STAC9872AK), and probably get an idea how to implement STAC9700 or STAC9221 for AppleALC.

**Comment by gerroon** [comment]
Hey thanks.  Did you happen to test this image with Qemu to see if the audio was easier to setup with that one?

**Comment by myspaghetti** [comment]
Audio works on QEMU with the Intel HDA device, but booting macOS on QEMU requires a bootloader like OpenCore.

**Comment by myspaghetti** [comment]
Seems like audio "works" out-of-the-box with VirtualBox 6.1.20, however it [crashes the VM](https://www.virtualbox.org/ticket/20319). Audio is disabled by default on [version 0.98.6](https://github.com/myspaghetti/macos-virtualbox/compare/473a72b..1e219244)

**Comment by myspaghetti** [comment]
Seems like audio "works" out-of-the-box with VirtualBox 6.1.20, however it [freezes the guest and host](https://www.virtualbox.org/ticket/20319). Audio is disabled by default on [version 0.98.6](https://github.com/myspaghetti/macos-virtualbox/compare/473a72b..1e219244)
