### ISSUE TITLE
Cannot enable HiDPI

### ISSUE THREAD

**Issue by neuhaus** [myspaghetti/macos-virtualbox#211]
I am using this on a Dell XPS 13 with a 13" 3200x1800 display.
I have configured a 2800x1800 resolution. I'd like to enable HiDPI mode.

Going to the system settings -> display I see the monitor and can toggle "scaled" but it only shows me the single 2800x1800 resolution.

I've tried:
* https://github.com/syscl/Enable-HiDPI-OSX
* `sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true`
* Installing RDM from https://github.com/usr-sse2/RDM

Running RDM i can pick 1440x900 from the menu but then nothing happens and everything stays tiny.

**Comment by neuhaus** [comment]
PS Ideally I'd like to run MacOS in HiDPI using the full 3200x1800 display resolution (so a virtual 1600x900)

**Comment by myspaghetti** [comment]
VirtualBox doesn't assign a vendor ID to its virtual display, so macOS doesn't use display scaling. Currently investigating how to assign a vendor ID to the VirtualBox MainDisplay.

**Comment by myspaghetti** [comment]
VirtualBox doesn't provide an EDID for its virtual display, so you will need to inject an EDID with a bootloader such as [OpenCore](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#edid)

**Comment by MehdiChinoune** [comment]
There is no guide how to do it ?!
