### ISSUE TITLE
Cannot finish in ubuntu cpu AMD

### ISSUE THREAD

**Issue by alexisaraya** [myspaghetti/macos-virtualbox#212]
Hi,

I have a ubuntu 18.10 in cpu AMD Phenom.

`Until the script completes, please do not interact with the virtual machine.`

in virtual machine see terminal

`LOG:EXITBS:START`

any idea for resume o fix installation ?

Tranks

**Comment by myspaghetti** [comment]
Duplicate of issue #8. See the documentation about assigning CPU profiles.
