### ISSUE TITLE
Error: Cannot create filesystem ... image data corrupted

### ISSUE THREAD

**Issue by michal-minich** [myspaghetti/macos-virtualbox#213]
I tried 2 times clean install (delete all files except install script).

I would appreciate any help.

Thank you.

![image](https://user-images.githubusercontent.com/580593/82765163-92f0a380-9e14-11ea-825b-cbce6a72082d.png)

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. If you don't mind, please post the `macOS_troubleshoot.txt` file that is created by the command `./macos-guest-virtualbox.sh troubleshoot`

**Comment by michal-minich** [comment]
I also did few modifications:
1) change resolution in script to 1440x900

2) I removed this section from script, after I prevent me from continue (The script asked to check for virtualization features).  (I'm attaching output of [vminfo.txt](https://github.com/myspaghetti/macos-virtualbox/files/4675577/vminfo.txt) )

```
if [[ "${vbox_log}" =~ ${regex} ]]; then
    echo -e "\nVirtualbox is not using hardware-supported virtualization features."
    if [[ -n "$(cygcheck -V 2>/dev/null)" ||
          "$(cat /proc/sys/kernel/osrelease 2>/dev/null)" =~ [Mm]icrosoft ]]; then
        echo "Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity"
        echo "protection, and other Windows features that lock virtualization are turned off."
    fi
    echo "Exiting."
    exit
fi
```

3) I had problem booting  because it could not mount vm image / swap. I run script from some other install guide [macos.txt](https://github.com/myspaghetti/macos-virtualbox/files/4675583/macos.txt) 

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4675590/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
According to the log, VirtualBox is... not using hardware supported virtualization features:
```
00:00:03.506679 HM: HMR3Init: Attempting fall back to NEM: VT-x is not available
```
macOS will not boot without VT-x/AMD-V hardware-supported virtualization.

**Comment by myspaghetti** [comment]
Generally, please don't use arbitrary `VBoxManage --cpuidset` commands from the internet, the CPUID must match your own CPU. See documentation about removing CPU profiles, and search Google for information about disabling Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and so on. [Some people reported success](https://www.virtualbox.org/ticket/14638) with the command `bcdedit /set hypervisorlaunchtype off` but mind that [many other Windows features](https://www.virtualbox.org/ticket/18536?cversion=0&cnum_hist=1) might block VT-x/AMD-V hardware-supported virtualization in VirtualBox.

**Comment by efa** [comment]
in my case was "Virtual Machine Platform" used by WSL2.
So I switched back from WSL2 to WSL1 with:
administrative PowerShell: > wsl --list --verbose
administrative PowerShell: > wsl --set-version Debian 1
wait some minutes for conversion
Then Control Panel, Activate or disactivate Windows functionalities
disabled "Virtual Machine Platform"
reboot
Checked WSL1 still work
Now VT-x is free and shell script work
