### ISSUE TITLE
Virtualbox Guest Addtions Install Fails

### ISSUE THREAD

**Issue by kwhat** [myspaghetti/macos-virtualbox#214]
Hi, I noticed that the guest additions 6.1.6 for darwin fail to install without much of an error message.  Just that it encountered an error.  Are the vbox guest additions supported?  I am really just looking for shared folders and maybe clipboard sharing.

**Comment by myspaghetti** [comment]
Guest Additions need to be [notarized](https://www.virtualbox.org/ticket/19047), I suspect the 6.1.6 aren't.

As a workaround for clipboard sharing I suggest [Barrier](https://github.com/debauchee/barrier/releases) which is free and open-source and runs on macOS, Linux, and Windows. For shared folders I recommend `rsync`, it's not pretty but it works.
