### ISSUE TITLE
Explain why this is better than macOS Vagrant box

### ISSUE THREAD

**Issue by bittner** [myspaghetti/macos-virtualbox#217]
To run macOS with Virtualbox there also exist Vagrant boxes [link removed for possibly illegal content - myspaghetti] (to be installed à la `vagrant init ... && vagrant up`). It would be helpful if the README would mention that fact and explain

- why your approach is different
- why your approach may be superior

This could be as trivial as, "it doesn't require Vagrant" :smirk:, or maybe there is really more to it that everyone deserves to know?

Also, pointing out to alternatives is generally a sign of a self-confident project (I feel) and gives us users the possibility to make informed decisions.

**Comment by myspaghetti** [comment]
I feel the users are already 100% informed. The script is less than 2000 lines, over 50% of them are documentation and checks. Anybody with some grasp of English, even if they have never seen or used a bash script, can view the script and understand exactly what it does in about ten minutes.

This script does not replace Vagrant, it is a bootstrap script for use with Vagrant, QEMU, VMWare, or any other solution. The link you provided, which I removed, very likely hosts illegally-distributed software. This script does not rely on any third-party distribution of Apple software.

Feel free to answer your questions yourself and create a pull request to incorporate them into the readme.

**Comment by bittner** [comment]
>  The link you provided, which I removed, very likely hosts illegally-distributed software.

Come on, don't be ridiculous. The link I provided was the official, public Hashicorp Vagrant boxes repository, as linked to from their [official documentation](https://www.vagrantup.com/docs/boxes.html).

> I feel the users are already 100% informed. \[...\] understand exactly what it does in about ten minutes.

Thanks for clarifying! The "100% informed" doesn't obviously include me and everyone else who invests less than the 10 minutes you mention that are necessary to find out what your project does.

I don't know where your arrogance comes from. I'm very sorry if I hurt your feelings with what I asked, if that was the case.

TBH, this almost made me reconsider placing a PR to your README. But I'll do that now anyway, because I care that other visitors of your repository can benefit as I benefited from you answering my question—in a way that arguably leaves room for improvement.

**Comment by myspaghetti** [comment]
You didn't know what the script does and how it's different from Vagrant? You didn't know the software distributed at the link you provided is not distributed by Apple, who owns the rights to it?

I'm sure you already know the answers.

**Comment by sudoforge** [comment]
>  The link you provided, which I removed, very likely hosts illegally-distributed software. This script does not rely on any third-party distribution of Apple software.

Just to note here, the `myspaghetti/macos-virtualbox` script is itself enabling "illegal distribution"; even if you don't wish to call it that, by having a script which allows for virtualized installation of macOS, you are breaching the license.

There is similar language to that below in all licenses (quotes below from the Catalina license, emphasis within sections mine):

> **1. General.**
> A. _**The Apple software (including Boot ROM code), any third party software, documentation, interfaces, content, fonts and any data accompanying this License whether preinstalled on Apple-branded hardware, on disk, in read only memory, on any other media or in any other form (collectively the “Apple Software”) are licensed, not sold, to you by Apple Inc. (“Apple”) for use only under the terms of this License**_. Apple and/or Apple’s licensors retain ownership of the Apple Software itself and reserve all rights not expressly granted to you. You agree that the terms of this License will apply to any Apple-branded application software product that may be preinstalled on your Apple-branded hardware, unless such product is accompanied by a separate license, in which case you agree that the terms of that license will govern your use of that product.
>
> \<snip\>
>
> **2. Permitted License Uses and Restrictions.**
> A. Preinstalled and Single-Copy Apple Software License. Subject to the terms and conditions of this License, _**unless you obtained the Apple Software from the Mac App Store, through an automatic download or under a volume license, maintenance or other written agreement from Apple, you are granted a limited, non-exclusive license to install, use and run one (1) copy of the Apple Software on a single Apple-branded computer at any one time**_. For example, these single-copy license terms apply to you if you obtained the Apple Software preinstalled on Apple-branded hardware.
>
> \<snip\>
>
> B. __Mac App Store License__. If you obtained a license for the Apple Software from the Mac App Store or through an automatic download, then subject to the terms and conditions of this License and as permitted by the Services and Content Usage Rules set forth in the Apple Media Services Terms and Conditions (https://www.apple.com/legal/internet-services/itunes/) (“Usage Rules”), you are granted a limited, non-transferable, non-exclusive license:
>
>    (i) to download, install, use and run for personal, non-commercial use, one (1) copy of the
>    Apple Software directly on each Apple-branded computer running macOS Mojave, macOS
>    High Sierra, macOS Sierra, OS X El Capitan, OS X Yosemite, OS X Mavericks, OS X
>    Mountain Lion or OS X Lion (“Mac Computer”) that you own or control;
>
>    (ii) If you are a commercial enterprise or educational institution, to download, install, use and
>    run one (1) copy of the Apple Software for use either: (a) by a single individual on each of the
>    Mac Computer(s) that you own or control, or (b) by multiple individuals on a single shared
>    Mac Computer that you own or control. For example, a single employee may use the Apple
>    Software on both the employee’s desktop Mac Computer and laptop Mac Computer, or
>    multiple students may serially use the Apple Software on a single Mac Computer located at a
>    resource center or library; and
>
>    (iii) to install, use and run up to two (2) additional copies or instances of the Apple Software
>    within virtual operating system environments on each Mac Computer you own or control that
>    is already running the Apple Software, for purposes of: (a) software development; (b) testing
>    during software development; (c) using macOS Server; or (d) personal, non-commercial use.
>    The grant set forth in Section 2B (iii) above does not permit you to use the virtualized copies
>    or instances of the Apple Software in connection with service bureau, time-sharing, terminal
>    sharing or other similar types of services.
>
> \<snip\>
>
> J. **Other Use Restrictions**. The grants set forth in this License _**do not permit you to, and
> you agree not to, install, use or run the Apple Software on any non-Apple-branded computer, or
> to enable others to do so.You agree not to remove, obscure, or alter any proprietary notices
> (including trademark and copyright notices) that may be affixed to or contained within the Apple
> Software.**_ Except as otherwise permitted by the terms of this License or otherwise licensed by
> Apple: (i) only one user may use the Apple Software at a time, and (ii) you may not make the
> Apple Software available over a network where it could be run or used by multiple computers at > the same time. __*You may not rent, lease, lend, sell, redistribute or sublicense the Apple
> Software.**_

**Comment by myspaghetti** [comment]
1. The script doesn't distribute any Apple Software. The software is obtained directly from Apple.
2. "Having something which allows something else" is not a legal test. Your computer allows for hacking into the Pentagon and starting a nuclear war, but unless you use it as such, "allowing" this does not make your computer illegal.

Don't use the script illegally. Only use it in accordance with the macOS software license.

**Comment by sudoforge** [comment]
Perhaps it would be helpful if I limited the portion of the above blockquote that is most relevant here:

> J. Other Use Restrictions. The grants set forth in this License do not permit you to, and you agree not to, install, use or run the Apple Software on any non-Apple-branded computer, **or to enable others to do so**.

A virtual machine is indeed a non-Apple-branded computer, as described in the license. Additionally, you explicitly state that this script supports installation on Windows and Linux, which further cements that the intent of this script is to be cross-platform and _enable others to run Apple Software on non-Apple-branded computers_.

If this isn't clear enough, then I am at a loss at how to explain it differently. This repository is in direct violation of the license (although whether or not Apple decides to pursue taking this down is unknown).

**Comment by myspaghetti** [comment]
The script is a general-purpose installer of macOS on VirtualBox, the same way VirtualBox is a general-purpose virtualization application. It can *generally* run macOS. macOS is licensed to be virtualized on an Apple-branded computer. An Apple-branded computer can run Windows or Linux. If you are running Windows or Linux on an Apple-branded computer, you can use this script to run macOS on VirtualBox on an Apple-branded computer.

Whether you can do *something else* with the script that violates the license is up to you. The script no more "enables" you to do it than VirtualBox "enables" you to do it. They are general-purpose tools that can be, but are not designed to be, used illegally.

**Comment by zicklag** [comment]
I think it would be good to put in the README that it is illegal to use this script on non-Apple hardware. That is really easy to miss, especially when it says in the README that this runs on Windows and Linux. It's really easy to think, "Oh yay! I can run MacOS on my Linux machine to do builds, etc.".

Realistically almost nobody is really going to read that license and find that line themselves. They're just going to use this repo regardless of whether or not they are on a Mac. I think it's safe to say that 98% at least of people running Windows and Linux are not doing so on Apple hardware.

**Comment by myspaghetti** [comment]
I'm not here to give people legal advice.
