### ISSUE TITLE
install cannot complete

### ISSUE THREAD

**Issue by felix-d-git** [myspaghetti/macos-virtualbox#220]
the installscript is creating the machine without any problem.
when launched first it stops on this line.
what am I doing wrong?

I am using cygwin on Windows 10 (Ryzen 7).

![VirtualBox_macOS_25_05_2020_22_37_55](https://user-images.githubusercontent.com/24978665/82842083-9d747100-9ed8-11ea-85b8-f30d1b66303b.png)

**Comment by felix-d-git** [comment]
I've already tried all the cpu profiles

**Comment by felix-d-git** [comment]
Duplate of https://github.com/myspaghetti/macos-virtualbox/issues/8, but still cant find the answer there ;(

**Comment by CoalUnicorn** [comment]
Had the same problem on AMD Ryzen 7 PRO 3700U
Running with this profile works for me.
VBoxManage modifyvm "Mojave" --cpu-profile "Intel Xeon X5482 3.20GHz"

When I restarted the VM got to installer
![image](https://user-images.githubusercontent.com/17591103/82844668-3e632c00-9ed9-11ea-8059-921a82d0ae26.png)

**Comment by nathanp** [comment]
Thank you, this worked great for my Ryzen 7 3800X.

If you haven't used `VBoxManage` in the command line, just follow the steps on http://www.roelpeters.be/vboxmanage-is-not-recognized-and-how-to-solve-it/ to set it up.
