### ISSUE TITLE
Unclear how to reach near native performance on WSL2

### ISSUE THREAD

**Issue by pinoli** [myspaghetti/macos-virtualbox#222]
Hello @myspaghetti, thanks for the awesome work.
I don't know if this is the right place but I can't find any other way to contact you.

I was able to start macOS in VirutalBox in Windows 10, using Debian 10 Buster running on WSL2. 
After that, I was really curious to expand on your [Performance paragraph](https://github.com/myspaghetti/macos-virtualbox#performance), but I fail to understand where to start.
You say that a way to improve performance is to move the VM (after conversion to .vdmk) to a level 1 hypervisor like QEMU/KVM. I don't understand if you are talking about about moving it to QEMU inside the WSL2 Debian distro I used to create the macOS VM in the first place.

AFAIK WSL2 is already running in a VM (a highly optimized one), so even if I were able to move it from VirtualBox to QEMU inside WSL2, I fail to see how I would get "almost native performance", since this would be a nested virtualization (and I don't even know if this going to work, I found very little on this topic on the web).
Can you please expand a little bit on this point? Possibly I am not getting what you are hinting at, maybe move the macOS VM to another machine (not Windows) running a level 1 hypervisor?

I am really interested in the possibility of getting higher performance on Windows, so I kindly ask if you can share some more about this or point us to relevant material like articles or documentation.

Thanks again for this amazing project.

**Comment by myspaghetti** [comment]
KVM is Linux-only.
