### ISSUE TITLE
Will VM work on AMD?

### ISSUE THREAD

**Issue by tcab** [myspaghetti/macos-virtualbox#223]
Win 10 on AMD Ryzen 3700x, Virtual Box 6.1, ran script under WSL 1 which reaches:

```
stage: populate_virtual_disks
Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, see the documentation
for information about applying different CPU profiles.

Until the script completes, please do not interact with the virtual machine.

Press enter when the Language window is ready.
```

however the virtualbox vm seems to be frozen at this point
![mac virtualbox script - freezes](https://user-images.githubusercontent.com/11467530/82856316-013a8080-9f51-11ea-82cf-fc05863a9b87.png)

Presumably I have hit the ` If booting fails, see the documentation
for information about applying different CPU profiles.` situation. 

Reading the script (which is difficult because of the code and highlighting codes) shows this fragment (is there a way of displaying this help properly via the script?):

```
macOS does not supprort every CPU supported by VirtualBox. If the macOS Base
System does not boot, try applying different CPU profiles to the virtual
machine with the following command:
    ${low_contrast_color}VBoxManage modifyvm \"\${vm_name}\" --cpu-profile \"\${cpu_profile}\"${default_color}
Available CPU profiles:
  ${low_contrast_color}\"Intel Xeon X5482 3.20GHz\"  \"Intel Core i7-2635QM\"  \"Intel Core i7-3960X\"${default_color}
  ${low_contrast_color}\"Intel Core i5-3570\"  \"Intel Core i7-5600U\"  \"Intel Core i7-6700K\"${default_color}
Remove existing CPU profiles with the following commands:
    ${low_contrast_color}VBoxManage modifyvm \"\${vm_name}\" --cpu-profile host${default_color}
    ${low_contrast_color}VBoxManage modifyvm \"\${vm_name}\" --cpuidremoveall${default_color}
```

suggests I use the `VBoxManage modifyvm` command to play with cpu profiles. The command is at `"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS ...` but I'm not sure what to do at this point? 
- Am I wasting my time getting this to work on my AMD cpu?
- Do I run the script again after making changes, and will it re-use the existing VM?

**Comment by myspaghetti** [comment]
macOS has been reported to work in VirtualBox on some AMD processors by using one of the six supported CPU profiles.

The documentation is supposed to be read with the command `./macos-guest-virtualbox.sh documentation` or, if you have `less`, with `./macos-guest-virtualbox.sh documentation | less -R`

**Comment by tcab** [comment]
Sorry - didn't see the documentation option at first reading.

I tried virtualbox settings, "Enable Nested VT-x/AMD-V" then changing all the possible cpu profiles.
Most of these gave me a UEFI interactive shell which goes into bios - had to select boot manager from file menu option and select System\Library\CoreServices\boot.efi to continue - not sure if that's the correct thing to do, but at least the vm proceeded and attempted to boot.

```
"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Core i7-6700K"
freeze

"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Core i7-5600U"
freeze

"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Core i7-3960X"
memory panic

"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
memory panic

"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Xeon X5482 3.20GHz"
memory panic

"\Program Files\Oracle\VirtualBox\VBoxManage.exe" modifyvm macOS --cpu-profile "Intel Core i5-3570"
No UEFI prompt
CPUM internal processing error #1. (VERR_CPUM_IPE_1).
```

Thus, no luck. Digging any further through countless hackintosh/virtualbox posts on the internet and then correlating any information I might find there with the operation of this script is not something I'm keen to proceed with. Its ceased to be a "Push-button installer of macOS on VirtualBox" situation!

Given the prevalence and popularity of AMD cpus these days, it would be helpful to a lot of people if someone helped with AMD specific instructions. Perhaps also one day a script that also handles AMD hosts.

**Comment by myspaghetti** [comment]
The documentation says:

>macOS does not supprort every CPU supported by VirtualBox.

Since you tried all the CPU profiles and none of them worked, it stands to reason that macOS does not support your CPU... Assuming your CPU is not lacking any features that macOS requires, you can disable any unnecessary CPU features through the [CPUID settings](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport).

>specific instructions

You can test different CPUID settings and leave specific instructions for your CPU here.

**Comment by tcab** [comment]
Finally got it working on my AMD Ryzen 3700x windows 10 host, running the script under WSL v1 !
Inserting these two lines in the script made it work:

```
VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
```

Here are my tips, just in case anyone cares:

- Move script `macos-guest-virtualbox.sh` into `/mnt/c/Users/YOURNAME/Documents/mac` and run it there. More reliable than WSL 1 apparently.

- Put `\Program Files\Oracle\VirtualBox\` in your path to make running VBoxManage.exe easier.

- You don't need VT-x/AMD-V setting in the vm

- If you get a corrupted image issues, delete everything and move the script to a proper windows dir and run it from there (run from within WSL 1 of course)

- If you want to restart from a particular stage, you can't.  You can run individual stages, but you can't proceed from a stage onwards.  So if you want to make mods, make them to the script and start from scratch. E.g. edit `C:\Users\YOURNAME\Documents\mac\macos-guest-virtualbox.sh`

```bash
# Attempt to create new virtual machine named "${vm_name}"
function create_vm() {
print_dimly "stage: create_vm"
if [[ -n "$( VBoxManage createvm --name "${vm_name}" --ostype "MacOS1013_64" --register 2>&1 >/dev/null )" ]]; then
    echo -e "\nError: Could not create virtual machine \"${vm_name}\"."
    echo -e "${highlight_color}Please delete exising \"${vm_name}\" VirtualBox configuration files ${warning_color}manually${default_color}.\n"
    echo -e "Error message:\n"
    VBoxManage createvm --name "${vm_name}" --ostype "MacOS1013_64" --register 2>/dev/tty
    exit
fi

# my inserted lines: 
VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
print_dimly "applied my mods ok"
 
}
```

- Yes you can restart stages of the script with e.g.
```bash
./macos-guest-virtualbox.sh populate_virtual_disks
./macos-guest-virtualbox.sh populate_macos_target_disk
./macos-guest-virtualbox.sh populate_virtual_disks
```
Presumably you can run all the command stages after your point of failure, one by one, (see the documentation via `./macos-guest-virtualbox.sh documentation` which lists the stages) but really, its easer to just insert the fixes to the script and start from scratch.

- When the script fails, delete your VM directory `C:\Users\YOURNAME\VirtualBox VMs\macOS` and run again.

- If you get into a UEFI interactive shell which goes into BIOS thing, you are stuffed but you can make the best of it by figuring out how to get the machine to boot. Select `exit` which enters the BIOS - Select Boot From File and select `System\Library\CoreServices\boot.efi` to attempt to boot. Once you figure out the settings that work, which for me were:

```
VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
```

make those changes to the script and start from scratch.

- Display resolution: As per this issue post #194 these are the primary display resolutions supported by macOS on VirtualBox: 5120x2880 2880x1800 2560x1600 2560x1440 1920x1200 1600x1200 1680x1050 1440x900 1280x800 1024x768 and 640x480
```
VBoxManage setextradata macOS "VBoxInternal2/EfiGraphicsResolution" "2560x1440"
```
If you get into fullscreen mode and can't get out, hit `R.CTRL HOME` to get a menu

**Comment by iamsee** [comment]
same 3700x 
![image](https://user-images.githubusercontent.com/6944557/85028191-5878ed00-b1ad-11ea-851d-64c3266ec9c1.png)
pls help

**Comment by smk762** [comment]
Thanks, can confirm running adding the below worked in Ubuntu 18.04 with AMD® Ryzen 7 3700x  CPU
```
VBoxManage modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
```

**Comment by kvn1351** [comment]
> Finally got it working on my AMD Ryzen 3700x windows 10 host, running the script under WSL v1 !
> Inserting these two lines in the script made it work:
> 
> ```
> VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
> VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
> ```
> 
> Here are my tips, just in case anyone cares:
> 
> * Move script `macos-guest-virtualbox.sh` into `/mnt/c/Users/YOURNAME/Documents/mac` and run it there. More reliable than WSL 1 apparently.
> * Put `\Program Files\Oracle\VirtualBox\` in your path to make running VBoxManage.exe easier.
> * You don't need VT-x/AMD-V setting in the vm
> * If you get a corrupted image issues, delete everything and move the script to a proper windows dir and run it from there (run from within WSL 1 of course)
> * If you want to restart from a particular stage, you can't.  You can run individual stages, but you can't proceed from a stage onwards.  So if you want to make mods, make them to the script and start from scratch. E.g. edit `C:\Users\YOURNAME\Documents\mac\macos-guest-virtualbox.sh`
> 
> ```shell
> # Attempt to create new virtual machine named "${vm_name}"
> function create_vm() {
> print_dimly "stage: create_vm"
> if [[ -n "$( VBoxManage createvm --name "${vm_name}" --ostype "MacOS1013_64" --register 2>&1 >/dev/null )" ]]; then
>     echo -e "\nError: Could not create virtual machine \"${vm_name}\"."
>     echo -e "${highlight_color}Please delete exising \"${vm_name}\" VirtualBox configuration files ${warning_color}manually${default_color}.\n"
>     echo -e "Error message:\n"
>     VBoxManage createvm --name "${vm_name}" --ostype "MacOS1013_64" --register 2>/dev/tty
>     exit
> fi
> 
> # my inserted lines: 
> VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
> VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
> print_dimly "applied my mods ok"
>  
> }
> ```
> 
> * Yes you can restart stages of the script with e.g.
> 
> ```shell
> ./macos-guest-virtualbox.sh populate_virtual_disks
> ./macos-guest-virtualbox.sh populate_macos_target_disk
> ./macos-guest-virtualbox.sh populate_virtual_disks
> ```
> 
> Presumably you can run all the command stages after your point of failure, one by one, (see the documentation via `./macos-guest-virtualbox.sh documentation` which lists the stages) but really, its easer to just insert the fixes to the script and start from scratch.
> 
> * When the script fails, delete your VM directory `C:\Users\YOURNAME\VirtualBox VMs\macOS` and run again.
> * If you get into a UEFI interactive shell which goes into BIOS thing, you are stuffed but you can make the best of it by figuring out how to get the machine to boot. Select `exit` which enters the BIOS - Select Boot From File and select `System\Library\CoreServices\boot.efi` to attempt to boot. Once you figure out the settings that work, which for me were:
> 
> ```
> VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
> VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-2635QM"
> ```
> 
> make those changes to the script and start from scratch.
> 
> * Display resolution: As per this issue post #194 these are the primary display resolutions supported by macOS on VirtualBox: 5120x2880 2880x1800 2560x1600 2560x1440 1920x1200 1600x1200 1680x1050 1440x900 1280x800 1024x768 and 640x480
> 
> ```
> VBoxManage setextradata macOS "VBoxInternal2/EfiGraphicsResolution" "2560x1440"
> ```
> 
> If you get into fullscreen mode and can't get out, hit `R.CTRL HOME` to get a menu

Works on Windows 10 Pro 2004 with VirtualBox 16.1.4 on a Ryzen 3600.

Before stumbling on this post, I doing the same via CMD once the script was waiting for the language screen. I got a `Configuration error: Querying "UUID" failed (VERR_CFGM_VALUE_NOT_FOUND).` however.

So it seems that these commands have to be performed right when the machine is being created.

I have wasted over 4 hours on this. I hope that someone else with this error might be saved from the same.

**Comment by meydominic** [comment]
I had to turn off HyperV by powershell to get it working:

- Starting Powershell with admin rights
- run `bcdedit /set hypervisorlaunchtype off`
- restart

Running 10.15 with AMD Ryzen 1600X with modifications from tcab.
