### ISSUE TITLE
Error message about hardware virtualization should mention Docker Desktop

### ISSUE THREAD

**Issue by agabert** [myspaghetti/macos-virtualbox#226]
The hardware virtualization error message also appears when Docker Desktop is installed.
Uninstalling it and rebooting makes the script continue.

**Comment by myspaghetti** [comment]
Since Docker Desktop requires manually enabling Hyper-V, people who use it should be aware that they have Hyper-V enabled. The error message doesn't need to mention every single application that uses Hyper-V.
