### ISSUE TITLE
Installation fails at stage populate_macos_target_disk .

### ISSUE THREAD

**Issue by psjbk** [myspaghetti/macos-virtualbox#230]
![errors](https://user-images.githubusercontent.com/51746608/83032018-eb14e900-a052-11ea-94fa-684bc503fdda.png)

Hello, @myspaghetti my virtual machine fails to install at the stage mentioned above. I've tried to inspect this myself and I think virtual machine isn't closed fully before executing this stage.

The message given by the script can be seen in the attached image.

Every Time the installation fails at the same stage. If you can not fix that please tell me the steps to proceed ahead so I can proceed with the installation manually.

Attached `troubleshoot.txt` below 👇 .
[troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4689358/troubleshoot.txt)

**Comment by myspaghetti** [comment]
You can continue the script from where you left off with the following command:
```
./macos-guest-virtualbox.sh populate_macos_target_disk
```
I'll add another delay while the virtual machine powers off to avoid this situation.

**Comment by psjbk** [comment]
@myspaghetti thanks for the quick response. I'll try and give you the update by Friday.

P.S. : You can add me to repository contribution. I really love this repo and would like to keep it updated and free of issues. I would also like to build a wiki with good docs for this repo.

**Comment by myspaghetti** [comment]
Thanks.

* If you want to contribute please fork the repo and create a pull request.
* I would like to avoid a wiki. Everything should be in the offline documentation.

A useful feature could be a [CPUID database](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) for CPUs that are incompatible with macOS. However, I would not want this database to be on this repo.

**Comment by myspaghetti** [comment]
Increased the wait from three seconds to five seconds in [version 0.93.5](https://github.com/myspaghetti/macos-virtualbox/commit/78d7353d42e3d0874c3a2cf942ec215e96a7eada). Unfortunately there's no way to detect that the GUI is still open using `VBoxManage` so hard-coded wait times will have to do.

**Comment by psjbk** [comment]
> Thanks.
> 
> * If you want to contribute please fork the repo and create a pull request.
> * I would like to avoid a wiki. Everything should be in the offline documentation.
> 
> A useful feature could be a [CPUID database](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) for CPUs that are incompatible with macOS. However, I would not want this database to be on this repo.

@myspaghetti Sure.

**Comment by psjbk** [comment]
@myspaghetti thanks VM installed successfully.
