### ISSUE TITLE
VM doesn't boot after changing CPU profiles

### ISSUE THREAD

**Issue by KevinIsMyName** [myspaghetti/macos-virtualbox#232]
Ran into a VM not booting after running script. Consulted the documentation, and after running 

```
VBoxManage modifyvm "macOS" --cpu-profile host
VBoxManage modifyvm "macOS" --cpuidremoveall
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```
The VM continued to not boot.

Here's a screenshot if it helps.
![your documentation doesn't work](https://user-images.githubusercontent.com/36412364/83069577-1e964a00-a038-11ea-9c39-4465672a8c64.png)

I found the instructions [here](https://www.geekrar.com/how-to-install-macos-catalina-on-virtualbox-on-amd-systems/) helpful, as it helped the VM boot after following its CPU profile steps. Once the VM booted, I ignored the article I just linked and continued on with your script, and installation went smoothly after that. Hopefully the link gives you some insight on what went wrong. Perhaps because I'm on an AMD Ryzen 5 2600X, and something just doesn't like non-Intel?

Anyway, I got the VM working in the end. Thanks!

**Comment by myspaghetti** [comment]
Since it's unclear, I'll add information to the documentation about CPU profiles and CPUID.

**Comment by Drakeo** [comment]
same thing in 6.1.20 and up only  mac profile used is 
VBoxManage modifyvm "<VM name>" --cpu-profile "Intel Xeon X5482 3.20GHz"
which has slowed my mac VBox down on my mac book pro
