### ISSUE TITLE
High Sierra seemed to install a Beta version of the OS.

### ISSUE THREAD

**Issue by atsushi1** [myspaghetti/macos-virtualbox#234]
First, I want to say this is an awesome script. I have been testing various versions of macOS to see if I could get iMessages to work. I did notice that High Sierra installs a beta version. This is just an FYI. Catalina and Mojave seem to be the latest versions.

**Comment by myspaghetti** [comment]
Thanks! Fixed in [version 0.93.6](https://github.com/myspaghetti/macos-virtualbox/commit/61f8fccd49c885ea9b99babd743e580cae731081)
