### ISSUE TITLE
macos-guest-virtualbox.sh: 15: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by Ngals** [myspaghetti/macos-virtualbox#235]
Hi,
thanks by advance for the script!
I am a beginner and wanted to try but I always have this error ?
macos-guest-virtualbox.sh: 15: Syntax error: "(" unexpected

what's wrong I am doing?

**Comment by myspaghetti** [comment]
Hi! You appear to be running the script with `/bin/sh`

The script requires `bash` or `zsh`. Please try to execute the script with `/bin/bash macos-guest-virtualbox.sh`

**Comment by Ngals** [comment]
> Hi! You appear to be running the script with /bin/sh
> The script requires bash or zsh. Please try to execute the script with /bin/bash macos-guest-virtualbox.sh

Of course…. A beginner I said (juste see .sh)

Thanks! I wait & see now
