### ISSUE TITLE
I am stuck after first vm popup window

### ISSUE THREAD

**Issue by shmox75** [myspaghetti/macos-virtualbox#237]
I am on manjaro KDE and here is my screenshot
![Screenshot_20200528_174042](https://user-images.githubusercontent.com/39054055/83170030-d3e60200-a10b-11ea-89b1-b7f098c31b52.png)

**Comment by myspaghetti** [comment]
See the documentation about CPU profiles and CPUID. If none of the profiles work, search the internet for a your CPU's VirtualBox CPUID for macOS.
