### ISSUE TITLE
The Readme.md points to the untested macos-guest-virtualbox.sh , please point it to a Release

### ISSUE THREAD

**Issue by victor871129** [myspaghetti/macos-virtualbox#239]
Also, you treat your audience of unexperienced people who wants to try a Mac on their machine as computer experts, maybe you should explain what is a WSL or a .sh file first

**Comment by myspaghetti** [comment]
I think maybe you've been misled? This is a bash script for people who know how to run a bash script. This is not a tutorial about running bash scripts on WSL.
