### ISSUE TITLE
check_default_virtual_machine

### ISSUE THREAD

**Issue by guiguil81** [myspaghetti/macos-virtualbox#241]
Hello, i start your script but i have this error:

Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.

I have windows build 2004 and wsl 2 is enabled.

my troubleshoot
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4717904/macOS_troubleshoot.txt)

![2020-06-02](https://user-images.githubusercontent.com/39791649/83534695-75e16200-a4f1-11ea-9d44-b0f4704083da.png)

**Comment by myspaghetti** [comment]
From the log:
```
00:01:22.049472 HM: HMR3Init: Attempting fall back to NEM: VT-x is not available
```
This means hardware-supported virtualization is not available for VirtualBox. This happens when features such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other virtualization features are enabled, and sometimes because third-party virtualization software is active.

Turn off these features to use VT-x in VirtualBox.

**Comment by startergo** [comment]
> 
> 
> From the log:
> 
> ```
> 00:01:22.049472 HM: HMR3Init: Attempting fall back to NEM: VT-x is not available
> ```
> 
> This means hardware-supported virtualization is not available for VirtualBox. This happens when features such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other virtualization features are enabled, and sometimes because third-party virtualization software is active.
> 
> Turn off these features to use VT-x in VirtualBox.

Well I got the same issue and yes I have WSL2, but VT-X is enabled:
![image](https://user-images.githubusercontent.com/7897244/85934928-0a07d480-b8b8-11ea-90e4-5b2cdc5b8246.png)
[VBox.log](https://github.com/myspaghetti/macos-virtualbox/files/4841499/VBox.log)

**Comment by startergo** [comment]
I have just block commented the hardware check in the script, because it is definitely not doing the VT-x check correctly:
```
 # if [[ "${vbox_log}" =~ ${regex} ]]; then
    # echo -e "\nVirtualbox is not using hardware-supported virtualization features."
    # if [[ -n "$(cygcheck -V 2>/dev/null)" ||
          # "$(cat /proc/sys/kernel/osrelease 2>/dev/null)" =~ [Mm]icrosoft ]]; then
        # echo "Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity"
        # echo "protection, and other Windows features that lock virtualization are turned off."
    # fi
    # echo "Exiting."
    # exit
# fi
```

**Comment by myspaghetti** [comment]
@startergo from your log:
```
00:00:03.042287 HM: HMR3Init: Attempting fall back to NEM: VT-x is not available
```

**Comment by startergo** [comment]
I am retracting my statement about disabling deviceguard check, because the script breaks at another point. I used a PS1 script to disable device guard:
```
# Get the ID and security principal of the current user account
$myWindowsID = [System.Security.Principal.WindowsIdentity]::GetCurrent();
$myWindowsPrincipal = New-Object System.Security.Principal.WindowsPrincipal($myWindowsID);

# Get the security principal for the administrator role
$adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator;

# Check to see if we are currently running as an administrator
if ($myWindowsPrincipal.IsInRole($adminRole))
{
    # We are running as an administrator, so change the title and background colour to indicate this
    $Host.UI.RawUI.WindowTitle = $myInvocation.MyCommand.Definition + "(Elevated)";
    $Host.UI.RawUI.BackgroundColor = "DarkBlue";
    Clear-Host;
}
else {
    # We are not running as an administrator, so relaunch as administrator

    # Create a new process object that starts PowerShell
    $newProcess = New-Object System.Diagnostics.ProcessStartInfo "PowerShell";

    # Specify the current script path and name as a parameter with added scope and support for scripts with spaces in it's path
    $newProcess.Arguments = "-windowstyle hidden & '" + $script:MyInvocation.MyCommand.Path + "'"

    # Indicate that the process should be elevated
    $newProcess.Verb = "runas";

    # Start the new process
    [System.Diagnostics.Process]::Start($newProcess);

    # Exit from the current, unelevated, process
    Exit;
}

Add-Type -AssemblyName System.Windows.Forms


$state = bcdedit /enum | Select-String -Pattern 'hypervisorlaunchtype\s*(\w+)\s*'


if ($state.matches.groups[1].ToString() -eq "Off"){

    $UserResponse= [System.Windows.Forms.MessageBox]::Show("Enable Hyper-V?" , "Hypervisor" , 4)

    if ($UserResponse -eq "YES" ) 
    {

        bcdedit /set hypervisorlaunchtype auto
        [System.Windows.Forms.MessageBox]::Show("Enabled Hyper-V. Reboot to apply." , "Hypervisor")

    } 

    else 

    { 

        [System.Windows.Forms.MessageBox]::Show("No change was made." , "Hypervisor")
        exit

    }

} else {

    $UserResponse= [System.Windows.Forms.MessageBox]::Show("Disable Hyper-V?" , "Hypervisor" , 4)

    if ($UserResponse -eq "YES" ) 
    {

        bcdedit /set hypervisorlaunchtype off
        [System.Windows.Forms.MessageBox]::Show("Disabled Hyper-V. Reboot to apply." , "Hypervisor")

    } 

    else 

    { 

        [System.Windows.Forms.MessageBox]::Show("No change was made." , "Hypervisor")
        exit

    }

}
```
Maybe you can integrate it in your script? I appreciate the excellent work you have done.

**Comment by myspaghetti** [comment]
Thanks, but there are a number of reasons not to attempt this:

1. This is a Bash script, not a PowerShell script
2. The script does not require elevated privileges. This is by design. If the user wants to disable critical system features like core isolation or Hyper-V, it really should be done manually and not by some unsigned elevated-privileges script off the internet.
3. VT-x is not only made unavailable to VirtualBox by Hyper-V. There's also core isolation, device guard, credential guard, and other features that block VirtualBox from using VT-x.
4. VT-x might be disabled in BIOS and not accessible through the OS at all.

I don't want the script monkeying around with the user's system settings.

**Comment by SeidChr** [comment]
ok, just disabling the hypervisor didnt do it for me

also i have never seen a one-botton-installation on that i've had to press so many buttons to fix one issue after the other. :-(

**Comment by SeidChr** [comment]
Ended up commenting it out. I have disabled everything from any website i found regarding virtualization and virtual box, but it still wouldnt go away. 
Guess i need to run it slow.

**Comment by damonlynch** [comment]
> You know, that running your script in WSL means basically, that you are asking to disable the very thing your thing is executed in?

WSL & WSL2 are _fundamentally_ different. See for instance https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq

**Comment by SeidChr** [comment]
Is there a way to figure out for sure what is locking down these virtualization resources?

**Comment by myspaghetti** [comment]
No. Windows doesn't report which feature is using VT-x. You'll have to go through each of the Windows features that might be using VT-x and disable them. There is no comprehensive list. You'll also have to make sure no other software installed on your computer is blocking access to VT-x.

**Comment by regunakyle** [comment]
Do I need to keep other VT-x features disabled even after installing the vm?

**Comment by myspaghetti** [comment]
If you plan on using VirtualBox for macOS virtualization on Windows, yes. Microsoft plans on releasing WSL-g with nested virtualization by the end of the year (though they might not) so when that happens the script will switch to VirtualBox on WSL-g, which won't require disabling Hyper-V any more (in fact it will require having Hyper-V enabled).

**Comment by tscizzlebg** [comment]
I know there's no comprehensive list of features to disable, but if the list in the script is supposed to list the most common ones, I'll put in my data point that disabling all the ones listed there hasn't gotten me past that step.

For those googling the error message and wondering HOW to disable those many features, Control Panel -> Programs and Features -> "Turn Windows features on or off" in the top left -> find each one (Hyper-V, WSL, which is Windows Subsystem for Linux, Windows Sandbox). Though, "Memory integrity protection" was a toggle I found in "Windows Security" -> "Core isolation" in the Start Menu.

**Comment by Cureno** [comment]
Hello @SeidChr, @tscizzlebg,
I suggest turning the following **OFF**:
in **"Turn Windows features on or off"**
- Hyper-V (both Hyper-V Management Tools and Hyper-V Platform)
- Microsoft Defender Application Guard
- Virtual Machine Platform
- Windows Hypervisor Platform
- Windows Sandbox
- Windows Subsystem for Linux

**AND** in Windows Security -> Device security -> Core Isolation (details) -> Memory integrity

**Comment by shrinidhi111** [comment]
> Hello @SeidChr, @tscizzlebg,
> I suggest turning the following **OFF**:
> in **"Turn Windows features on or off"**
> 
> * Hyper-V (both Hyper-V Management Tools and Hyper-V Platform)
> * Microsoft Defender Application Guard
> * Virtual Machine Platform
> * Windows Hypervisor Platform
> * Windows Sandbox
> * Windows Subsystem for Linux
> 
> **AND** in Windows Security -> Device security -> Core Isolation (details) -> Memory integrity


This is literally the only helpful comment in this whole thread. Just disabling Hyper-V was not enough. Others are needed too.

Thank you!

**Comment by Masamune3210** [comment]
Its been mentioned multiple times in multiple other threads the list of things needed to be turned off, to the point that most people are just tired of repeating themselves. Look at other issues next time you are having a problem please

**Comment by myspaghetti** [comment]
@shrinidhi111 it's literally mentioned in the first reply:

>This happens when features such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other virtualization features are enabled, and sometimes because third-party virtualization software is active.

People don't read.

**Comment by myspaghetti** [comment]
It's mentioned in the readme too and in the documentation. I'm deleting this issue.
