### ISSUE TITLE
Keyboard integration issues.

### ISSUE THREAD

**Issue by psjbk** [myspaghetti/macos-virtualbox#243]
Hello everyone, I know this issue isn't related to the repo but I would like to ask that how you guys integrated your Windows keyboard with the VM. 

I can't designate any key as COMMAND key.

**Comment by myspaghetti** [comment]
The Windows key is the Command key.

**Comment by psjbk** [comment]
@myspaghetti really ? Then what is the ctrl key for in Mac OS ?

**Comment by psjbk** [comment]
> The Windows key is the Command key.

@myspaghetti Can you tell the whole keyboard mapping for MacOS.

**Comment by myspaghetti** [comment]
[Windows is Command, Control is Control, Alt is Option](https://support.apple.com/en-ie/HT202676)

**Comment by myspaghetti** [comment]
>Can you tell the whole keyboard mapping for MacOS.

Yes, enable Accessibility Keyboard and then when you press a key on your keyboard it will be highlighted in red on the on-screen Accessibility Keyboard.
![accessibility keyboard](https://user-images.githubusercontent.com/31696646/83759298-064bae00-a67c-11ea-860c-6e329739ba6a.png)

**Comment by psjbk** [comment]
@myspaghetti thank you so much for helping me out.
