### ISSUE TITLE
How to re-open the VM

### ISSUE THREAD

**Issue by satan87** [myspaghetti/macos-virtualbox#245]
Hello,

I manage to create the VM, then I close it.
How can I re-open it. It's not showing on my VirtualBox.

here the files I have:
<img width="388" alt="Screen Shot 2020-06-05 at 4 10 34 PM" src="https://user-images.githubusercontent.com/5104971/83918597-18465300-a747-11ea-9fc1-bbfd5d59f156.png">

Thanks,
Nicolas

**Comment by myspaghetti** [comment]
You can [manually add a VM to VirtualBox from the GUI](https://www.virtualbox.org/manual/ch01.html#gui-createvm) or with [`VBoxManage`](https://www.virtualbox.org/manual/ch08.html#vboxmanage-createvm), or if the `.vbox` file is still available you can [register it](https://www.virtualbox.org/manual/ch08.html#vboxmanage-registervm), or you can use the script with `./macos-guest-virtualbox.sh create_vm configure_vm` then attach the `macOS.vdi` virtual disk image file to the new virtual machine.
