### ISSUE TITLE
Mouse capture can't be stopped

### ISSUE THREAD

**Issue by realestninja** [myspaghetti/macos-virtualbox#248]
The VM was working fine so far, but since today it seems the mouse is permanently captured while it wasn't captured at all before. I never needed the Host key and noticed today that the host key doesn't seem to do anything. Is this a known problem? Right now I need to shut down the VM to get out of it.

**Comment by myspaghetti** [comment]
The script sets the pointing device as `usbtablet` which does not capture the mouse. Make sure your virtual machine doesn't have your pointing device in the USB filters and that your pointing device is not set to `ps2` or `usb`

**Comment by realestninja** [comment]
Thanks for your quick response. Those two settings were indeed the issue. It works again now. Thanks :pray:
