### ISSUE TITLE
No audio 

### ISSUE THREAD

**Issue by LEUNGUU** [myspaghetti/macos-virtualbox#253]
Hi,

What I am using is ubuntu(18.04) host and macos guest in virtualbox.  After running the script, everything works well except the audio. May I get help?

Vbox setting:
![image](https://user-images.githubusercontent.com/7521775/85185111-26f34500-b2c5-11ea-990a-c34804cc3915.png)

In macos, there is no driver can be found in Input/Output configuration pane.

Thanks in advanced.

**Comment by psjbk** [comment]
@LEUNGUU audio doesn't work with the default installation of MacOS. You need to get a bootloader such as OpenCore and a audio kext(driver) for MacOS from online (do a Google search) to make the audio work.

**Comment by myspaghetti** [comment]
I can't believe this has to be said: do not reply to questions with "google it" or similar comments. If you can't be helpful, don't reply.
