### ISSUE TITLE
macOS 11.0 Big Sur

### ISSUE THREAD

**Issue by myspaghetti** [myspaghetti/macos-virtualbox#254]
Big Sur boots on VirtualBox but crashes when accessing the secure keychain. Anybody having the same issue?

**Comment by myspaghetti** [comment]
Seems like the installer finishes even though parts of it fail. Testing whether a bootable installer made with `--downloadassets` will properly install.

**Comment by myspaghetti** [comment]
Surprisingly, AppleKeyStore works when there is no network connection. I wonder what macOS is doing...
![bigsur](https://user-images.githubusercontent.com/31696646/85652472-82517880-b6b3-11ea-81a5-32b0e988c597.jpg)

**Comment by myspaghetti** [comment]
Surprisingly, AppleKeyStore works when there is no network connection. I wonder what macOS is doing...
![bigsur](https://repository-images.githubusercontent.com/156108442/54b8ff00-b6b4-11ea-96d2-c21f40531ab9)

**Comment by myspaghetti** [comment]
Works with USB version set to 1.1 instead of 3.0 and network adapters disabled. USB can be set to 3.0 and network adapters can be enabled after the initial setup is complete.

![bigsur](https://repository-images.githubusercontent.com/156108442/54b8ff00-b6b4-11ea-96d2-c21f40531ab9)

**Comment by tcab** [comment]
This is great news! 

How do we refer to Big Sur in the script?  I tried `macOS_release_name="Bigsur"` and `macOS_release_name="BigSur"` but Mojave keeps getting downloaded.

Also how do we make the USB and network changes you describe?  Are these somewhere in the script, or more likely, in the VirtualBox VM settings? At which point in the script lifecycle can we alter the VM settings and restart the VM, without the script being interrupted?

**Comment by myspaghetti** [comment]
The script doesn't support Big Sur at the moment. There are no current plans for the script to support the current installer of Big Sur since it needs to be unpacked from a `pkg` file, and such unpacking software is not available by default on most systems' package managers. There are [macOS-host-only scripts](https://github.com/AlexanderWillner/runMacOSinVirtualBox) that unpack the `pkg` file automatically.

The USB and network settings are done through `VBoxManage` or the VirtualBox graphical interface. Currently, with Big Sur version `20A4299v` the system's secure keychain `AppleKeyStore` crashes occasionally when networking or USB 3.0 is enabled.

If you want to manually install Big Sur you can follow these steps:

1. Install Catalina
2. [Download Big Sur `InstallAssistant.pkg`](http://swcdn.apple.com/content/downloads/15/52/001-18401-A_I5FFC1VB5J/rrfxkhkf3ykxzj3zjshu1srsh4n74a41n4/InstallAssistant.pkg) version `20.0.4299.22` (this link will be dead when a new version comes out) either inside the virtual machine or on the host on a disk image that will be mounted on the virtual machine. Windows can create and mount VHD disk images through Disk Management, which can then be unmounted and attached to the virtual machine.
3. Use VirtualBox to create an additional disk image that has at least 60GB of storage space. Attach it to the virtual machine and erase it with Disk Utility, formatting it to APFS.
4. Run `InstallAssistant.pkg` which creates the app "Install macOS Beta.app" in the `/Applications` folder
5. Run "Install macOS Beta.app", when prompted select "Show All Disks..." and select the new empty disk.
6. Allow the installer to complete, it will automatically boot into macOS Big Sur. When the macOS initial setup starts, shut down macOS with Command-Q
7. Set the virtual machine's USB version to 1.1 and disable all network adapters from the VirtualBox settings (`AppleKeyStore`, the system's secure keychain, crashes otherwise)
8. Boot macOS Big Sur and complete the initial setup
9. After initial setup is complete the USB settings and network adapters can be restored, but this will make `AppleKeyStore` crash occasionally.

**Comment by tcab** [comment]
Above procedure works! A few observations:
- I got AppleKeyStore crashes hovering over or trying to click on the new notification menu icon both with usb 1.1 and networking off as well as with usb 3 and networking on.  I crash back to text mode OS messages and then Mac OS recovers and takes you back to the login screen pretty quickly.
- graphics seems slower, but I could be imagining it
- Launchpad app really slow, mouse barely moves - something wrong there esp. inside launchpad/other
- Spotlight search doesn't find Applications e.g. searching for TextEdit or Terminal - possibly indexing is broken?
- Finder search within Applications folder doesn't work e.g. searching for TextEdit or Terminal
- Copy paste of files and folders sometimes really slow but then recovers, then gets worse again later.

**Comment by myspaghetti** [comment]
I get `AppleKeyStore` crashes whenever clicking on Control Center. Modifying the VM hardware points to the crash being related to disk access.

![uid-minus-1](https://user-images.githubusercontent.com/31696646/85840742-ad1bf980-b7a5-11ea-8a2a-915c4810121f.png)

![NVMe](https://user-images.githubusercontent.com/31696646/85840749-af7e5380-b7a5-11ea-9167-f664ce670de6.png)

**Comment by alienpenguin** [comment]
my applekeystore keeps crashing no matter what, i tried switching to usb 1.1 and no network to no avail.

**Comment by myspaghetti** [comment]
@alienpenguin during initial setup or after?

**Comment by alienpenguin** [comment]
I did not read your guide before installing, so after the install was completed and i was presented the login screen for the first time I noticed that i could not login. After googling about the applekeystore message i found your post about network and usb: i turned off vbox, changed the vm settings and restarted, but nothing changed, so i am stuck at login screen.

**Comment by myspaghetti** [comment]
The workaround only works for a clean install where there isn't an existing user account, doesn't work for upgrades.

**Comment by myspaghetti** [comment]
The workaround only works for a new install where there isn't an existing user account, doesn't work for upgrades.

**Comment by alienpenguin** [comment]
thanks @myspaghetti re-installing on a new disk it worked.

**Comment by Va1a** [comment]
not an issue or anything but myspaghetti i want to give you a fat wet kiss for this godlike tool you have made. <3 <3

**Comment by myspaghetti** [comment]
Please maintain social distancing.

**Comment by panthersdude2001** [comment]
I have finally got Big sur to work...
![big sur in windows - rare](https://user-images.githubusercontent.com/44646536/87689406-25972a00-c756-11ea-87ac-075dc48f7bb9.png)
until this happens...
![or not](https://user-images.githubusercontent.com/44646536/87689437-2fb92880-c756-11ea-8918-6d0ac0f3e752.png)
Grr! Stupid kernel panic has ravaged the os! 😬😬😬

**Comment by myspaghetti** [comment]
Big Sur works fine under QEMU so if you create a `vmdk` installation you can (with some manual configuration) pop it into QEMU.

**Comment by panthersdude2001** [comment]
Oh oK! BRYCE M From: JackSent: Thursday, July 16, 2020 12:53 PMTo: myspaghetti/macos-virtualboxCc: Computer Geek; CommentSubject: Re: [myspaghetti/macos-virtualbox] macOS 11.0 Big Sur (#254) Big Sur works fine under QEMU so if you create a vmdk installation you can (with some manual configuration) pop it into QEMU.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by panthersdude2001** [comment]
@myspaghetti what is the command to put into qemu? i booted and said no bootable device.

**Comment by panthersdude2001** [comment]
I have this code: qemu-system-x86_64.exe -L pc-bios -boot c -m 4096 ^
-hdd macos.vmdk ^
-hda macos_1.vmdk ^
-sdl ^
-netdev user,id=network01 -device rtl8139,netdev=network01 ^
-device VGA,edid=on 
but it's stuck on booting from hard disk..

**Comment by panthersdude2001** [comment]
@myspaghetti I get what you are saying about the vmdk. How do you exactly convert a pkg into a bootable vmdk so it will boot and install, within qemu for windows?

**Comment by panthersdude2001** [comment]
Sorry for bugging you. I will try this in about another hour or two.

**Comment by panthersdude2001** [comment]
> The script doesn't support Big Sur at the moment. There are no current plans for the script to support the current installer of Big Sur since it needs to be unpacked from a `pkg` file, and such unpacking software is not available by default on most systems' package managers. There are [macOS-host-only scripts](https://github.com/AlexanderWillner/runMacOSinVirtualBox) that unpack the `pkg` file automatically.
> 
> The USB and network settings are done through `VBoxManage` or the VirtualBox graphical interface. Currently, with Big Sur version `20A4299v` the system's secure keychain `AppleKeyStore` crashes occasionally when networking or USB 3.0 is enabled.
> 
> If you want to manually install Big Sur you can follow these steps:
> 
> 1. Install Catalina
> 2. [Download Big Sur `InstallAssistant.pkg`](http://swcdn.apple.com/content/downloads/15/52/001-18401-A_I5FFC1VB5J/rrfxkhkf3ykxzj3zjshu1srsh4n74a41n4/InstallAssistant.pkg) version `20.0.4299.22` (this link will be dead when a new version comes out) either inside the virtual machine or on the host on a disk image that will be mounted on the virtual machine. Windows can create and mount VHD disk images through Disk Management, which can then be unmounted and attached to the virtual machine.
> 3. Use VirtualBox to create an additional disk image that has at least 60GB of storage space. Attach it to the virtual machine and erase it with Disk Utility, formatting it to APFS.
> 4. Run `InstallAssistant.pkg` which creates the app "Install macOS Beta.app" in the `/Applications` folder
> 5. Run "Install macOS Beta.app", when prompted select "Show All Disks..." and select the new empty disk.
> **_6. Allow the installer to complete, it will automatically boot into macOS Big Sur. When the macOS initial setup starts, shut down macOS with Command-Q_**
> 7. Set the virtual machine's USB version to 1.1 and disable all network adapters from the VirtualBox settings (`AppleKeyStore`, the system's secure keychain, crashes otherwise)
> 8. Boot macOS Big Sur and complete the initial setup
> 9. After initial setup is complete the USB settings and network adapters can be restored, but this will make `AppleKeyStore` crash occasionally.
Bolded in your instructions on 6, how do you shut down an os, if it has the apple logo and says x minutes remaining?

**Comment by myspaghetti** [comment]
Sorry, no support is offered for QEMU. You get the `vmdk` by creating an empty `vmdk` and installing Big Sur onto it as described in the thread.

**Comment by myspaghetti** [comment]
Sorry, no support is offered for QEMU. You get the `vmdk` by creating an empty `vmdk` and installing Big Sur onto it as described in the thread. Don't interrupt the installer, the initial setup loads after the installer completes.

**Comment by panthersdude2001** [comment]
Ohhhh. Ok. Now I know how this works.
You just run the setup with catalina, then download the files for big sur, and then create the second hdd and install big sur. when that completes and gets to the language screen, do i just exit the vbox (big sur) or did i go past it?
Now one more question @myspaghetti , how do you get the two hard drives into qemu without saying, HDD1 already exists, when placing hdd0(catalina) and hdd1(bigsur) into the hdd slot?

**Comment by panthersdude2001** [comment]
And one more thing. Which is the vmdk, the catalina, or the big sur? Because when i boot into just one in vbox, it goes to the uefi shell.

**Comment by panthersdude2001** [comment]
Thanks so much @myspaghetti for clearing this confusion up significantly. You deserve (with social distancing practices) a big hug and a kiss! 😘😘😘

**Comment by myspaghetti** [comment]
You could just shut down VirtualBox and continue on QEMU, that seems reasonable. You could even go back a little and run Catalina on QEMU and upgrade to Big Sur or install it on an empty APFS-formatted virtual disk image. Main point is that the script is used to bootstrap a working macOS virtual machine. You could make a Catalina `vmdk` or a Big Sur `vmdk`, but if you're gonna use QEMU I'd suggest both, saves time not having to go back-and-forth between QEMU and VirtualBox.

I've mentioned this on other issues, I mainly use the script to create bootable macOS installers to use on Macs with a failing recovery environment. VirtualBox is slow and kinda painful, but it works everywhere and with little to no manual configuration, which is why the script is designed for VirtualBox and not QEMU, even though QEMU is better.

**Comment by panthersdude2001** [comment]
Ok thank you for the recomenndations.

**Comment by panthersdude2001** [comment]
Still stuck on
![still stuck on booting](https://user-images.githubusercontent.com/44646536/87825148-90269380-c844-11ea-8e18-c1d3e58c5ba5.png)

**Comment by myspaghetti** [comment]
From a bootable `BaseSystem.vdi`, the Terminal command `pkgutil --expand-full InstallAssistant.pkg /Volumes/path/to/new/folder` successfully extracts the file `SharedSupport.dmg` and the installer app, which means Big Sur installation be automated in the script.

**Comment by dfuentes03** [comment]
> The script doesn't support Big Sur at the moment. There are no current plans for the script to support the current installer of Big Sur since it needs to be unpacked from a `pkg` file, and such unpacking software is not available by default on most systems' package managers. There are [macOS-host-only scripts](https://github.com/AlexanderWillner/runMacOSinVirtualBox) that unpack the `pkg` file automatically.
> 
> The USB and network settings are done through `VBoxManage` or the VirtualBox graphical interface. Currently, with Big Sur version `20A4299v` the system's secure keychain `AppleKeyStore` crashes occasionally when networking or USB 3.0 is enabled.
> 
> If you want to manually install Big Sur you can follow these steps:
> 
> 1. Install Catalina
> 2. [Download Big Sur `InstallAssistant.pkg`](http://swcdn.apple.com/content/downloads/15/52/001-18401-A_I5FFC1VB5J/rrfxkhkf3ykxzj3zjshu1srsh4n74a41n4/InstallAssistant.pkg) version `20.0.4299.22` (this link will be dead when a new version comes out) either inside the virtual machine or on the host on a disk image that will be mounted on the virtual machine. Windows can create and mount VHD disk images through Disk Management, which can then be unmounted and attached to the virtual machine.
> 3. Use VirtualBox to create an additional disk image that has at least 60GB of storage space. Attach it to the virtual machine and erase it with Disk Utility, formatting it to APFS.
> 4. Run `InstallAssistant.pkg` which creates the app "Install macOS Beta.app" in the `/Applications` folder
> 5. Run "Install macOS Beta.app", when prompted select "Show All Disks..." and select the new empty disk.
> 6. Allow the installer to complete, it will automatically boot into macOS Big Sur. When the macOS initial setup starts, shut down macOS with Command-Q
> 7. Set the virtual machine's USB version to 1.1 and disable all network adapters from the VirtualBox settings (`AppleKeyStore`, the system's secure keychain, crashes otherwise)
> 8. Boot macOS Big Sur and complete the initial setup
> 9. After initial setup is complete the USB settings and network adapters can be restored, but this will make `AppleKeyStore` crash occasionally.

Do you happen to have the link to the most recent `InstallAssistant.pkg`? The link is indeed dead.

**Comment by myspaghetti** [comment]
You can get the latest beta download URL from the [software update catalog](https://swscan.apple.com/content/catalogs/others/index-10.16seed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog).
This is the latest URL: `http://swcdn.apple.com/content/downloads/46/56/001-34223-A_QIYG1DL7MO/igh8xp5qsam7ounuabziajlktg8nhoptis/InstallAssistant.pkg`
This link will break when a new version is released.

**Comment by alienpenguin** [comment]
@myspaghetti do you have any insights on upgrading? i tried upgrading to beta2 and now beta4 but i am stuck at login screen with the usual applekeystore crash. Except from re-installing on a new disk is there anything that can be done?

**Comment by myspaghetti** [comment]
I haven't tested Big Sur any further. I suspect solving the bug requires a conscious effort from the VirtualBox devs to debug it. Since Oracle can't legally provide cloud-hosted macOS virtual machines, I doubt debugging macOS guests is a priority. Then again they completely overhauled NVRAM, which improved macOS compatibility, so maybe another similar design overhaul will positively impact macOS guests.

**Comment by alienpenguin** [comment]
just an update: updating to beta 8 solves the applekeystore crash :D

**Comment by DX37** [comment]
In case y'all wanted fresh link to Big Sure - just use [gibMacOS](https://github.com/corpnewt/gibMacOS). Release type `developer` shows InstallAssistand.pkg download.

**Comment by shaqaruden** [comment]
> The script doesn't support Big Sur at the moment. There are no current plans for the script to support the current installer of Big Sur since it needs to be unpacked from a `pkg` file, and such unpacking software is not available by default on most systems' package managers. There are [macOS-host-only scripts](https://github.com/AlexanderWillner/runMacOSinVirtualBox) that unpack the `pkg` file automatically.
> 
> The USB and network settings are done through `VBoxManage` or the VirtualBox graphical interface. Currently, with Big Sur version `20A4299v` the system's secure keychain `AppleKeyStore` crashes occasionally when networking or USB 3.0 is enabled.
> 
> If you want to manually install Big Sur you can follow these steps:
> 
> 1. Install Catalina
> 2. [Download Big Sur `InstallAssistant.pkg`](http://swcdn.apple.com/content/downloads/15/52/001-18401-A_I5FFC1VB5J/rrfxkhkf3ykxzj3zjshu1srsh4n74a41n4/InstallAssistant.pkg) version `20.0.4299.22` (this link will be dead when a new version comes out) either inside the virtual machine or on the host on a disk image that will be mounted on the virtual machine. Windows can create and mount VHD disk images through Disk Management, which can then be unmounted and attached to the virtual machine.
> 3. Use VirtualBox to create an additional disk image that has at least 60GB of storage space. Attach it to the virtual machine and erase it with Disk Utility, formatting it to APFS.
> 4. Run `InstallAssistant.pkg` which creates the app "Install macOS Beta.app" in the `/Applications` folder
> 5. Run "Install macOS Beta.app", when prompted select "Show All Disks..." and select the new empty disk.
> 6. Allow the installer to complete, it will automatically boot into macOS Big Sur. When the macOS initial setup starts, shut down macOS with Command-Q
> 7. Set the virtual machine's USB version to 1.1 and disable all network adapters from the VirtualBox settings (`AppleKeyStore`, the system's secure keychain, crashes otherwise)
> 8. Boot macOS Big Sur and complete the initial setup
> 9. After initial setup is complete the USB settings and network adapters can be restored, but this will make `AppleKeyStore` crash occasionally.

If Big Sur is not fully support I would recommend switching your screenshot to Catalina or put these instructions in the readme. BTW If this script works for me, you will have been a life saver. I have been trying to get a macOS VM up and running for hours now and just came across this repo maybe 30 minutes ago.

**Comment by myspaghetti** [comment]
As of [beta 8](https://github.com/myspaghetti/macos-virtualbox/issues/254#issuecomment-696996906) the built-in macOS Software Update successfully upgrades Catalina to Big Sur, so you don't need to jump through all those hoops.

**Comment by myspaghetti** [comment]
I've hidden all the comments addressing the issues with earlier Big Sur betas to make it clear that beta 8 and later can be installed from macOS Software Update without issue.

**Comment by myspaghetti** [comment]
Closing as `won't fix`

The public release versions of Big Sur have been out for a while, and it doesn't look like it'll have the same installer distribution that Sierra, High Sierra, Mojave, and Catalina have. It's certainly possible to extract the installer from the `InstallAssistant.pkg` file but this requires a different implementation. It's easy on macOS, but for a cross-platform solution it requires `xar`, which is rarely available as a binary package from a package manager. It's not difficult to compile but I don't want to add all the compilation dependencies to the script.

**Comment by tuxpeople** [comment]
@myspaghetti Jack, sorry for commenting on so many closed issues. I don't want to annoy you.

I was thinking about the `xar` problem, can't get this off my mind. And it may be solvable, without having dependencies to sources.

- MacOS: use the built in `xar`
- Linux: use 7Zip, which can extract xar files. For Linux, there is [p7zip](https://sourceforge.net/projects/p7zip/) which should be enough (cli-only version)
- Cygwin: I have no idea. Either also p7zip if it's working there, or portable Version of normal 7Zip for Windows which also includes a CLI interface

What do you think? I agree with the argument it's easy to upgrade to Big Sur manually. But more OSX versions are coming and maybe there will be a point where upgrading from Catalina is not suitable or doable anymore.

**Comment by myspaghetti** [comment]
>sorry for commenting on so many closed issues

So far all of your comments have been helpful, so no apologies necessary!

I'll look into p7zip, it does seem to be commonly available as a binary package.

>there will be a point where upgrading from Catalina is not suitable or doable anymore

Big Sur is probably the last x86 macOS, I expect that in a couple of years this script will be at best a curiosity like a Windows 95 installer.

**Comment by myspaghetti** [comment]
`p7zip` does not recognize the archived directory structure and only extracts a single file from the payload in `InstallAssistant.pkg`, so we're back to either finding a trusted binary package for `xar` or compiling it from source, which isn't difficult but adds a lot of dependencies.

**Comment by myspaghetti** [comment]
For reference, [here are instructions for compiling `xar`](https://github.com/cylance/macos-arm64-emulation). If anyone wants to maintain a binary package and push it to Ubuntu, Debian, centOS, and other major distros, that'll help people around the world recover their Mac devices if their recovery partition fails to install macOS.

**Comment by rhoehener** [comment]
How about first creating a temporary Catalina VM just to access the tooling required to extract the Big Sur installer from the pkg file? It would double the install time, and make the script more complex, but remain cross platform and fully automated.

**Comment by myspaghetti** [comment]
>How about first creating a temporary Catalina VM just to access the tooling required to extract the Big Sur installer from the pkg file?

That would work.

It could recognize whether it's on the first-boot setup process or already logged in with `tesseract` and perform accordingly. I'll reference your suggestion in issue #476 which combines this issue for macOS 11 Big Sur and 12 Monterey.
