### ISSUE TITLE
Stuck on Downloading Downloading Apple macOS HighSierra software update catalog WSL

### ISSUE THREAD

**Issue by SamHep0803** [myspaghetti/macos-virtualbox#256]
So I've had the script running for well over 22 hours now and it still for some reason hasn't got passed `Downloading Apple macOS HighSierra software update catalog`.

I've tried it with both Catalina and High Sierra so i'm trying to figure out why it's happening. At first I thought it was just because it was a large file but after leaving it for this long, I'm pretty sure that's not the case.

Is there something I'm doing wrong? 

Thanks, Sam.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

The Apple software update catalog is about 7MB, it should usually take a few seconds to download. Would you mind attaching or pasting the output of the following command:
```
wget --debug 'https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog'
```

**Comment by SamHep0803** [comment]
```
DEBUG output created by Wget 1.20.1 on linux-gnu.

Reading HSTS entries from /home/samuel/.wget-hsts
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/samuel/.wget-hsts'. HSTS will be disabled.
URI encoding = ‘UTF-8’
Converted file name 'index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog' (UTF-8) -> 'index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog' (UTF-8)
--2020-07-01 21:04:01--  https://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Certificates loaded: 126
Resolving swscan.apple.com (swscan.apple.com)... 23.213.140.68, 2001:41a8:45:297::1759, 2001:41a8:45:2b2::1759
Caching swscan.apple.com => 23.213.140.68 2001:41a8:45:297::1759 2001:41a8:45:2b2::1759
Connecting to swscan.apple.com (swscan.apple.com)|23.213.140.68|:443... connected.
Created socket 3.
Releasing 0x00007fffed93a6e0 (new refcount 1).
```

**Comment by myspaghetti** [comment]
Looks like something's wrong with the DNS lookup, flush your device's or router's DNS cache.

**Comment by myspaghetti** [comment]
Added timeout to `wget` in [version 0.93.8](https://github.com/myspaghetti/macos-virtualbox/commit/899c27905f2f008272ef00553add6ff6b898e46a)

**Comment by SamHep0803** [comment]
@myspaghetti I have flushed my DNS cache on my pc and completely changed routers yet it is still bugged

I might try reinstalling wget

**Comment by SamHep0803** [comment]
I have reinstalled wget to no result. I am stumped

**Comment by SamHep0803** [comment]
```
DEBUG output created by Wget 1.20.1 on linux-gnu.

Reading HSTS entries from /home/samuel/.wget-hsts
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/samuel/.wget-hsts'. HSTS will be disabled.
URI encoding = ‘UTF-8’
--2020-07-01 21:44:19--  https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Certificates loaded: 126
Resolving swscan.apple.com (swscan.apple.com)... 23.213.140.68, 2001:41a8:45:2b2::1759, 2001:41a8:45:297::1759
Caching swscan.apple.com => 23.213.140.68 2001:41a8:45:2b2::1759 2001:41a8:45:297::1759
Connecting to swscan.apple.com (swscan.apple.com)|23.213.140.68|:443... connected.
Created socket 5.
Releasing 0x00007fffe731fba0 (new refcount 1).
Closed fd 5
Unable to establish SSL connection.
```
Here's the Catalina_wget.log from after updating the script

**Comment by myspaghetti** [comment]
Very unlikely that this is a `wget` issue, the IP address `23.213.140.68` does not belong to Apple. Check your network settings, your device's `hosts` file, and other devices that sit between it and the internet. One of them is misdirecting traffic. Try downloading the URL from your browser, you will likely get the same result.

**Comment by SamHep0803** [comment]
Very weird, I went to the website in my browser and it has an apple logo and everything.

![image](https://user-images.githubusercontent.com/14109339/86275846-f7a5d780-bbe4-11ea-8e06-038184bde2fc.png)

**Comment by myspaghetti** [comment]
Hmm, my mistake, it _is_ an Apple server. I might look into this later, but in general this is not a script issue so I'm not sure how much I can troubleshoot it.

**Comment by SamHep0803** [comment]
Ok, well do you have any other platform I can talk to you about this as I would like to get this fixed?

**Comment by myspaghetti** [comment]
Sorry, no, I don't offer general tech support.

**Comment by SamHep0803** [comment]
Ah ok. Well thanks for your help. I guess I will need to find another way to make a mac VM

**Comment by myspaghetti** [comment]
I googled `wget fd 5` and it seems that some old versions of `wget` don't support some secure protocols. Could you post the output of `wget --version`?

**Comment by SamHep0803** [comment]
`GNU Wget 1.20.1 built on linux-gnu.`

**Comment by myspaghetti** [comment]
Oh that's brand new... Can you download the `sucatalog` url with `curl` or your browser?

**Comment by SamHep0803** [comment]
one sec

**Comment by SamHep0803** [comment]
`curl: (60) SSL certificate problem: unable to get local issuer certificate`

**Comment by myspaghetti** [comment]
Try updating your certificates, usually `ca-certificates` on your package manager.

**Comment by SamHep0803** [comment]
Ok i'm hoping that works, cURL now seems to like it so we will see

**Comment by SamHep0803** [comment]
Still nothing :/ though the ip has appeared to change to `104.84.156.59`

**Comment by myspaghetti** [comment]
Check if your `wgetrc` file [points to the right certificate directory](https://serverfault.com/questions/896082/fixing-wget-certificates).

**Comment by SamHep0803** [comment]
It's kind of late here now, do you mind if we continue this tomorrow?

**Comment by myspaghetti** [comment]
Uh, sure, as long as this issue is unlocked you can post here...

**Comment by SamHep0803** [comment]
Ok so wgetrc is set correctly but still not working :/

**Comment by myspaghetti** [comment]
Make sure your `wget` supports SSL. Run `wget --version` and see if there's `+https` and `+ssl/gnutls` in the output. See if your package manager has a version of `wget` with these protocols.

**Comment by SamHep0803** [comment]
yep :/ `-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls
+ntlm +opie +psl +ssl/gnutls`

**Comment by myspaghetti** [comment]
Try reinstalling `crypto-policies`

Otherwise, you can modify the script to use any other downloader (`curl` would do)

**Comment by SamHep0803** [comment]
` crypto-policies` doesn't seem to be a package in debian. I'll try
modifying the script

**Comment by myspaghetti** [comment]
[Here's a version of the script that uses `curl`.](https://github.com/myspaghetti/macos-virtualbox/files/4863807/macos-guest-virtualbox-curl.sh.txt)

I still recommend trying to fix `wget`, there is some configuration that's preventing it from using the required protocols.

**Comment by SamHep0803** [comment]
Thanks very much!

**Comment by SamHep0803** [comment]
I'm trying to use the curl version on the script, but for some reason I get the error:
```
Please make sure the following packages are installed:
coreutils    gzip    unzip    xxd    curl
Please make sure the coreutils and gzip packages are the GNU variant
```
even though every thing is updated

**Comment by myspaghetti** [comment]
There's a typo on line 194, `Csplit` (capital `C`) should be `csplit` (lowercase `c`)

I tested the script on a case-insensitive file system...

**Comment by SamHep0803** [comment]
thanks! i may have ruined an install of debian wsl because of that though haha. i tried to reinstall those core packages and it seriously messed something up. anyways i'll try it on my ubuntu wsl install tomorrow

**Comment by SamHep0803** [comment]
@myspaghetti the script works! thanks very much for your help :)

**Comment by DavidLuong98** [comment]
@SamHep0803 What did you exactly do to fix this issue if you remember? Running into the same issue and the typo is no longer within the script

**Comment by SamHep0803** [comment]
You can try running it in Ubuntu 18.04 WSL as I think there are some issues with SSL in newer versions

**Comment by DavidLuong98** [comment]
@SamHep0803 Currently running on Ubuntu 18.04 and getting this,the same as you previously : 
```
Please make sure the following packages are installed
and that they are of the version specified or newer:

    coreutils 8.22   wget 1.14   gzip 1.5   unzip 6.0

Please make sure the coreutils and gzip packages are the GNU variant.

**Comment by SamHep0803** [comment]
Then sorry I can't help, I don't use this script anymore and even if I did I don't think the same fix I used works. I suggest you create a new issue. Sorry 😅
