### ISSUE TITLE
Unable to install in WSL2

### ISSUE THREAD

**Issue by cameronbroe** [myspaghetti/macos-virtualbox#258]
When trying to use the script with default arguments, I get this message:

```
Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
```

The README mentions that the Windows Subsystem for Linux should work. Is it only supposed to work in WSL1 and not WSL2? I have VirtualBox 6.1.10 installed.

**Comment by myspaghetti** [comment]
Yes, WSL2 blocks VirtualBox from using hardware-supported virtualization, better known as VT-x and AMD-V. Oracle has discussed this issue with Microsoft and Microsoft does not plan to change this behavior. You can convert your WSL2 distro to WSL1 and vice-versa, or you can use Cygwin, or you can [use some fancy CPU configuration to use nested virtualization inside WSL2](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/) and run VirtualBox with VT-x inside WSL2, which is pretty cool but complicated.

**Comment by cameronbroe** [comment]
Cool. Thanks for the quick answer. Yeah, I know Hyper-V takes exclusive control over VT-x. VirtualBox does have support for running VMs through Hyper-V though, with a performance hit. Is that something that could be used? Also, would you be opposed to a PR adding a note in the documentation specifying support for WSL1, but not WSL2?

**Comment by myspaghetti** [comment]
>VirtualBox does have support for running VMs through Hyper-V

True but the macOS installer fails when it is used.

Added the error message to the readme and documentation.

**Comment by pwr22** [comment]
Huh, this is a pain. Is there a technical reason why Windows blocks VirtualBox from enabling VT-x? I'm assuming they've made virtualbox work by changing it to use hyper-v as a backend?

**Comment by pwr22** [comment]
And another question, could I make the VM on a machine without Hyper-V, go through the installer, and then import and use it on a machine without VT-x?

**Comment by myspaghetti** [comment]
@pwr22 regarding the first question: Microsoft is "[working closely](https://github.com/microsoft/WSL/issues/5030#issuecomment-638409782)" with third-party VM vendors about the issue.

Regarding the second question, macOS crashes on VirtualBox with NEM. However, [you can run macOS on QEMU on WSL2.](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/)

**Comment by CSmith1998** [comment]
`
Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.
`
I still get this error. I do not have access to Hyper-V, I've disabled the HyperVisor Platform, I WSL2 isn't available in my features, nor is Windows Sandbox, memory integrity IS off... What else could it be?
