### ISSUE TITLE
od: unrecognized option '--endian=little'

### ISSUE THREAD

**Issue by pciavald** [myspaghetti/macos-virtualbox#261]
Hi, 

I'm running CentOS 7 where bash 4.3+ is not available, so i compiled it from source.

The script seems to work correctly except for this part:

```
stage: create_nvram_files
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=big'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=big'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=big'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=little'
Try 'od --help' for more information.
od: unrecognized option '--endian=big'
Try 'od --help' for more information.
```

Then it goes up to:
```
stage: populate_virtual_disks
Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles.

Until the script completes, please do not manually interact with
the virtual machine.

Press enter when the Language window is ready.

Press enter when the macOS Utilities window is ready.

Press enter when the Terminal command prompt is ready.

Please wait
Partitioning the target virtual disk and the installer virtual disk.
Loading base system onto the installer virtual disk. Moving installation
files to installer virtual disk, updating InstallInfo.plist, and rebooting the
virtual machine.

The virtual machine may report that disk space is critically low; this is fine.

When the installer virtual disk is finished being populated, the script will
shut down the virtual machine. After shutdown, the initial base system will be
detached from the VM and released from VirtualBox.

If the partitioning fails, exit the script by pressing CTRL-C
Otherwise, please wait.
^C
```

I had to ^C at this point because the formatting failed. I'm guessing it's because of the wrong endianness so i'll research what can be done to fix it. Will keep updated.

```
$ od --version
od (GNU coreutils) 8.22
```

**Comment by pciavald** [comment]
So [it seems](https://patchew.org/QEMU/20200226125424.481840-1-eblake@redhat.com/) that `--endian` was added in `coreutils 8.23`, also installing `coreutils 8.30` from Centos 8 package does not work - it will conflict with several other core components of the system. Would there be another tool to replace `od`'s job ?

**Comment by myspaghetti** [comment]
Thanks for the bug report! Technically you don't need the NVRAM parameters at all to run macOS, you can skip the entire `create_nvram_files` stage. Flipping the endianness can be done manually, I might implement that as a workaround if it doesn't make the code too obtuse.

**Comment by pciavald** [comment]
Maybe just check if coreutils >= 8.23 and tell the user that the script is disabling NVRAM if not, enter to continue ?

Can the VM be built on any machine and transferred to the host ? 

Would you be interested in a docker image to run this script ? I've made a virtualbox docker image recently.

**Comment by myspaghetti** [comment]
Implemented check.

The VM can be transferred either by copying the `.vdi` `.vbox` and `.nvram` files and registering the `.vbox` file with VirtualBox, or, less conveniently, by exporting the virtual machine, which packs all the files into one `.ovf` file.

Docker would make the script less portable. Outside of very old distros like centOS 7, it's easier to run the script natively since the dependencies are very common.

We'll see how ugly replacing `od` is...

**Comment by myspaghetti** [comment]
Replaced `od` with `xxd` in [version `0.94.21](https://github.com/myspaghetti/macos-virtualbox/commit/6a9d1a22bd1a84725aa34e301ffbe9b83768fa6b). This slows down the script by a couple of seconds and slightly improves readability in one line.

**Comment by myspaghetti** [comment]
Replaced `od` with `xxd` in [version `0.94.21`](https://github.com/myspaghetti/macos-virtualbox/commit/6a9d1a22bd1a84725aa34e301ffbe9b83768fa6b). This slows down the script by a couple of seconds and slightly improves readability in one line.

**Comment by pciavald** [comment]
Thanks ! 

I'm trying the new version and get this message:

```
stage: create_nvram_files
Usage:
       xxd [options] [infile [outfile]]
    or
       xxd -r [-s [-]offset] [-c cols] [-ps] [infile [outfile]]
Options:
    -a          toggle autoskip: A single '*' replaces nul-lines. Default off.
    -b          binary digit dump (incompatible with -ps,-i,-r). Default hex.
    -c cols     format <cols> octets per line. Default 16 (-i: 12, -ps: 30).
    -E          show characters in EBCDIC. Default ASCII.
    -g          number of octets per group in normal output. Default 2.
    -h          print this summary.
    -i          output in C include file style.
    -l len      stop after <len> octets.
    -ps         output in postscript plain hexdump style.
    -r          reverse operation: convert (or patch) hexdump into binary.
    -r -s off   revert with <off> added to file positions found in hexdump.
    -s [+][-]seek  start at <seek> bytes abs. (or +: rel.) infile offset.
    -u          use upper case hex letters.
    -v          show version: "xxd V1.10 27oct98 by Juergen Weigert".
```

So I guess xxd has the same issue than od in terms of changed api. I've created the vm on another machine to transfer it to the host :)

**Comment by myspaghetti** [comment]
That's weird, I am using the same version of `xxd`:
```
xxd -h
Usage:
       xxd [options] [infile [outfile]]
    or
       xxd -r [-s [-]offset] [-c cols] [-ps] [infile [outfile]]
Options:
    -a          toggle autoskip: A single '*' replaces nul-lines. Default off.
    -b          binary digit dump (incompatible with -ps,-i,-r). Default hex.
    -C          capitalize variable names in C include file style (-i).
    -c cols     format <cols> octets per line. Default 16 (-i: 12, -ps: 30).
    -E          show characters in EBCDIC. Default ASCII.
    -e          little-endian dump (incompatible with -ps,-i,-r).
    -g          number of octets per group in normal output. Default 2 (-e: 4).
    -h          print this summary.
    -i          output in C include file style.
    -l len      stop after <len> octets.
    -o off      add <off> to the displayed file position.
    -ps         output in postscript plain hexdump style.
    -r          reverse operation: convert (or patch) hexdump into binary.
    -r -s off   revert with <off> added to file positions found in hexdump.
    -s [+][-]seek  start at <seek> bytes abs. (or +: rel.) infile offset.
    -u          use upper case hex letters.
    -v          show version: "xxd V1.10 27oct98 by Juergen Weigert".
```

**Comment by myspaghetti** [comment]
centOS 7 `xxd` reports version `V1.10` but does not have the same features as other `V1.10` `xxd` binaries...

**Comment by myspaghetti** [comment]
The plot thickens...
```
VERSION
       This manual page documents xxd version 1.7
```
It appears centOS `xxd` is misreporting its version number.

**Comment by myspaghetti** [comment]
centOS 7 definitely has an `xxd` version that misreports its version number. Thanks for raising this issue, it appears the script actually requires `xxd` version `1.10`

A true `xxd` version `1.10` can be installed on centOS 7 from the Ghettoforge Plus repository:
```
yum localinstall vim-enhanced-8.0.003-1.gf.el7.x86_64.rpm vim-common-8.0.003-1.gf.el7.x86_64.rpm vim-minimal-8.0.003-1.gf.el7.x86_64.rpm
```

**Comment by myspaghetti** [comment]
Mystery solved: https://github.com/ConorOG/xxd/commit/caa48bf6ad4a33cb22aa17bd395ea7eba0361c89

A whole bunch of patched `xxd` versions do not report that they're `V1.11`.

This is noted in script version [`0.94.3`](https://github.com/myspaghetti/macos-virtualbox/commit/a50857fa04af6cc32278f593c96ed83620428f97)
