### ISSUE TITLE
Catalina installation failing at > startosinstall: an extraneous parameter was specified with option 'pidtosignal'

### ISSUE THREAD

**Issue by not4mj** [myspaghetti/macos-virtualbox#262]
Trying to install Mac OS Catalina from Ubuntu 20.0 -
Issue- 
Installation failed at command -
 `./startosinstall --agreetolicense --pidtosignal ${background_pid} --rebootdelay 500 --volume "/Volumes/'"${vm_name} `

Error Message:
`startosinstall: an extraneous parameter was specified with option 'pidtosignal'`

Solution-
Swapping the parameter `pidtosignal` with `rebootdelay` fixed it-
`./startosinstall --agreetolicense  --rebootdelay 500 --pidtosignal ${background_pid} --volume "/Volumes/'"${vm_name}`

**Comment by myspaghetti** [comment]
Hi, please attach the file `macOS_troubleshoot.txt` that is generated when executing `./macos-guest-virtualbox.sh troubleshoot`

**Comment by not4mj** [comment]
![VirtualBox_macOS_09_07_2020_20_56_04](https://user-images.githubusercontent.com/1065714/87118418-f8033a00-c298-11ea-8039-4ba93e4ceb84.png)


[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4901052/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
@not4mj thanks, the screenshot shows the problem! Something is wrong with the variable expansion of `${background_pid}`, for example if `${background_pid}` is `500` then the Terminal titlebar should show `500` and not `{background_pid}`

The `$` character is showing in the command but missing from the executed command showing in the titlebar. I'll try to reproduce the issue.

**Comment by myspaghetti** [comment]
@not4mj thanks, the screenshot shows the problem! When you ran the command the second time, `${background_pid}` was typed without `$`

[Script version 0.94.4](https://github.com/myspaghetti/macos-virtualbox/commit/e6e9786c6a714cb79c2f44795fb65633639609fe) has a sanity check that aborts if `${background_pid}` does not look like a process ID.

Here's how the Terminal titlebar should look, with `--pidtosignal ` followed by three digits:
![p](https://user-images.githubusercontent.com/31696646/87127861-57604a80-c297-11ea-9e67-936c26d10fdc.png)
