### ISSUE TITLE
Loop of Installation

### ISSUE THREAD

**Issue by RoyiAvital** [myspaghetti/macos-virtualbox#266]
The sequence:

1. The script installed the system.
2. The system restarted to start macOS High Sierra.
3. The loading of the system got stuck (Hard reset).
4. I rerun the machine form VirtualBox, it again started the installer and not the OS itself.
5. I reinstalled. The system restarted to start the OS. It got stuck.
6. Back to (3).

I tried both:

```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```

What info can I bring to the table to try solve this?

By the way, amazing project!

**Comment by myspaghetti** [comment]
I don't understand the loop you're describing. The script has no loops, and if macOS installed successfully you need to detach the installer as instructed by the script so VirtualBox boots from the target disk and not from the installer.

**Comment by myspaghetti** [comment]
If macOS installed successfully you need to detach the installer as instructed by the script so VirtualBox boots from the target disk and not from the installer.

If I understand you correctly, the installer boots but the target system doesn't?

**Comment by RoyiAvital** [comment]
I did. It didn't work. I tried Mojave and suddenly it worked.

Maybe some compatibility with the latest VirtualBox and High Sierra?
I have Core i7 6800K.

**Comment by myspaghetti** [comment]
The CPU requirements for High Sierra and Mojave are identical, what you're describing sounds like a failed installation but you're too vague about it.

**Comment by RoyiAvital** [comment]
What info can I add to make it less vague? I'd be happy to assist.

**Comment by myspaghetti** [comment]
If `HighSierra_bootable_installer.vdi` is detached, the VM cannot boot from it. If I understand you correctly, you're saying `HighSierra_bootable_installer.vdi` was detached from the VM but the VM still booted from it?

**Comment by RoyiAvital** [comment]
It might be it. I knew I should do it but I might did not. But still had hard reset (Of the host computer) which I didn't have with Mojave.

Anyhow, Mojave works and I can't thank you enough for this. Amazing work!
