### ISSUE TITLE
how to get GNU variant coreutils and gzip

### ISSUE THREAD

**Issue by darvyong** [myspaghetti/macos-virtualbox#268]
Hi, I'm trying to use your install script on my win 10 home running on ryzen 2600. I tried using both cygwin and wsl 1 to run the script, but I keep running into this problem:

![Screenshot_2](https://user-images.githubusercontent.com/31510085/87858868-8e072680-c963-11ea-816b-a4a186bd2895.png)

as you can see, I've checked the versions of the packages installed on my WSL, and they're all higher than the required versions. I don't know how to resolve the "GNU variant" problem, and I haven't found any help from the internet and on here (not sure if i missed something).

please help! thank you.

**Comment by myspaghetti** [comment]
`unzip` is not installed
