### ISSUE TITLE
populate_macos_target_disk stage hangs - invalid signal specification

### ISSUE THREAD

**Issue by JimMikola** [myspaghetti/macos-virtualbox#271]
When this final stage of the script executes, the VM boots for the second time and progresses through to the bash terminals to execute nvram.sh, and a second bash terminal which runs startofinstall.sh.  The startofinstall.sh progresses through to 100% successfully and then emits a signal to the background PID.  Unfortunately the background PID (the first bash terminal) responds with:

`nvram.sh:  line 8: kill: SIGUSR1: invalid signal specification`

When I attempt to run the subsequent lines of nvram.sh by hand, I observe the following:

`disks="$(diskutil list | grep -o "[0-9][^ ]* GB *disk[0-9]$"`
`disks=(${disks[@]})`
(at this point 'disks' echos as 'disk1')

`mkdir -p "/Volumes/CatalinaOS/tmp/mount_efi"`
`mount_msdos /dev/${disks[0]}s1 "/Volumes/CatalinaOS/tmp/mount_efi"`
(bash terminal responds with:  mount_msdos: /dev/disk1s1: Resource busy)

`cp -r "/Volumes/Catal-files/ESP/"* "/Volumes/CatalinaOS/tmp/mount_efi/"`
(the copy seems to execute ok as verified by 'ls' in both source and destination folders)

Now I'm stuck so I just enter a reboot command in the first bash shell.  The system reboots back into the same language selection and then macOS Utilities.

Additional Information:  I'm using Virtual Box 6.1.12

**TRY #2**:  After rebooting into the same recovery image, I reran the .sh files again, this time by hand.  The mount_msdos command did not result in a resource busy.  When I executed the subsequent kill command on the installer_pid, the second bash shell (running startofinstall.sh) detected the signal and kicked off a reboot.  This reboot lands properly into the remainder of the installation.

The original issue is still present (SIGUSR1: invalid signal specification).  This prevents the remainder of nvram.sh from executing.

**Comment by myspaghetti** [comment]
OOOOH my mistake! Introduced this bug in version `0.96.0`!

**Comment by myspaghetti** [comment]
Fixed in [version `0.96.2`](https://github.com/myspaghetti/macos-virtualbox/commit/825a581033bc4683d6f2f53a57c0dff1eb2b2263)
