### ISSUE TITLE
How install on windows

### ISSUE THREAD

**Issue by harpreet9629** [myspaghetti/macos-virtualbox#272]
How i can use and install it on windows virtualbox?

**Comment by myspaghetti** [comment]
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (with or without Extension Pack)
2. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`  `bash` `gzip`  `unzip`  `wget` and `xxd`
3. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
4. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash ./macos-guest-virtualbox.sh`)

**Comment by harpreet9629** [comment]
Hi thank you i got installed genuine mac os on virtual box, can you please do 1 favor for me? How i can resize its resolution size after install?

**Comment by myspaghetti** [comment]
See documentation.

**Comment by harpreet9629** [comment]
I tried commands but not working

**Comment by myspaghetti** [comment]
Please post the command you entered.

**Comment by harpreet9629** [comment]
its solved when i restart pc. Thank You

**Comment by harpreet9629** [comment]
When i connect my iphone to virtual machine i am getting error, i am connecting because test ios apps on device. can you help me

Could not insert the C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditionas.iso disk image file into the virtual machine macOS. as the has no optical drives. Please add a drive using the storage page of the virtual machine settings window.

**Comment by myspaghetti** [comment]
Sorry, no support is offered for VirtualBox. I recommend you use QEMU with KVM for proper USB support and better virtualization in general. No support is offered for QEMU/KVM configuration.

**Comment by harpreet9629** [comment]
Hi, its working very smoothly but i have 1 more issue, my macOS disk size is 80gb and it show 53gb free but still when i download something it say no space is macOS disk

**Comment by harpreet9629** [comment]
never mind it fixed, i repaired disk

**Comment by johnfrades** [comment]
![image](https://user-images.githubusercontent.com/20201069/199449357-13820c91-b1e4-4df3-81bf-f8413f4e3443.png)

 i tried running this command in Cygwin but it gives me this error

**Comment by myspaghetti** [comment]
@johnfrades see for example issue #28 

Cygwin uses Unix line endings, git needs to be configured to use Unix line endings instead of Windows. The easiest solution is [downloading the script directly](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh).
