### ISSUE TITLE
Can't login with Apple ID

### ISSUE THREAD

**Issue by richardk2016** [myspaghetti/macos-virtualbox#273]
Installation works fine without issues. Great job!! Thank you.

But after installing Catalina I can't login with an Apple ID.

When I use an existing Apple ID I get the error “This Apple ID is valid but is not an iCloud account”. This is a mistake. Because with this ID I can successfully login to icloud.com and appleid.apple.com anywhere and even on the newly created Mac with Safari.

When I try to create a new Apple ID, I get the error "Could not create Apple ID. This Mac has been used to create too many new Apple IDs"

What do I have to do?

**Comment by richardk2016** [comment]
Solved it by myself by using this Apple ID on an iPhone before trying to to login on the V-Mac. After login successfully on that iPhone I afterwards was able to login on the V-Mac.

**Comment by myspaghetti** [comment]
In case anybody reading this is wondering, when creating an Apple ID or logging in with an inactive Apple ID, [Apple checks more parameters](https://github.com/myspaghetti/macos-virtualbox/issues/76#issuecomment-520000788) than the ones supplied by the script, possibly through the SMC and other components that are not emulated by VirtualBox. For complete Mac emulation, a bootloader like OpenCore is required.

**Comment by acme-im** [comment]
Right, I can't create a new AppleID on the installed VM, it says: "This mac has been used to create too many new Apple IDs...
