### ISSUE TITLE
Virtualbox is not using hardware-supported virtualization features. Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other Windows features that lock virtualization are turned off. Exiting.

### ISSUE THREAD

**Issue by snaildos** [myspaghetti/macos-virtualbox#277]
Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.

I have none of these.

**Comment by myspaghetti** [comment]
Please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `macOS_troubleshoot.txt` file here.

**Comment by snaildos** [comment]
https://paste.ubuntu.com/p/H69JxTNjfY/

**Comment by myspaghetti** [comment]
You're running the script on WSL2.

**Comment by snaildos** [comment]
OH MY! IM SO SORRY IT MUST OF AUTO UPDATED! what a piece of crap,
Just a question, can i have docker running while I have WSL?

**Comment by myspaghetti** [comment]
Yes, but [the process is complicated](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/) and no support is offered for topics outside the scope of the script.

**Comment by arifikhsan** [comment]
how do u solve this?
