### ISSUE TITLE
Cannot boot into macOS or run Reinstall macOS

### ISSUE THREAD

**Issue by unxpctederr** [myspaghetti/macos-virtualbox#278]
Forgive me if this is not the correct way to use it, but after the install script finished, and the VM was started it booted to the recovery menu. I then selected the Startup Disk option from the apple menu at the top left and select macOS Base System, macOS, 10.15.6 and then pressed restart. This then restarts the VM but it boots straight into the recovery window again. 

I then am trying to use the 'Reinstall macOS' button to install macOS. This then gives an error message
> This copy of the Install macOS Catalina application is damaged, and can't be used to install macOS. 

I'm guessing this is normal, as obviously there are some tricks done in the install, but I cannot find any other way to actually boot into macOS and not just the recovery screen. Attached is the .txt file result of the troubleshooting script. 

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/4982288/macOS_troubleshoot.txt)

(Awesome script btw though!)

**Comment by myspaghetti** [comment]
Thanks.

The last stage of the script involves Terminal running `startosinstall` and then it reboots the VM into the macOS initial setup. The script doesn't check that `startosinstall` completes successfully. The first boot takes several minutes to an hour while macOS populates itself, then macOS boots regularly.

If the VM boots into the rescue environment after `startosinstall`, the installation might have failed. The script doesn't check that the installation is successful and I don't really have any way to check that `startosinstall` was successful so the easiest thing would be to try to populate the target disk again:
```
./macos-guest-virtualbox.sh create_target_virtual_disk populate_macos_target_disk
```

**Comment by myspaghetti** [comment]
Thanks.

The last stage of the script involves Terminal running `startosinstall` and then it reboots the VM into the macOS initial setup. The script doesn't check that `startosinstall` completes successfully. The first boot takes several minutes to an hour while macOS populates itself, then macOS boots regularly.

If the VM boots into the rescue environment after `startosinstall`, the installation might have failed. The script doesn't check that the installation is successful and I don't really have any way to check that `startosinstall` was successful so the easiest thing would be to try to populate the target disk again:
```
./macos-guest-virtualbox.sh create_installer_virtual_disk create_target_virtual_disk populate_virtual_disks populate_macos_target_disk
```

**Comment by unxpctederr** [comment]
Thanks for the quick reply! I just ran the script again, and it seems to have booted successfully (it is currently showing the apple logo and 'About 9 minutes remaining' which I'm assuming means it has booted properly and is doing first time setup. I'll see what happens after this is completed.

**Comment by unxpctederr** [comment]
Can confirm that re-running the script fixed the issue and is working well now 💯. Thank you for your assistance.
