### ISSUE TITLE
USB passthrough not working

### ISSUE THREAD

**Issue by sharmaraju352** [myspaghetti/macos-virtualbox#280]
I am using ubuntu 20.04.
I have installed virtualbox 6.1 with extension pack (I am able to see USB 3.0 controller).
I have added my user to vboxusers group.
Restarted my laptop several times, but I don't see USB passthrough to be working.

I tried connecting both  android as well as iphone. They are getting picked by host immediately, but I don't see them in virtualbox.
I tried unmounting devices from host as well.

Nothing seems to be working.

Am I missing something?

**Comment by sharmaraju352** [comment]
After one more restart started working.
Don't know why.

**Comment by g33kyshivam** [comment]
Hey, is the USB still working after the reboot?  @sharmaraju352
