### ISSUE TITLE
Successful installation, but fails to boot

### ISSUE THREAD

**Issue by dac09** [myspaghetti/macos-virtualbox#281]
Hi, thank you so much for building this. The installation process was amazing.

I seem to be having an issue booting up though:
![image](https://user-images.githubusercontent.com/1521877/88700475-a82dcb00-d100-11ea-8796-adb2252e8b9c.png)

Any tips on how to fix this?

---

**Details**
- Default settings on script,   macOS release: Mojave
- Host OS: OSX 10.15.6 (Catalina)
- Virtualbox Version 6.1.12 r139181 (Qt5.6.3)

**Comment by myspaghetti** [comment]
You can boot macOS manually by entering `fs0:\System\Library\CoreServices\boot.efi` in the EFI Internal Shell *but* I would like you to post `startup.nsh` here so I can troubleshoot the issue.

If you don't mind, please rename `macOS_startup.nsh` to `macOS_startup.nsh.txt` (or whatever you like with a `.txt` suffix) and attach it here.

The correct `startup.nsh` is supposed to look like this:
```
echo -off
if exist "fs0:\EFI\NVRAM\MLB.bin" then
  dmpstore -all -l fs0:\EFI\NVRAM\MLB.bin
  dmpstore -all -l fs0:\EFI\NVRAM\ROM.bin
  dmpstore -all -l fs0:\EFI\NVRAM\csr-active-config.bin
  dmpstore -all -l fs0:\EFI\NVRAM\system-id.bin
endif
for %a run (1 5)
  if exist "fs%a:\EFI\NVRAM\MLB.bin" then
    dmpstore -all -l fs%a:\EFI\NVRAM\MLB.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\ROM.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\csr-active-config.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\system-id.bin
  endif
endfor
for %a run (1 5)
  if exist "fs%a:\macOS Install Data\Locked Files\Boot Files\boot.efi" then
    "fs%a:\macOS Install Data\Locked Files\Boot Files\boot.efi"
  endif
endfor
for %a run (1 5)
  if exist "fs%a:\System\Library\CoreServices\boot.efi" then
    "fs%a:\System\Library\CoreServices\boot.efi"
  endif
endfor
```

For some reason your `startup.nsh` has the VirtualBox 6.0 and 5.2 drivers:
```
load fs0:\EFI\OC\Drivers\AppleImageLoader.efi
load fs0:\EFI\OC\Drivers\AppleUiSupport.efi
load fs0:\EFI\OC\Drivers\ApfsDriverLoader.efi
map -r
```

**Comment by myspaghetti** [comment]
You can boot macOS manually by entering `fs0:\System\Library\CoreServices\boot.efi` in the EFI Internal Shell (replace `0` with subsequent `fs` numbers until macOS boots) *but* I would like you to post `startup.nsh` here so I can troubleshoot the issue.

If you don't mind, please rename `macOS_startup.nsh` to `macOS_startup.nsh.txt` (or whatever you like with a `.txt` suffix) and attach it here.

The correct `startup.nsh` is supposed to look like this:
```
echo -off
if exist "fs0:\EFI\NVRAM\MLB.bin" then
  dmpstore -all -l fs0:\EFI\NVRAM\MLB.bin
  dmpstore -all -l fs0:\EFI\NVRAM\ROM.bin
  dmpstore -all -l fs0:\EFI\NVRAM\csr-active-config.bin
  dmpstore -all -l fs0:\EFI\NVRAM\system-id.bin
endif
for %a run (1 5)
  if exist "fs%a:\EFI\NVRAM\MLB.bin" then
    dmpstore -all -l fs%a:\EFI\NVRAM\MLB.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\ROM.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\csr-active-config.bin
    dmpstore -all -l fs%a:\EFI\NVRAM\system-id.bin
  endif
endfor
for %a run (1 5)
  if exist "fs%a:\macOS Install Data\Locked Files\Boot Files\boot.efi" then
    "fs%a:\macOS Install Data\Locked Files\Boot Files\boot.efi"
  endif
endfor
for %a run (1 5)
  if exist "fs%a:\System\Library\CoreServices\boot.efi" then
    "fs%a:\System\Library\CoreServices\boot.efi"
  endif
endfor
```

For some reason your `startup.nsh` has the VirtualBox 6.0 and 5.2 drivers:
```
load fs0:\EFI\OC\Drivers\AppleImageLoader.efi
load fs0:\EFI\OC\Drivers\AppleUiSupport.efi
load fs0:\EFI\OC\Drivers\ApfsDriverLoader.efi
map -r
```

**Comment by dac09** [comment]
Rapid reply! 🔥

Not a very long output so I'm just going to place it here:
```
echo -off
if exist "fs0:\EFI\NVRAM\MLB.bin" then
  dmpstore -all -l fs0:\EFI\NVRAM\MLB.bin
  dmpstore -all -l fs0:\EFI\NVRAM\ROM.bin
  dmpstore -all -l fs0:\EFI\NVRAM%
```

Clearly incomplete. Tried replacing the contents with your script, just goes into shell currently.

**Comment by myspaghetti** [comment]
Yes, you need to replace `startup.nsh` on the ESP (EFI System Partition) as described in the documentation section about updating NVRAM variables. You need to execute on the host `./macos-guest-virtualbox.sh create_macos_installation_files_viso` and then boot into the macOS VM, mount the ESP, and copy the new `startup.nsh` to the ESP, see the docs for more details.

Very strange that the file would be cut off like that *and* that the part meant for VBox 5.2/6.0 is present on a VBox 6.1 installation. I'll test the stage `create_macos_installation_files_viso` on `zsh` which I assume you're using.

**Comment by myspaghetti** [comment]
If you still haven't replaced it, I'd appreciate the content of `startup.nsh` from the VM's ESP too.

**Comment by dac09** [comment]
I'm just rerunning the setup at the moment, will report back in a bit. 

Yes, I'm using zsh. FYI, I did just update virtualbox (with brew cask), maybe something didn't go through properly? After a full restart it seems to be behaving a little differently.

**Comment by myspaghetti** [comment]
Bug reproduced. `zsh` interprets `\c` as a break.

**Comment by dac09** [comment]
I'll get back to you later on this, going to be afk for a bit! Installation seems to be going better so far, will wait it out - if I still see the issue, I'll try it with bash.

Thanks so much for the help so far.

**Comment by myspaghetti** [comment]
Fixed in [version `0.96.5`](https://github.com/myspaghetti/macos-virtualbox/commit/94e8f98c594246f6c37612081ebb0d0e56b8b4a9)

**Comment by dac09** [comment]
💯 you are a super hero.

**Comment by myspaghetti** [comment]
Well I put the bug there in the first place so I'm a supervillain too.

**Comment by dac09** [comment]
FYI, bug was probably related, but seems to have worked without the change this time. It was either a weird state my machine was in (after vbox upgrade). 

You took my breath away with this tool today haha, no clicking installation of a full os? Super hero in my books

**Comment by myspaghetti** [comment]
The bug only appears on VirtualBox 5.2 or 6.0 when executing the script on `zsh`

Thank you for finding it and for your excellent issue reporting.
