### ISSUE TITLE
Failed to create "Catalina_BaseSystem.vdi".

### ISSUE THREAD

**Issue by s3hMC** [myspaghetti/macos-virtualbox#283]
I'm pretty sure I did everything right, but I got this error message at the end of running . MacOS _was_ created in VirtualBox, but when I run it it just opens up [this window](https://i.imgur.com/HawIkT7.png).

**Comment by myspaghetti** [comment]
It's very likely `BaseSystem.dmg` failed to download or the file is corrupt. There should be an error message from `dmg2img` prior to `Failed to create`.

**Comment by s3hMC** [comment]
> 
> 
> It's very likely `BaseSystem.dmg` failed to download or the file is corrupt. There should be an error message from `dmg2img` prior to `Failed to create`.

So how can I fix this?

**Comment by myspaghetti** [comment]
You need to provide more details first. Please post the complete output of the last executed stage of the script.

**Comment by s3hMC** [comment]
`stage: populate_basesystem_virtual_disk
Converting BaseSystem.dmg to BaseSystem.img
./macos-guest-virtualbox.sh: line 684: dmg2img: command not found
Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseS
ystem.vdi"...
VBoxManage.exe: error: Cannot open file "Catalina_BaseSystem.img": VERR_FILE_NOT
_FOUND
Failed to create "Catalina_BaseSystem.vdi".
Exiting.
`

**Comment by s3hMC** [comment]
https://i.imgur.com/ooW7G09.png

**Comment by myspaghetti** [comment]
What's the output of `dmg2img -d`

**Comment by s3hMC** [comment]
Command not found

**Comment by myspaghetti** [comment]
For some reason the script did not exit when the dependency was checked. Please upload the file `macOS_troubleshoot.txt` generated when running `./macos-guest-virtualbox.sh troubleshoot`

You can skip the hash generation, I just need to know the script version, OS version, etc, provided by the first stage of troubleshooting.

**Comment by s3hMC** [comment]
https://pastebin.com/raw/aFz7QsrP

**Comment by myspaghetti** [comment]
Please attach the entire file here by clicking on the "Attach files" in the comment box. The pastebin is missing most of the relevant information.

**Comment by s3hMC** [comment]
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5013592/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
Totally my fault, I messed up the `dmg2img` check. Fixed in [version 0.96.6](https://github.com/myspaghetti/macos-virtualbox/commit/261b2bb61e2e0fe593bae73db709dce9a1966539)

**Comment by s3hMC** [comment]
Cool, thanks a lot. The mac works! Just one more question, is there a way to get more than 15 fps?

**Comment by myspaghetti** [comment]
On VirtualBox, probably not. On KVM/QEMU, with GPU passthrough.

**Comment by s3hMC** [comment]
One more thing, there was a command to delete all of the temporary files created by the script, but I forget it. Could you please remind me?

**Comment by myspaghetti** [comment]
`./macos-guest-virtualbox.sh prompt_delete_temporary_files`

**Comment by s3hMC** [comment]
Thanks!
