### ISSUE TITLE
Install specific subversion

### ISSUE THREAD

**Issue by timwr** [myspaghetti/macos-virtualbox#285]
Excellent work @myspaghetti !!!
Is it possible to install a specific OSX version (e.g 10.15.4 as opposed to 10.15.6)?
Alternatively is it possible to install 10.15.0 without having it auto-update to 10.15.6?
Many thanks!
Tim

**Comment by myspaghetti** [comment]
The script can be made to fetch any version of the macOS installer available from `swscan.apple.com`. Looking at the [Catalina software update catalog](https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog) for example, the available versions are `10.14.5.0.0.1563168771`, `10.14.6.0.0.1569030045`, `10.13.6.0.0.1544783150`, `10.14.4.0.0.1552634279`, `10.13.5.0.0.1525410252`, `10.15.3.0.0.1583234667`, `10.15.4.0.0.1587988616`, `10.15.5.0.0.1591330708`, and `10.15.6.0.0.1594329682`

The script looks for the string specified in the variable `CFBundleShortVersionString` when determining the download URL, and selects the last (latest) match.

You can change `CFBundleShortVersionString` to `10.15.4` for example, in line `339`, or add specific versions of Catalina, or even allow user input for the version string.

See the attached [macos-guest-virtualbox.sh.txt](https://github.com/myspaghetti/macos-virtualbox/files/5015947/macos-guest-virtualbox.sh.txt) for a hardcoded download of `10.15.4`, where line `339` has been replaced with the following:
```
    CFBundleShortVersionString="10.15.4"
```

I think there are developer software update catalog URLs that have more versions available.

I currently don't plan on implementing version selection, but I will accept pull requests.

**Comment by timwr** [comment]
@myspaghetti thanks so much!!! You've saved me a lot of time and hassle.

**Comment by timwr** [comment]
fyi: This is working for 10.15.3 and 10.15.4 but not 10.15.2:
```
Downloading Apple macOS Catalina software update catalog
Catalina_sucatalog                                   100%[=====================================================================================================================>]   6.40M  --.-KB/s    in 0.1s
Trying to find macOS Catalina InstallAssistant download URL
Catalina_sucatalog_00_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  40.05K  --.-KB/s    in 0.007s
Catalina_sucatalog_01_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.03K  --.-KB/s    in 0.006s
Catalina_sucatalog_02_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.99K  --.-KB/s    in 0.006s
Catalina_sucatalog_03_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.98K  --.-KB/s    in 0.007s
Catalina_sucatalog_04_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.98K  --.-KB/s    in 0.005s
Catalina_sucatalog_05_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.98K  --.-KB/s    in 0.007s
Catalina_sucatalog_06_InstallAssistantAuto.smd       100%[=====================================================================================================================>]     969  --.-KB/s    in 0s
Catalina_sucatalog_07_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.90K  --.-KB/s    in 0.005s
Catalina_sucatalog_08_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  36.57K  --.-KB/s    in 0.004s
Catalina_sucatalog_09_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.90K  --.-KB/s    in 0.005s
Catalina_sucatalog_10_InstallAssistantAuto.smd       100%[=====================================================================================================================>]  39.90K  --.-KB/s    in 0.005s
Couldn't find the requested download URL in the Apple catalog. Exiting.

```

**Comment by myspaghetti** [comment]
Version `10.15.2` is not in the catalog.

**Comment by myspaghetti** [comment]
Closing as `won't fix` but pull requests that implement this are welcome.
