### ISSUE TITLE
Converting VDI to VMDK

### ISSUE THREAD

**Issue by s3hMC** [myspaghetti/macos-virtualbox#286]
Hi,
I'm planning on switching from VirtualBox to QEMU, and so I want to convert the VDI file created by the script to VMDK. When I try the command provided by the script (`VBoxManage clonehd --format vmdk source.vdi target.vmdk`), I get the error message that the command is not found. Am I doing something wrong? 
(Also, unrelated to the question, but any tips for using QEMU are welcome!)

Thanks

**Comment by myspaghetti** [comment]
The path to `VBoxManage` needs to be in the environment's `PATH` variable.
