### ISSUE TITLE
Script checks login shell

### ISSUE THREAD

**Issue by alexs77** [myspaghetti/macos-virtualbox#288]
The script has a few checks for `$SHELL`. This contains the LOGIN SHELL of the user. For me, it is Fish. And as Fish isn't supported, it of course exits.

But when the script is run with either `./macos-guest-virtualbox.sh` or especially with `zsh macos-guest-virtualbox.sh` or `bash macos-guest-virtualbox.sh`, the login shell doesn't matter at all.

Even though I have Fish as a login shell, I was successfully able to run the script after I removed these `$SHELL` checks.

**Comment by myspaghetti** [comment]
You're correct, the script used `${SHELL}` incorrectly. Fixed in [version `0.96.7`](https://github.com/myspaghetti/macos-virtualbox/commit/a83e5de9c1a28a357b4d88339747905bda048f87)
