### ISSUE TITLE
Gray Screen with cursor

### ISSUE THREAD

**Issue by TravikSkoot** [myspaghetti/macos-virtualbox#289]
I am currently trying to install High Sierra and I have the latest version of the script, but when I try to boot it only shows a grey screen with the cursor, where instead should be the language screen.

Phil

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5037631/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
You appear to be using a modified version of the script that skips the dependency checks.
