### ISSUE TITLE
Please execute this script with Bash 4.3 or higher, or zsh 5.5 or higher

### ISSUE THREAD

**Issue by dfuentes03** [myspaghetti/macos-virtualbox#292]
**Issue:** 
When trying to execute `./macos-guest-virtualbox.sh` I'm presented with the following message:
```
Please execute this script with Bash 4.3 or higher, or zsh 5.5 or higher.
macOS detected. Make sure the script is not executed with
the default /bin/bash which is version 3.
```

**Troubleshooting:**
- If I check the bash version I have installed via `bash --version` I get the following returned:
```
GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

- Same version I get returned when I run `echo "${BASH_VERSION}"`:
`5.0.18(1)-release`

- I did `cd /bin/` and ran `bash --version` on that directory and got the same returned.
![Screen Shot 2020-08-11 at 12 03 13 PM](https://user-images.githubusercontent.com/48250453/89921015-28f1ca00-dbcb-11ea-8007-83e17530d814.png)

How can I get around this issue?

**Comment by dfuentes03** [comment]
Per #195 I changed the script from `#!/bin/bash` to `#/bin/bash` and that seems to have fixed it.
Feel free to close this ticket and sorry about the trouble.

Thanks!

**Comment by myspaghetti** [comment]
The script is executed on `/bin/bash` which is version 3 on macOS, as the script helpfully points out:
```
macOS detected. Make sure the script is not executed with
the default /bin/bash which is version 3.
```
The correct solution is executing the script with a supported version of `bash` or `zsh`. Please do not confuse removing the hashbang with fixing the issue, removing the hashbang merely makes the shell guess the correct executable for the script.

**Comment by dfuentes03** [comment]
> The script is executed on `/bin/bash` which is version 3 on macOS, as the script helpfully points out:
> 
> ```
> macOS detected. Make sure the script is not executed with
> the default /bin/bash which is version 3.
> ```
> 
> The correct solution is executing the script with a supported version of `bash` or `zsh`. Please do not confuse removing the hashbang with fixing the issue, removing the hashbang merely makes the shell guess the correct executable for the script.

I agree, however, but per the returned when executing `bash --version` and  `echo "${BASH_VERSION}"` I'm on `5.0.18(1)-release` which is a higher version than what is required.

What am I doing wrong that it's still executing using version 3?

**Comment by myspaghetti** [comment]
The shell reads the hashbang and uses `/bin/bash`

When you remove the hashbang, the shell uses the default shell (`zsh`)

Either explicitly execute the script with a supported shell or edit the hashbang so it points to a supported `bash` or `zsh`
