### ISSUE TITLE
Display Refresh Rate

### ISSUE THREAD

**Issue by ethanbeyer** [myspaghetti/macos-virtualbox#293]
I've got the VM installed and working great, thank you!

My only question is whether I can increase the framerate of the VM in any way. The only setting I see for Display memory is in the script and the VM Settings, maxed at 128MB. I've enabled Hardware Acceleration, but it seems like my GPU is not being engaged at all - so the VM is running sub 30fps.

Is there any way to increase this?

**Comment by myspaghetti** [comment]
You could manually increase the VRAM to 256 by editing the `.vbox` file but you will not see a noticeable increase in graphics performance. If you want proper graphics performance I recommend using KVM/QEMU with GPU passthrough, which runs almost exactly like a genuine Mac. No support is offered for KVM/QEMU.

**Comment by ethanbeyer** [comment]
I completely understand. Initially, I thought this was my error in setting up. After posting this issue I did research (apologies for doing things in this order), and realized that it's a VB limitation.

I appreciate this script and how easy it is to use, though! Thank you again @myspaghetti!

For posterity, it seems to me that this script shines in its ability to create a VM at all, but for longterm use, to prepare a `.vmdk` for use elsewhere, in order to fully utilize a system's hardware capabilities.
