### ISSUE TITLE
Run VM From External SSD

### ISSUE THREAD

**Issue by dfuentes03** [myspaghetti/macos-virtualbox#294]
I checked out `./macos-guest-virtualbox.sh documentation` and didn't find anything related to this topic, so I apologize if it's a redundant question. Also, the URL at the end of the documentation output seems to be missing.

**Question:** Is it possible to move the macOS VM to an external SSD so that I can increase the disk space without it consuming my internal disk space? If so, how can I go about doing so?

**Comment by myspaghetti** [comment]
Yes, in fact I only run the script on external drives. Simply run the script from a directory on the external drive, for example `/Volumes/Time Machine` or `/mnt/usb0` or `/cygdrive/d/` or whatever is the corresponding path on your system.

VirtualBox itself stores two important files, `macOS.vbox` and `macOS.nvram` in a different path, but you can simply copy these files to the external drive if you need to use them on another machine.

**Comment by myspaghetti** [comment]
Yes. Power off the virtual machine, release and remove the storage devices from the VirtualBox media manager GUI, move the files to wherever you want, and then attach them to the virtual machine from the VirtualBox virtual machine storage settings.

VirtualBox itself stores two important files, `macOS.vbox` and `macOS.nvram` in a different path, but they don't take up a significant amount of storage space.
