### ISSUE TITLE
gpu_vram showing low value

### ISSUE THREAD

**Issue by codevski** [myspaghetti/macos-virtualbox#302]
Heya 😄 

Love the script makes the install so much easier.

Just wondering about the gpu_vram option it seems to be stuck on 7mb. 

![image](https://user-images.githubusercontent.com/1435321/92115021-23d41380-ee35-11ea-98b9-0e5fdb2f6434.png)

In VM settings its set to 128mb not sure what could be causing this?

Host spec:
CPU: i909900K
RAM: 32GB
GPU: 2080ti
OS: win10
Vbox: 6.1.12

**Comment by myspaghetti** [comment]
This is a VirtualBox issue. The displayed VRAM depends on the virtual machine's display resolution and not the assigned VRAM. You can increase the graphics performance a little bit by installing [VMWare Tools](https://packages.vmware.com/tools/releases/latest/) but the only way to get decent performance is with GPU passthrough on QEMU/KVM.
