### ISSUE TITLE
Should put how big files are

### ISSUE THREAD

**Issue by ToastyNIck** [myspaghetti/macos-virtualbox#303]
![image](https://user-images.githubusercontent.com/32781165/92609490-a0774f80-f284-11ea-91e6-096c43c559a4.png)
During the download process. It does not show how big the file it is.  All it shows is how much is downloaded. You could put like Downloaded/File Size. For example 475.48M/1285M
When downloading. I like to know how big is a file it is so I can estimate it should be ready. Yes there is the Estimated Time Arrival (eta) time but the script does not know our internet. Sometime we know our internet connection can change so we need something mentally to expect when it's done.

I know code is hard but I will fork this git and see If I can add my idea

**Comment by myspaghetti** [comment]
This can be achieved by removing the `--quiet`  flag from `wgetargs`, however this behavior is by design and I find that the percentage, downloaded size, throughput, and time estimate are sufficient.
