### ISSUE TITLE
VERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by MyCatCondo** [myspaghetti/macos-virtualbox#304]
I ran the script, and it ran like normal in Cygwin, but towards the end, I get this:
`Converting BaseSystem.dmg to BaseSystem.img`
`macos-guest-virtualbox.sh: line 315: /cygdrive/v/dmg2img.exe: Permission denied`
`Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseS
ystem.vdi"...`
`VBoxManage.exe: error: Cannot open file "Catalina_BaseSystem.img": VERR_FILE_NOT
_FOUND`
`Failed to create "Catalina_BaseSystem.vdi".`
`Exiting.`
I have no idea what this means, but I'm putting the media on an OpenMediaVault (5mb per second download) and that might be messing it up.
Edit: Added GitHub Gist of script when ran. View it [here](https://gist.github.com/MyCatCondo/e65ae930f354ea8a1264341d7925ae78).
Edit 2: I just noticed it says `macos-guest-virtualbox.sh: line 315: /cygdrive/v/dmg2img.exe: Permission denied`. I think that's the culprit, but I don't know what to do about it.

**Comment by myspaghetti** [comment]
Thanks for the bug report. My best guess is that Windows permissions for files on `V:` are set for read/write but not execute, and despite the script attempting to add the `+x` permission it silently fails.

From Windows's built-in Explorer, open the properties for `dmg2img.exe` and edit the permissions so the active user can execute the file.

**Comment by MyCatCondo** [comment]
Yeah, I tried that but the script just reinstalls it and overwrites the permissions. I use linux to host the V:/ (for "Virtual Machines") by the way.

**Comment by myspaghetti** [comment]
Oh if it's a network share then you have to configure permissions on the server side. Pretty sure Windows network shares are not permission-aware. Alternatively you can put `dmg2img.exe` in a directory that's in the `PATH` variable. Closing as "won'tfix" because making the script aware of network shares and Windows permissions is too much effort for me.

**Comment by MyCatCondo** [comment]
Oh, I think I'm signed in as a guest. I will sign in as a user. If that doesn't work, I will turn to the web control panel. I'm not the greatest with scripts, but if I can figure out getting this to work, I will create a pull request. Thanks for your help! By the way, this script is great! Keep up the awesome work!

**Comment by MyCatCondo** [comment]
Ok, I changed a few things and now it is going to work.

**Comment by rbdone** [comment]
> Ok, I changed a few things and now it is going to work.

I'm getting the same issue on macOS. What things did you change to get it to work for you @MyCatCondo?

**Comment by MyCatCondo** [comment]
@rbdone, dmg2img is working, but for some reason it says `Segmentation error` so that might be a problem with the code.

**Comment by MyCatCondo** [comment]
You might want to reinstall the macOS-virtual box script and try again.

**Comment by rbdone** [comment]
That totally resolved it. Thanks @MyCatCondo!

I may have messed it up initially by running (partial run) it before upgrading bash/wget/etc and installing dmg2img.

**Comment by MyCatCondo** [comment]
I’m glad it worked out @rbdone! Happy to help!
