### ISSUE TITLE
[Enhancement] Guest Additions installation 

### ISSUE THREAD

**Issue by commcad** [myspaghetti/macos-virtualbox#305]
::Enhancement::

Below are the steps I've recently had to go through to get the tools to install (found on the Internet, google strings for authors). 

**Beware, tested on Catalina only.** Wondering if this could be tested by @myspaghetti (and others; use at your own risk) and if proven "stable" perhaps be added in the automated script a way or another?

**## BOOT IN RECOVERY MODE ##**
In macOS Catalina, Utilities>Terminal:
**$ sudo nvram recovery-boot-mode=unused && sudo shutdown -r now**
Once in recovery mode you can run the commands you need in Utilities>Terminal.
**$ csrutil disable**
Get out of recovery mode and reboot
**$ nvram -d recovery-boot-mode && shutdown -r now** 

**## PREPS FOR GUEST ADDITIONS INSTALLATION ##**
Once in macOS Catalina, Utilities>Terminal:
**$ sudo mount -uw /
$ sudo chown :admin /System/Library/Extensions/
$ sudo chmod 775 /System/Library/Extensions/
$ sudo spctl --master-disable**  //(to re-enable: $ sudo spctl --master-enable

Mount Guest Addition CD-ROM, install, reboot, done!

**Comment by myspaghetti** [comment]
What exactly are you proposing here?

**Comment by commcad** [comment]
**Automated pre-modifications** for the VirtualBox Guest Additions installation to successfully install. Thus providing the functionalities such as copy/paste, share, etc... 

I'll leave the technical part regarding implementation and how this could be done creatively to you (others) ;)

**Comment by myspaghetti** [comment]
Disabling System Integrity Protection for these very minor conveniences seems like a bad idea.

**Comment by felipealmeida** [comment]
Tested and works. Have no idea what the guest additions add as new features or functionality though

**Comment by startergo** [comment]
> Disabling System Integrity Protection for these very minor conveniences seems like a bad idea.

Here is a way to disable/install re-enable SIP. Maybe this can be automated?
```
In the guest Mac, open the Terminal and go for a reboot on the Recovery partition
 
sudo nvram "recovery-boot-mode=unused" && sudo reboot
 
    Now you're in Recovery mode, enter the Terminal and do:
 
csrutil disable
spctl kext-consent add VB5E2TV963
nvram -d recovery-boot-mode && reboot
 
    Back in "normal" mode, open the Terminal, and do:
 
sudo mount -uw /
sudo chown :admin /System/Library/Extensions/
sudo chmod 775 /System/Library/Extensions/
 
Download latest VBoxGuestAdditions.iso from https://download.virtualbox.org/virtualbox/ and attach the iso to the virtual machine.
 
    Run the Guest Additions installer and go through the end (in principle, it goes through successfully)
 
    Now in the terminal, do:
 
sudo chown :wheel /System/Library/Extensions/
sudo chmod 755 /System/Library/Extensions/
sudo nvram "recovery-boot-mode=unused"
sudo reboot
 
    Again in Recovery mode, go into the Terminal and do:
 
csrutil enable
nvram -d recovery-boot-mode
reboot
```

**Comment by organicdeveloper-net** [comment]
HELLO

_______THANKYOU SO MUCH I STILL HAVEN'T GOT SPAGHETTI TO WORK BUT I AMA  A HUGE FAN AND BLV I RCV THE FRAMEWORK 4 THE PUNCH INSTALL IM
JUST LEARNING CODE

BUT I'M DOING GREAT WORK WITH VIRTUAL MAC OS X VMS
IN V BOX
CURRENTLY MY GOAL IS TO GET THEM ALL ORGANIZED IN vs STUD OR iNTELLIj
AND WRK EM ALL TOGETHER W A DJANGO PROJECT OR SUM JUPYTER NOTEBOOK IMPLMENTATION
I HAVE TONS AND TONS OF NOTES AND PICS FROM ALL MY TESTING WOULD LIKE TO BE ABLE TO COMPRESS AND SHARER


THX FOR REACHING OUT N PLEASE KEEP ME POSTED 😊OMG
IM A VM FREAK


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by startergo** [comment]
A better alternative is Vmware tools which will give 128MB of vRAM and can be downloaded from here:
https://github.com/paolo-projects/unlocker
After installation please rename the "VMware Tools" folder located under "/Library/Application Support/", which will prevent from constant crashes/reboots. There is no need to add the developer ID of VMWARE in recovery console to spctl kext-consent, but these steps are necessary for the installation:

```
In the guest Mac, open the Terminal and go for a reboot on the Recovery partition
 
sudo nvram "recovery-boot-mode=unused" && sudo reboot
 
Now you're in Recovery mode, enter the Terminal and do:
 
csrutil disable
nvram -d recovery-boot-mode && reboot

Back in "normal" mode, open the Terminal, and do:

sudo mount -uw /
sudo chown :admin /System/Library/Extensions/
sudo chmod 775 /System/Library/Extensions/

Run the Guest Additions installer and go through the end.

 Now in the terminal, do:
 
sudo chown :wheel /System/Library/Extensions/
sudo chmod 755 /System/Library/Extensions/
sudo nvram "recovery-boot-mode=unused"
sudo reboot
 
 Again in Recovery mode, go into the Terminal and do:
 
csrutil enable
nvram -d recovery-boot-mode
reboot

```

**Comment by myspaghetti** [comment]
You can get [newer VMWare Fusion packages (version 11.1.0)](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.1.0/13668589/packages/)

**Comment by startergo** [comment]
> You can get [newer VMWare Fusion packages (version 11.1.0)](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/11.1.0/13668589/packages/)

Thanks. Corrected links.

**Comment by commcad** [comment]
@startergo thanks for sharing this, works great. Slowly starting to look & feel like a pwr VM now!

**Comment by sryze** [comment]
Thanks for sharing :+1:  I finally was able to install the guest additions on Catalina with this. I think the chown step is not necessary though, since the installer already runs scripts with root privileges.
