### ISSUE TITLE
[Question] Anyone having difficulties sync'ing a iPhone X to the VM's macOS?

### ISSUE THREAD

**Issue by commcad** [myspaghetti/macos-virtualbox#306]
The bash script worked out without a glitch. Quite impressive work went into this and I'm grateful to the author for the share. Performance is what you'd expect from a VM/virtualization too so all in all I'm fairly happy right now!!! Thank you.

 I'd be even more happy if I could sync my iPhone with the VM :/ I'm hoping to use the VM as a mobile dev platform, which is perfectly fine using the built-in simulators mind you, however not being able to sync a real-life dev iPhone is annoying.

Anyone knows of a 'workaround' this lil issue?

ps. the iPhone shows up in Picture. Have access to its hdd via usb, see pics, but that's it. Doesn't show up in finder, nor in xcode. 
pps. yes, I've just bought this iPhone for dev (I'm coming from Android), Hopefully I don't have to buy their MAC above all?

**Comment by commcad** [comment]
I've just found several claims online of "USB over ethernet" being the only workaround. True/false?
If anyone could confirm that's working, and what software/tool you are using, I'd sincerely appreciate. Thanks folks.

**Comment by myspaghetti** [comment]
USB devices generally don't work as intended through the VirtualBox USB passthrough on macOS guests. There are a few workarounds:

* Use KVM/QEMU and PCI passthrough with a PCI USB card.
* Use VMWare
* Use USB over IP as you mentioned.

**Comment by commcad** [comment]
Interestingly enough the OS sees the iPhone hex's VID, PID, SN and all the other bits (under Utility > System Info > Hardware : USB). Fwiw; not interested into VMRare, had severe data corruption/losses in the past and still traumatized. Couldn't care less if they've squared those bugs out already or not.

I'll look into USB over IP soft & hardware dongles and see where this goes. Seems like the easiest and most affordable solution. Thanks for confirming that info by the way, appreciated.

(Damn...)

**Comment by commcad** [comment]
After investigating into this a bit further it appears Oracle can be outsourced to commercially engineer a "driver" for iPhone, or else DIY in the case of Virtualbox. Therefore, and since my dev goals are toward mobility, I'm going to pass on that challenge!

I did however successfully tested a 3rd party driver (USB to IP) and it works fine! I'll use/test their 14days trial and give that a go a PayPal bump if all remains glory.

I'm closing this rant for now; if anyone have the driver available please share or at least try to compete the $159 asked price for that existing driver. That'd be useful for quite a few I'm sure. Thanks
