### ISSUE TITLE
Command in MacOS terminal failes while concatenating files.

### ISSUE THREAD

**Issue by akiftariq** [myspaghetti/macos-virtualbox#308]
Hi,
I was able to create VMs successfully a few months ago. But I tried yesterday after a long time and I get this.

![VirtualBox_macOS_29_09_2020_13_00_57](https://user-images.githubusercontent.com/9317940/94530223-3551e500-0254-11eb-8083-ff8c4b33ff0b.png)

sed: RE error: illegal byte sequence

I am using cygwin (64 bit) with all the prerequisites installed except tesseract as I like to continue by pressing enter manually over the terminal. I have tried with tesseract also, but no use.

**Comment by myspaghetti** [comment]
Thanks for the report. I'm assuming this is Catalina? Currently investigating.

**Comment by akiftariq** [comment]
Yes @MechantRouquin. It is Catalina.

**Comment by myspaghetti** [comment]
If you still have the installation files, check that `InstallInfo.plist` on the host and on the guest is not corrupt, its `md5sum` is `ced8e0407d153ad2cbc851b49edb39ce` for version `10.15.7.0.0.1600727528`

**Comment by akiftariq** [comment]
> 
> 
> If you still have the installation files, check that `InstallInfo.plist` on the host and on the guest is not corrupt, its `md5sum` is `ced8e0407d153ad2cbc851b49edb39ce` for version `10.15.7.0.0.1600727528`

Yes I think something is wrong with it.

Have a look below:

![image](https://user-images.githubusercontent.com/9317940/94588938-124c2300-029e-11eb-8ce0-a6640fc2485d.png)

**Comment by myspaghetti** [comment]
You should just delete the file then download it again. I'm not sure the version you downloaded is currently available, so if you use the script to download it automatically you will have to download the rest of the Catalina installer version `10.15.7.0.0.1600727528`

**Comment by akiftariq** [comment]
@myspaghetti I tried again after deleting all the old files, but I am still getting the same problem i.e. sed: `RE error: illegal byte sequence`

Following are the contents of Catalina_InstallInfo.plist now:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Additional Installers</key>
	<array/>
	<key>Additional Wrapped Installers</key>
	<array/>
	<key>Diagnostics Image Info</key>
	<dict>
		<key>URL</key>
		<string>AppleDiagnostics.dmg</string>
		<key>chunklistURL</key>
		<string>AppleDiagnostics.chunklist</string>
		<key>chunklistid</key>
		<string>com.apple.chunklist.AppleDiagnostics</string>
		<key>id</key>
		<string>com.apple.dmg.AppleDiagnostics</string>
		<key>sha1</key>
		<string></string>
		<key>version</key>
		<string>10.15.6.0.0.1597084492</string>
	</dict>
	<key>OS Installer</key>
	<string>OSInstall.mpkg</string>
	<key>Payload Image Info</key>
	<dict>
		<key>URL</key>
		<string>InstallESDDmg.pkg</string>
		<key>chunklistURL</key>
		<string>InstallESDDmg.chunklist</string>
		<key>chunklistid</key>
		<string>com.apple.chunklist.InstallESDDmg</string>
		<key>id</key>
		<string>com.apple.pkg.InstallESDDmg</string>
		<key>sha1</key>
		<string></string>
		<key>version</key>
		<string>10.15.6.0.0.1597084492</string>
	</dict>
	<key>System Image Info</key>
	<dict>
		<key>URL</key>
		<string>BaseSystem.dmg</string>
		<key>chunklistURL</key>
		<string>BaseSystem.chunklist</string>
		<key>chunklistid</key>
		<string>com.apple.chunklist.BaseSystem</string>
		<key>id</key>
		<string>com.apple.dmg.BaseSystem</string>
		<key>sha1</key>
		<string></string>
		<key>version</key>
		<string>10.15.6.0.0.1597084492</string>
	</dict>
</dict>
</plist>`

**Comment by myspaghetti** [comment]
Make sure the file `/Volumes/Base System 1/Install macOS Catalina/Contents/SharedSupport/InstallInfo.plist` on the guest is not corrupt.
