### ISSUE TITLE
GNU Varients.

### ISSUE THREAD

**Issue by SamHep0803** [myspaghetti/macos-virtualbox#310]
sort of a duplicate of #268 but for some reason, I get the error even though all of the packages are installed.

![image](https://user-images.githubusercontent.com/14109339/95078966-01c8fc00-0727-11eb-8f94-b0b32c8cff3d.png)

**Comment by myspaghetti** [comment]
Thanks for the bug report! You appear to be using an old version of the script. Please use the [latest version](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/e1fd1988fc7d09119e56dfd0c238f887a6795f8d/macos-guest-virtualbox.sh). The new version has a more verbose error message and checks `xxd` correctly.

**Comment by myspaghetti** [comment]
On closer inspection it appears you are not using this branch of the script at all.

**Comment by myspaghetti** [comment]
Closing until further information is provided.
