### ISSUE TITLE
Terminal near os install phase opens itself twice

### ISSUE THREAD

**Issue by Kubamach** [myspaghetti/macos-virtualbox#312]
So I'm trying to install High Sierra, at the start os install part it opens two terminals when I had one open when the script wanted to and writes invalid things because of it alternating writing in terminals.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report.

* Please attach the `macOS_troubleshoot.txt` file generated by running `./macos-guest-virtualbox.sh troubleshoot`
* Please screenshot and attach the "invalid things" being written in Terminal

**Comment by Kubamach** [comment]
Okay, I will try something and if that won't work I'll send you the report.

**Comment by myspaghetti** [comment]
Closing until further details are provided.
