### ISSUE TITLE
OS not booting

### ISSUE THREAD

**Issue by TechDroid-Creator** [myspaghetti/macos-virtualbox#313]
Hey there , i ran the script on windows through cygwin, it downloaded the dmg file and the VM booted , i was able to get past the first two screens i.e the Language selection and utilities screen , however after this the terminal on the macos was installing something ( sorry i don't remember what exactly) and the script on cygwin said " Press Ctrl + C to exit if it fails Please Wait" . On the mac on terminal i got an error saying (not fully sure) "Invalid byte read" hence i stopped the script on cygwin. After this i rebooted the VM but now its been over an hour or so but all i see is a black screen with a bunch of text. Could you help me with what i can do to possibly fix this?

I tried re running the shell file but however it says a mac image already exists do you want to delete ? (Y/N).

If you need anymore information from my end please let me know i shall provide it.

Thank you

**Comment by myspaghetti** [comment]
>all i see is a black screen with a bunch of text

The immediate suspect:

* VirtualBox is running on an AMD processor, and the last few lines of text in the VM contain the words `LoadKernelFromStream`, `EndRandomSeed` or `EXITBS`. If that's the case check [the documentation](https://github.com/myspaghetti/macos-virtualbox#documentation) about CPU profiles, and if none of them work you will have to use [custom CPUID settings.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport)

If that's not the case, please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `macOS-troubleshoot.txt` file here.

**Comment by Yethal** [comment]
@TechDroid-Creator If you're running Ryzen, try changing the CPU profile to the Xeon one. I managed to successfully install Catalina on two different Ryzen machines.
@myspaghetti I think it'd be useful if CPU profile was listed at the top of the script with other variables so that it's easier for users to set it ahead of time. If you want I can send a PR

**Comment by myspaghetti** [comment]
Since it's a trial-and-error process I don't think it should be part of the script.

**Comment by Yethal** [comment]
It definitely is. Having it as a variable would make the trial and error process much easier though

**Comment by myspaghetti** [comment]
Closing until further details are provided.
