### ISSUE TITLE
Recreate virtual disk without re-downloading OSX install files

### ISSUE THREAD

**Issue by startergo** [myspaghetti/macos-virtualbox#314]
I have deleted by mistake the virtual disk drive, but I have all necessary files in the folder:
![image](https://user-images.githubusercontent.com/7897244/95686878-8e176b00-0bce-11eb-9ee9-844d3a77c959.png)
What is the command to recreate the machine without internet downloads?

**Comment by myspaghetti** [comment]
`./macos-guest-virtualbox.sh create_bootable_installer_virtual_disk populate_bootable_installer_virtual_disk create_target_virtual_disk populate_macos_target_disk`

**Comment by startergo** [comment]
Thanks for the reply. When it reboots it stops at UEFI shell. When I go and execute startup.nsh it kernel panics, reboots and stops back at shell.
![image](https://user-images.githubusercontent.com/7897244/95691637-849dfb00-0bee-11eb-937b-8b052e6e009a.png)
![image](https://user-images.githubusercontent.com/7897244/95691648-98e1f800-0bee-11eb-9550-b17e074cf6fb.png)

**Comment by startergo** [comment]
I recently updated Windows to build 19041.508. Could that be causing issues? I had the virtual machine working with the previous Windows release.

**Comment by startergo** [comment]
[macOS-2020-10-11T22-45-59-952697400Z.zip](https://github.com/myspaghetti/macos-virtualbox/files/5362300/macOS-2020-10-11T22-45-59-952697400Z.zip)
Attached is a video of the reboot process

**Comment by myspaghetti** [comment]
I think the kernel panic might be happening because you're using an existing NVRAM file and other existing settings for the VM. Keep the downloaded files but delete the VM (or just the `.nvram` file) and try booting the base system.

**Comment by startergo** [comment]
It looks like when I upgraded Windows something was enabled:
```
stage: check_default_virtual_machine

Checking that VirtualBox starts the virtual machine without errors.

Checking that VirtualBox uses hardware-supported virtualization.

Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting.
```
![image](https://user-images.githubusercontent.com/7897244/95695019-0dbf2d00-0c03-11eb-90cb-06f6d67f9fed.png)


Should virtual machine platform be enabled?

**Comment by myspaghetti** [comment]
Anything that uses Hyper-V or offers hypervisor protection should be disabled. There's a lot of stuff that does this, like Windows Sandbox, WSL2, core isolation settings, Device Guard settings, and others. For some reason disabling Hyper-V requires two reboots.

**Comment by startergo** [comment]
Ok it looks like somehow hypervisor functions were enabled. I have disabled them and can manually start the installation and get to the install screen just not automatically so the script stays at the reinstall OSX Window. It is because when I start the machine it goes to the UEFI shall instead of running automatically startup.nsh. What is wrong here?
I run:
```
 ./macos-guest-virtualbox.sh create_target_virtual_disk populate_macos_target_disk
```

**Comment by myspaghetti** [comment]
Automatic booting doesn't work because there might be an existing NVRAM file in the VirtualBox virtual machine folder on the host. You can delete the `.nvram` file and then VirtualBox will look for the boot volume automatically. If that doesn't work you can manually boot `fsN:\System\Library\CoreServices\boot.efi` from the bootable installer and continue using the script normally. Alternatively you can run all the stages in order except `prepare_macos_installation_files` which might corrupt the existing downloaded files (because the script doesn't check downloaded file versions or hashes or anything other than filesize).

**Comment by startergo** [comment]
There was no nvram files in the virtual machine folder, but this command did the trick:
```
./macos-guest-virtualbox.sh check_shell check_gnu_coreutils_prefix check_dependencies prompt_delete_existing_vm create_vm check_default_virtual_machine create_macos_installation_files_viso configure_vm populate_basesystem_virtual_disk create_bootable_installer_virtual_disk populate_bootable_installer_virtual_disk create_target_virtual_disk populate_macos_target_disk
```
All other partial commands were failing at some point.
So to summarize my issue was that during the Windows update/upgrade the hypervisor features were re-enabled which broke the virtual machine in VirtualBox. Just FYI VMWARE 16 does not care anymore if hypervisor features are enabled.
