### ISSUE TITLE
Pass Hardware UUID parameter to the virtual machine

### ISSUE THREAD

**Issue by startergo** [myspaghetti/macos-virtualbox#316]
In about this mac I have the generic:
```
DmiSystemUuid="CAFECAFE-CAFE-CAFE-CAFE-DECAFFDECAFF"
```
And:
```
C:\Program Files\Oracle\VirtualBox>VBoxManage getextradata "macOS" "VBoxInternal/Devices/efi/0/Config/DmiSystemUuid"
Value: 036D7354-CE92-4820-A9BF-35B5A2DC50FE
```
Why is the HARDWARE ID in about this mac still the default? I see this parameter is not passed through NVRAM, how can I change it after the machine is created?

**Comment by myspaghetti** [comment]
macOS records the EFI value to NVRAM on boot. Delete the `.nvram` file from the VM directory so macOS re-populates the NVRAM with the values from the EFI. Alternatively, if you want to preserve the `.nvram` file, you can use the `nvram` command on the guest to [manipulate the NVRAM values](https://github.com/erikberglund/AppleNVRAM/blob/df3514418a8b3782d252412961e8e40366b8303b/All/README.md), but it's easier to just delete the `.nvram` file.

**Comment by startergo** [comment]
Hmm I thought this will load the parameters into NVRAM:

> Loading the generated binary files into the virtual machine NVRAM
Load the generated binary files into VirtualBox VM NVRAM with the builtin command dmpstore in the VM EFI Internal Shell, for example dmpstore -all -l fs0:\system-id.bin

Isn't what startup.nsh is doing when loaded from the UEFI shell?

**Comment by myspaghetti** [comment]
Some parameters are set in EFI (and later loaded to NVRAM) and some are set directly in NVRAM. This is specified in the comments of the script directly next to the variables. The part about deleting the `.nvram` file is specified in the documentation.

```
        Changing the EFI and NVRAM parameters after installation
The variables mentioned above may be edited and applied to an existing macOS
virtual machine by deleting the .nvram file from the directory where the
virtual machine .vbox file is stored, then executing the following
[...]
```
