### ISSUE TITLE
Moving virtualbox image from Mac to Windows

### ISSUE THREAD

**Issue by worldjoe** [myspaghetti/macos-virtualbox#317]
I successfully created a VM on my Mac. I booted it up and successfully activated and signed into iMessage. Then I tried to move the virtualbox to my PC. I tried two different methods. Both failed to boot. I get the "End RandomSeed" as my last message.

First I tried quitting VirtualBox on my Mac and copying over all the files from my Mac to my PC. I opened up my macos.vbox on my PC and it couldn't find the attached disks. I forgot to detach/reattach. I detached everything and reattached the macOS.vdi disk. I had to use vboxmanage sethduuid to get a new uuid since the old was was thought to be attached already. Boot up, no go. Check all the settings, Boot Order (optical, then hard disk ), Processor (tried with and without Enable Nested VT-x/AMD-V). Still won't boot up properly.

Second attempt, I used the "Export Appliance" feature in VirtualBox. Export from mac, Import from PC. Still no boot. The imported Virtual Box has 2 SATA drives attached. Presumably my hard drive (39GB) and what on the mac is called "High_Sierra_Bootable_Installer.vdi". Same problem though. Boot stops at "End RandomSeed"

I know my PC can run MacOS on it, I manually created a Mac OS installer using other manual directions, and I have a High Sierra setup running successfully on my PC. But that one doesn't have iMessage activated properly.

Is there something I need to do when I move my VirtualBox image from Mac to PC? I noticed some variation in commands that need to be run based on CPU. So I'm including my CPU info. My PC has an Intel i9-10900K CPU. The Mac I created this image on has a Quad Core Intel Xeon.

**Comment by worldjoe** [comment]
This fixed it for me:
> VBoxManage modifyvm "${vm_name}" --cpu-profile "Intel Core i7-6700K"

**Comment by davidmatthew-dev** [comment]
I know this issue is closed but for anyone running an Intel i9-7980XE, if you get stuck "waiting for the language window", simply exit the running VBox, open Command Prompt as Admin and set your CPU Profile to:
```
cd "C:\Program Files\Oracle\VirtualBox"
VBoxManage.exe modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```

Just as @worldjoe mentioned. I don't know if this is the case for all i9's but I figured it is good to add my specific CPU.
Other System info to add:
```
NVIDIA GeForce RTX 2080 Ti
Windows 10 (Version 2004 OS Build 19041.804)
VirtualBox Version 6.1.18 r142142 (Qt5.6.2)
