### ISSUE TITLE
Stuck at populate_macos_target_disk stage

### ISSUE THREAD

**Issue by jprojas2** [myspaghetti/macos-virtualbox#319]
Hi! Thanks very much for making this installer! I'm having certain issues though:

First, I was having trouble at the `populate_bootable_installer_virtual_disk` stage, I kept getting the "sed: RE error: illegal byte sequence" error, which I think it's been mentioned in issue #313 .  I solved that by typing `LC_CTYPE=C && LANG=C` and running `bootinst.sh` again.

Everything went on fine until I got to the `populate_macos_target_disk` stage, where both concurrent scripts `startosinstall.sh` and nvram.sh are run but only `startosinstall.sh` finishes, `nvram.sh` is just stuck in a blank terminal.

Any idea why this might be happening?

This is my troubleshoot file:

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5380981/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
The `sed` error indicates that `Catalina_InstallInfo.plist` is corrupt. Could you copy it to `Catalina_InstallInfo.plist.txt` and attach it here please?

**Comment by jprojas2** [comment]
[Catalina_InstallInfo.plist.txt](https://github.com/myspaghetti/macos-virtualbox/files/5380978/Catalina_InstallInfo.plist.txt)

**Comment by myspaghetti** [comment]
Yup, the file is definitely corrupt, and I suspect the other `Catalina_*` files are corrupt too. These are the md5 hashes of the macOS Catalina installer files version `10.15.7.0.0.1600727528`:
```
03c413f6d55c67eb7b5ea9230e658516 *Catalina_BaseSystem.chunklist
47a78e4da956d712a9a307ee8c685cd5 *Catalina_BaseSystem.dmg
a3102f19e7e8b5d4f648f6957ef1e6ae *Catalina_InstallESD.part00
e69d3c60180472aabb5601662df1a14f *Catalina_InstallESD.part01
2ff9f6bce21d66cb29ddb86d054536ed *Catalina_InstallESD.part02
174f03efa7c9210b2037a931ccabcd97 *Catalina_InstallESD.part03
fb0223541180abfd4aeca78d601a2f25 *Catalina_InstallESD.part04
7fa7a79103f276618b37c7d45a16e67e *Catalina_InstallESD.part05
0ac8875fc35e697d740f5acd87c9995d *Catalina_InstallESD.part06
364add8049044e9dfb3040f9b8441543 *Catalina_InstallESD.part07
0bc562caacdb67f0f9d3aed6c8ac63c4 *Catalina_InstallESDDmg.pkg
ced8e0407d153ad2cbc851b49edb39ce *Catalina_InstallInfo.plist
d5f77fade0e8fc6fe9de8d3509f22e02 *Catalina_AppleDiagnostics.chunklist
f924524231976c694062ba7bfd6716e3 *Catalina_AppleDiagnostics.dmg
```

`Catalina_InstallInfo.plist` is an XML file and if you edit it (and it's not corrupt) you can see the version number of the installer under `<key>version</key>` `<string>10.15.7.0.0.1600727528</string>`

Closing as `won't fix` because I don't plan on implementing integrity checks for the downloaded files, but I'd be willing to accept pull requests.

**Comment by jprojas2** [comment]
Thanks! I downloaded the files manually from [here](http://swcdn.apple.com/content/downloads/20/55/001-51042-A_2EJTJOSUC2/rsvf13iphg5lvcqcysqcarv8cvddq8igek/InstallInfo.plist) and the installation went on smoothly.
