### ISSUE TITLE
integrity check, sha256 hashes, checksums, chunklist, corrupt files

### ISSUE THREAD

**Issue by myspaghetti** [myspaghetti/macos-virtualbox#321]
The script does not perform any integrity checks on downloaded files. Apple provides [signed `.chunklist` files that list sha256 hashes of file chunks.](https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7) These files can be used for integrity-checking. Another method is [hosting a database of known-good file hashes.](https://github.com/notpeter/apple-installer-checksums)

Currently I have no plans to implement either solution. Using Apple's signed chunklists is the correct solution and I'm willing to accept pull requests implementing it. Creating a database requires trusting the database maintainer which is not unreasonable but should be avoided.

**Comment by jspraul** [comment]
How do you feel about an 'if possible/available, do it in Python' approach?

[original source](https://gist.github.com/MCJack123/943eaca762730ca4b7ae460b731b68e7#gistcomment-3061078), actually already linked above though the comment was updated recently
 → [incorporated](https://github.com/acidanthera/OpenCorePkg/pull/294) into a [python tool for grabbing the images](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macrecovery/macrecovery.py#L91), with AFAIK only stdlib dependencies for Python2/3
 → used in a [bash4 script to setup QEMU](https://github.com/wimpysworld/quickemu/blob/master/quickget#L694), which demonstrates grabbing hashes from webpages with wget and verifying in bash+various *sum utils

If you have any pointers to how dependency-free bash can work with binary files, feel free to share! It may be possible with some xxd wizardry.
https://unix.stackexchange.com/questions/10801/how-to-use-bash-script-to-read-binary-file-content

**Comment by JayCynine** [comment]
Solution
To implement integrity checks on downloaded files, we can use either the signed .chunklist files provided by Apple or a database of known-good file hashes.

Using Signed .chunklist files
The .chunklist files provided by Apple contain a list of sha256 hashes of file chunks. We can use these hashes to verify the integrity of the downloaded files. Here's how we can do it:

Download the .chunklist file along with the other files.

Verify the signature of the .chunklist file using Apple's public key.

Parse the .chunklist file to obtain the list of sha256 hashes.

Compute the sha256 hash of each downloaded file chunk.

Compare the computed hashes with the hashes in the .chunklist file to verify their integrity.

Here's some Python code to implement this:
import hashlib
import urllib.request

# Download the .chunklist file and the other files
url = 'https://example.com/download'
urllib.request.urlretrieve(url + '/file.chunklist', 'file.chunklist')
urllib.request.urlretrieve(url + '/file1', 'file1')
urllib.request.urlretrieve(url + '/file2', 'file2')

# Verify the signature of the .chunklist file
# (Code to verify the signature using Apple's public key)

# Parse the .chunklist file to obtain the list of sha256 hashes
hashes = []
with open('file.chunklist') as f:
    for line in f:
        if line.startswith('hash'):
            hashes.append(line.split('=')[1].strip())

# Compute the sha256 hash of each downloaded file chunk
for filename in ['file1', 'file2']:
    with open(filename, 'rb') as f:
        filehash = hashlib.sha256(f.read()).hexdigest()

    # Compare the computed hash with the hash in the .chunklist file
    if filehash not in hashes:
        print(f'Error: {filename} is corrupt')


Using a Database of Known-Good File Hashes
Another method to verify the integrity of downloaded files is to maintain a database of known-good file hashes. Here's how we can do it:

Create a database of known-good file hashes. This can be a simple text file or a more sophisticated database system.

Whenever a new file is downloaded, compute its sha256 hash.

Look up the hash in the database to verify its integrity.

If the hash is not found in the database, mark the file as corrupt.

Here's some Python code to implement this:
import hashlib
import urllib.request

# Load the database of known-good file hashes
hashes = set()
with open('hashes.txt') as f:
    for line in f:
        hashes.add(line.strip())

# Download the file
url = 'https://example.com/file'
urllib.request.urlretrieve(url, 'file')

# Compute the sha256 hash of the downloaded file
with open('file', 'rb') as f:
    filehash = hashlib.sha256(f.read()).hexdigest()

# Look up the hash in the database
if filehash not in hashes:
    print('Error: file is corrupt')
else:
    print('File is OK')

**Comment by Bizarrus** [comment]
The problem is located at the **Networking** of VirtualBox.

The installations procedure of Mac OS try to validate the installation packages directly with the apple's servers. When the machine has no internet connection, the installer can't validate the packages.

> See the Issue #669.
