### ISSUE TITLE
HI RE Mac OS 11 BETA in Virtual Box VM

### ISSUE THREAD

**Issue by organicdeveloper-net** [myspaghetti/macos-virtualbox#322]
I RECENTLY LOSSt ACCESS

to my perfectly running VM.
from the day i got my hands on the iso
 i was excited - thus finally got it to boot  in 2.8 min ( including to launch install )
tot time 4 build 1:15
Initial startup 1:40 sec
_______________________________________
ive been a mac over 25+ yr user i have NEVER SEEN a mac boot this fast.
_______________________________________________________________________
2 weeks ran perfectly..
got x code installed..
ran beautifully LET BETA team know how pleased i was with the functionality.
( in all honesty i didnt get to see all the subtle changes)
i have 4 RUNNING Mojave 10.14.3 VMS 
1 Linux MINT
___________________________________________________________________________
 i took really good care and did not modify the VM

_______________________________________________________________
THEN THE HORROR STORY STSRTS
i come back to login after 20 days ...
only to find erro erro erro error
BUT TH GREAT THING IS I MANAGED TO EXPORT an 2.0 ova way back whn runnin good. and always save a back up of VM Folder
NOW IM STUCK SAD , HURT, N MAD
I would think Apple would help me but no..
 im running 2 separate dev accounts for them
4 BETA TESTING
Their " ISO " from apple does not work .. for some weird REASOM EVERYTHING WENT ARRAY
 now it boots to EFI SHELL.

anY sUGGESTIONS""

**Comment by myspaghetti** [comment]
This is an issue tracker for the script, not a general tutorial for running macOS on VirtualBox and definitely not the place to discuss ISOs of Mojave which were never distributed by Apple.
