### ISSUE TITLE
Command not found using cygwin

### ISSUE THREAD

**Issue by arifikhsan** [myspaghetti/macos-virtualbox#323]
trying to execute script gave me this

arifikhsanudin@machine ~/code/virtualbox/macos-virtualbox
$ ./macos-guest-virtualbox.sh
./macos-guest-virtualbox.sh: line 6: $'\r': command not found
./macos-guest-virtualbox.sh: line 15: $'\r': command not found
./macos-guest-virtualbox.sh: line 16: syntax error near unexpected token `$'{\r''
'/macos-guest-virtualbox.sh: line 16: `function set_variables() {

how to solve this?

**Comment by myspaghetti** [comment]
Configure git to use Unix line endings or download the script directly from your web browser.

**Comment by arifikhsan** [comment]
i dont understand how to do that

**Comment by myspaghetti** [comment]
[Save this file and run it with bash](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh)
