### ISSUE TITLE
Cursor deadzone using 3840x2160

### ISSUE THREAD

**Issue by isaiahtaylorhh** [myspaghetti/macos-virtualbox#324]
First, thanks for a FANTASTIC repo.... this is amazing.

I set resolution to 3840x2160 using vboxmanage so that I could use it on my 4k monitor. After doing this, I now have a cursor "deadspot" as described in this thread:

https://forums.virtualbox.org/viewtopic.php?f=22&t=94662

No idea if it is related to this repo.

**Comment by myspaghetti** [comment]
Try changing the pointing device from "USB Tablet" to "USB Multi-Touch tablet" or vice-versa, or to "PS/2 Mouse" (which will require pressing the host key to release the cursor from the VM)

**Comment by myspaghetti** [comment]
Thanks! Try changing the pointing device from "USB Tablet" to "USB Multi-Touch tablet" or the other way, or change it to "PS/2 Mouse" (which will require pressing the host key to release the cursor from the VM)
