### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by FutureMarsWalker** [myspaghetti/macos-virtualbox#325]
Tried running it on windows and kali linux wsl. Both yielded this error:

./macos-guest-virtualbox.sh: line 6: $'\r': command not found
./macos-guest-virtualbox.sh: line 15: $'\r': command not found
./macos-guest-virtualbox.sh: line 16: syntax error near unexpected token `$'{\r''
'/macos-guest-virtualbox.sh: line 16: `function set_variables() {

I have not messed with any of the files. Just cloned the repo and tried to run it.

I am sorry if I missed something in the readme about this.

**Comment by FutureMarsWalker** [comment]
Is there any other info do you need to be able to solve this?

**Comment by myspaghetti** [comment]
Configure git to use Unix line endings or download the script directly from your web browser.
