### ISSUE TITLE
tesseract and terminal recognition

### ISSUE THREAD

**Issue by bridgesense** [myspaghetti/macos-virtualbox#326]
I installed Catalina without any issues.  However there appears to be an issue with the Tesseract function recognizing the terminal during the High Sierra install.

In either case, it might be nice to have an option for manual or automatic prompting - just a suggestion, though.

Nice work on this - keeps getting better and better!

**Comment by myspaghetti** [comment]
Hi, thanks! I'm currently investigating the bug. What resolution was configured for the High Sierra VM? (The default is 1280x800)

**Comment by myspaghetti** [comment]
Reproduced the issue. Fixing now...

**Comment by myspaghetti** [comment]
Fixed in [version 0.97.4](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/004199ef8fdff236abfc9989a500096e235a9a61/macos-guest-virtualbox.sh). Thanks for testing!
