### ISSUE TITLE
Hard reboot loop

### ISSUE THREAD

**Issue by jadar** [myspaghetti/macos-virtualbox#327]
I'm trying to use the script to install macOS Mojave in a guest VM on my Macbook Pro. It seems that once the VM boots up, it gets stuck in a kernel panic cycle. The panic is caused by `corecrypto`. Is there something I'm not configuring correctly?

Host computer: MacBook Pro 15" 2019, Core i9
Host OS: macOS Catalina 10.15.7
VirtualBox: 6.1.16

**Comment by myspaghetti** [comment]
Are you referring to a kernel panic on the host?

**Comment by myspaghetti** [comment]
Hi, could you attach a screenshot of the kernel panic screen? Usually the VirtualBox screenshot shortcut is Host+E and can be configured under Preferences > Input > Virtual Machine > Take Screenshot...

**Comment by jadar** [comment]
Thanks for being willing to help! Here is a screenshot of the panic.
<img width="1288" alt="Screen Shot 2020-10-28 at 1 16 28 PM" src="https://user-images.githubusercontent.com/3793928/97472244-0052b400-1920-11eb-9d5e-71a442caf6fb.png">

**Comment by myspaghetti** [comment]
Googling "FIPS Kernel POST Failed" doesn't demystify the error much...

Let's rule out corrupt installation files... would you mind running `./macos-guest-virtualbox.sh troubleshoot` and attaching the resulting `macOS_troubleshoot.txt` file here?

**Comment by jadar** [comment]
Haha, I did try that. Guess I was hoping that you would have seen that before somewhere else. Here is my troubleshooting file:
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5454224/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
The attached file doesn't have the md5 sums for the installation files. Anyway these are the md5 checksums for the Mojave installer version `10.14.4.0.0.1552634279`:
```
ce2c02a6669dd02d830a97afc285ce17 *Mojave_BaseSystem.chunklist
b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
dbf6d95266beefc887a38c63a7df383a *Mojave_InstallESD.part00
1b5c60cd12a10eacb692f3d36f8046e7 *Mojave_InstallESD.part01
4a3613e31816afc5a750f0c461a54c99 *Mojave_InstallESD.part02
86e61d1dd0ed054e00d4d49ca5bd84f7 *Mojave_InstallESD.part03
e84ab943b9a57a11491ddff9483ac0b3 *Mojave_InstallESD.part04
1d9f2a2a3bbb9d88b15f0114aed56d7d *Mojave_InstallESD.part05
3ffc64e9a5fd3d1cb65314432c3b1c53 *Mojave_InstallESDDmg.pkg
c6ea60bdc05652f06141c284a86b4618 *Mojave_InstallInfo.plist
9ecb9bd94257dbd6eda65049750979c4 *Mojave_AppleDiagnostics.chunklist
46789046cc0a4377c2513cb53fbe00d1 *Mojave_AppleDiagnostics.dmg
```
If all the checksums match then the issue stems from something else.

**Comment by myspaghetti** [comment]
I skimmed through the log and everything seems fine from the VirtualBox side of things.

**Comment by myspaghetti** [comment]
If the checksums are fine I would try disabling guest audio from the VirtualBox GUI.

**Comment by myspaghetti** [comment]
Closing until further info is provided.
