### ISSUE TITLE
[EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by timwr** [myspaghetti/macos-virtualbox#328]
Apologies for raising an issue here as it's unlikely related to this repository, feel free to close it. Actually it occurs on some specific hardware (Dell XPS 15), but not others (Dell XPS 15). 
I get the following when I attempt to boot for the first time:

![VirtualBox_macOS_28_10_2020_16_21_38](https://user-images.githubusercontent.com/684924/97411830-bd9ed500-193b-11eb-8341-e1037b4dc92a.png)

I found the following potential helpful guide but I'm not sure how it applies here:
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eblogexitbsstart

Any ideas?
Thanks so much!

**Comment by timwr** [comment]
I was able to fix this by reading the manual!
I powered off the VM, ran:
`VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"`
It then booted successfully!
Thanks!!!

**Comment by Gokux23** [comment]
where did you run the vboxmanage command?
