### ISSUE TITLE
Script thinks VirtualBox didn't shutdown when it actually did

### ISSUE THREAD

**Issue by JustAnother-Dev** [myspaghetti/macos-virtualbox#330]
Here is the output:
Push-button installer of macOS on VirtualBox

This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.

The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.

Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:

  ./macos-guest-virtualbox.sh documentation | less -R

Press enter to review the script configuration

vm_name="macOS"
macOS_release_name="Catalina"    # install "HighSierra" "Mojave" "Catalina"
storage_size=80000               # VM disk image size in MB. minimum 22000
storage_format="vdi"             # VM disk image file format, "vdi" or "vmdk"
cpu_count=2                      # VM CPU cores, minimum 2
memory_size=4096                 # VM RAM in MB, minimum 2048
gpu_vram=128                     # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution

These values may be customized as described in the documentation.

Press enter to continue, CTRL-C to exit
Can't find VBoxManage in PATH variable,
checking C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
Found VBoxManage

Catalina selected to be downloaded and installed

stage: prompt_delete_existing_vm

A virtual machine named "macOS" already exists.
Delete existing virtual machine "macOS"? [y/N] y
Deleting macOS virtual machine.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

stage: create_vm

stage: check_default_virtual_machine

Checking that VirtualBox starts the virtual machine without errors.

Checking that VirtualBox uses hardware-supported virtualization.

stage: prepare_macos_installation_files

Downloading Apple macOS Catalina software update catalog
Catalina_sucatalog  100%[===================>]   6.42M  1.55MB/s    in 4.2s
Trying to find macOS Catalina InstallAssistant download URL
Catalina_sucatalog_ 100%[===================>]  40.05K  --.-KB/s    in 0.06s
Found download URL: http://swcdn.apple.com/content/downloads/61/24/001-57224/0o1xetys5n505gocjsil5qo0p4kg939elb/

Downloading macOS installation files from swcdn.apple.com

Splitting the several-GB InstallESDDmg.pkg into 1GB parts because
VirtualBox hasn't implemented UDF/HFS VISO support yet and macOS
doesn't support ISO 9660 Level 3 with files larger than 2GB.
creating file 'Catalina_InstallESD.part00'
creating file 'Catalina_InstallESD.part01'
creating file 'Catalina_InstallESD.part02'
creating file 'Catalina_InstallESD.part03'
creating file 'Catalina_InstallESD.part04'
creating file 'Catalina_InstallESD.part05'
creating file 'Catalina_InstallESD.part06'
creating file 'Catalina_InstallESD.part07'

stage: create_nvram_files

stage: create_macos_installation_files_viso
Creating EFI startup script

Creating VirtualBox 6 virtual ISO containing the
installation files from swcdn.apple.com

stage: configure_vm

stage: populate_basesystem_virtual_disk
Catalina_BaseSystem.vdi bootstrap virtual disk image exists.

stage: create_bootable_installer_virtual_disk
Creating Catalina installation media virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 4ddfdf1f-93a6-4dcd-a154-bee2d8d1fafe

stage: populate_bootable_installer_virtual_disk

Creating VirtualBox 6 virtual ISO containing macOS Terminal script
for partitioning and populating the bootable installer virtual disk.

Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.

Until the script completes, please do not manually interact with
the virtual machine.

Press enter when the Language window is ready.

Press enter when the macOS Utilities window is ready.

Press enter when the Terminal command prompt is ready.

Partitioning the bootable installer virtual disk; loading base system onto the
installer virtual disk; moving installation files to installer virtual disk;
updating the InstallInfo.plist file; and rebooting the virtual machine.

The virtual machine may report that disk space is critically low; this is fine.

When the bootable installer virtual disk is finished being populated, the script
will shut down the virtual machine. After shutdown, the initial base system will
be detached from the VM and released from VirtualBox.

If the partitioning fails, exit the script by pressing CTRL-C
Otherwise, please wait.
Waiting for the VirtualBox GUI to shut off.

Could not detach Catalina_BaseSystem.vdi
It's possible the VirtualBox GUI took longer than five seconds to shut off.
The macOS installation may be resumed with the following command:
  ./macos-guest-virtualbox.sh populate_macos_target_disk

**Comment by myspaghetti** [comment]
Hi, I assume you managed to complete the installation with ` ./macos-guest-virtualbox.sh populate_macos_target_disk`

Even when the VirtualBox GUI is not visible, it's possible it's still active, hence the error message. The script only waits five seconds for the virtual machine to shut off but it could take longer. VirtualBox doesn't report this state so it can't be queried directly. Five seconds and an error message seemed to be a good compromise that works most of the time and fails gracefully. Maybe I'll implement a loop instead of a one-time check.

**Comment by myspaghetti** [comment]
[Corrected the error message and added an infinite loop](https://github.com/myspaghetti/macos-virtualbox/commit/f7f3a60cbea4c8084d67e0d0ab01491c41b37201)
