### ISSUE TITLE
Very large drives break the script

### ISSUE THREAD

**Issue by gabrielesvelto** [myspaghetti/macos-virtualbox#332]
I was creating a VM this morning and I accidentally typed 1.2TB (1200000) instead of 120GB (120000) of storage in the `storage_size` variable. The first steps of the process worked correctly but when it came to running the `startosinstall.sh` script within the VM it failed while executing the `diskutil partitionDisk ...` step. Specifically the command failed claiming it couldn't unmount a partition.

Note: I don't have enough storage on my main drive to accomodate a VDI that large but I haven't noticed error messages about that.

**Comment by myspaghetti** [comment]
Thanks for testing! Fixed in [version 0.97.7](https://github.com/myspaghetti/macos-virtualbox/commit/51c272deb523f0c8edf8c5c8fa8828baa8937279)
