### ISSUE TITLE
How to start again?!!!

### ISSUE THREAD

**Issue by mohsenksr** [myspaghetti/macos-virtualbox#334]
Hi. Thanks for this useful bash. I know this is a beginner question but I installed Catalina successfully and after shut down, I understand that it isn't in my virtualbox vm list. How can I start it again or import to virtualbox?

**Comment by giacomo270197** [comment]
I know this issue is closed and it does not concern the script itself, but I had the same issue so I figured I'd drop a hint if still needed. Start VirtualBox as root (sudo Virtualbox) and you'll have it there.

**Comment by myspaghetti** [comment]
If the VM was installed as root, a better solution would be moving the VM files (`macOS.vbox`, `macOS.nvram`, and `macOS.vdi`) to the user's virtual machine directory and changing the permissions so they're user-read-write-able. 

The script is not meant to run as root, please run it with ordinary user privileges.
