### ISSUE TITLE
After populate_macos_target_disk, no installation or booting up

### ISSUE THREAD

**Issue by ygkip** [myspaghetti/macos-virtualbox#335]
EDIT: 3rd try did it

Hello,

I've run the script from the beginning twice and something seems to go wrong at the populate_macos_target_disk stage. The nvram script does something, then startosinstall.sh is called, seems to do some stuff with partitions, then ends, leaving the bash terminal sitting there. When I restart the VM, I'm taken to the recovery screen/macOS utilities. What can I do?

--------------------------------------------------------------------------------------------------------
stage: populate_macos_target_disk

Creating VirtualBox 6 virtual ISO containing macOS Terminal scripts
for partitioning and populating the target virtual disk.

The VM will boot from the populated installer base system virtual disk.

Attempting automated recognition of virtual machine graphical user interface.
Please wait      
The second open Terminal in the virtual machine copies EFI and NVRAM files
to the target EFI system partition when the installer finishes preparing.

After the installer finishes preparing and the EFI and NVRAM files are copied,
macOS will install and boot up when booting the target disk.

Please wait

For further information, such as applying EFI and NVRAM variables to enable
iMessage connectivity, see the documentation with the following command:

  ./macos-guest-virtualbox.sh documentation | less -R

That's it! Enjoy your virtual machine.

stage: prompt_delete_temporary_files
Temporary files may be deleted when the virtual machine is powered off
and without a suspended state by executing the following command at the script's
working directory:

  ./macos-guest-virtualbox.sh prompt_delete_temporary_files

**Comment by 0raculo** [comment]
Same issue here.

**Comment by myspaghetti** [comment]
I suspect the newly-added `sed` command breaks something,  You can test [this old version](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/5f13e2a80e90a83c00d5cfd85e89995e20922c89/macos-guest-virtualbox.sh) which is probably [before I broke it](https://github.com/myspaghetti/macos-virtualbox/compare/5f13e2a...bcd07f5). Or it could be something completely unrelated...

**Comment by 0raculo** [comment]
Old version works! Thank you

**Comment by myspaghetti** [comment]
Closing on the baseless assumption that [the pipes were the problem](https://github.com/myspaghetti/macos-virtualbox/compare/cce2480...b6ba0fd)
