### ISSUE TITLE
How do I add settings for my amd cpu to this script?

### ISSUE THREAD

**Issue by CrappyCodeWithAaron** [myspaghetti/macos-virtualbox#336]
Hi! 
I'd like to start by saying this is the best one click process for a newbie that i've seen. I've been roaming tutorial hell with a lot less success than I've gotten here. on to my question. 
How/where can I add vboxmanage commands to the copy of your script I have downloaded?

For now I have bypassed this by just manually running the commands in a separate terminal window while the script is downloading files. 

for ref

VBoxManage.exe modifyvm "macOS" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff 
VBoxManage setextradata "macOS" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3" 
VBoxManage setextradata "macOS" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0" 
VBoxManage setextradata "macOS" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple" 
VBoxManage setextradata "macOS" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" 
VBoxManage setextradata "macOS" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"

stolen from https://www.geekrar.com/how-to-install-macos-catalina-on-virtualbox-on-amd-systems/

**Comment by myspaghetti** [comment]
All the commands except the first and last ones do not matter, and the first and last commands override each other, so pick one or the other. You can add them at the bottom of the `configure_vm()` function.
