### ISSUE TITLE
I tried running this on (from) big sour but it's stuck at language selection

### ISSUE THREAD

**Issue by davibe** [myspaghetti/macos-virtualbox#337]
The terminal shows dialog like "if partitioning fail hit control c\n please wait"

**Comment by davibe** [comment]
A also see many of these

```
Please waitVBoxManage: error: Argument aWidth is invalid (must be aWidth != 0 && aWidth <= 32767)
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component DisplayWrap, interface IDisplay, callee nsISupports
VBoxManage: error: Context: "TakeScreenShotToArray(iScreen, width, height, BitmapFormat_PNG, ComSafeArrayAsOutParam(saScreenshot))" at line 1880 of file VBoxManageControlVM.cpp
```

**Comment by myspaghetti** [comment]
Seems like VirtualBox fails to take screenshots. I suggest uninstalling tesseract or removing the lines starting with `tesseract_ocr` and `tesseract_lang` from the script (lines 1495 and 1496).

I'm not currently running Big Sur on anything so it'll be a while before I start investigating this bug, but in the meantime you can use the workaround.

**Comment by davibe** [comment]
I have uninstalled `tesseract` and while this removes the error I am still stuck here after repeating the whole process

https://www.dropbox.com/s/16xikobvbv8zsp3/Screenshot%202020-11-14%20at%2018.17.56.png?dl=0

**Comment by myspaghetti** [comment]
If you don't mind, please manually select a language (English would be fine) then manually select Terminal from the top bar. Then on Termianl on the host try sending stuff to the Terminal on the guest, for example:
```
VBoxManage controlvm "macOS" keyboardputscancode 02 82 03 83 04 84 05 85 06 86
```
If this fails it's possible that `VBoxManage` is buggy on Big Sur.

**Comment by davibe** [comment]
I was executing the scrpt with `curl <url> | bash -` and this gave problem
Now i tried downloading the file and seems to be working !!
