### ISSUE TITLE
On Mingw32 script hangs when trying to call VBoxManage 

### ISSUE THREAD

**Issue by atomicwrites** [myspaghetti/macos-virtualbox#338]
Hi, I'm trying to run this on Mingw32 the script just hangs after it asks you to confirm your configuration. I traced the script using `set -x` and the last thing it does is execute 

```
cmd.exe /d /s /c call VBoxManage.exe -v
```

Based on the source it looks like its expecting either VBoxManage to run meaning it's in the path or to get command not found. Instead when I run that command in the shell I get a cmd prompt which obviously never returns. Based on the documentation you shouldn't get a prompt if you pass the `/c` argument but it does inside the mingw bash but not when called from a native windows shell. Thanks in advance for your help.

**Comment by atomicwrites** [comment]
I just found that I can call VBoxManage as `/c/Program\ Files/Oracle/VirtualBox/VBoxManage.exe -v` and tried replacing `cmd.exe /d /s /c call VBoxManage.exe -v` with that and it seems to be working. Is there a reason why it was called through `cmd`?

**Comment by atomicwrites** [comment]
Actually that looked like it worked but when it gets to start the VM, the boot fails and looking at the settings for the VM it created it has no storage attached, memory is set to the minimum, and basically none of the settings applied.

**Comment by myspaghetti** [comment]
Hi! thanks for testing the script.

Currently no support is planned for Mingw32. `VBoxManage.exe` is not meant to work on a Unix environment, which is why the script calls it with `cmd.exe`. Cygwin has trouble passing arguments to `VBoxManage.exe` and Minigw32 probably does, too.

**Comment by myspaghetti** [comment]
If you're looking for a minimal environment to run bash scripts on Windows, I think [WinPython dot](https://github.com/winpython/winpython/releases) provides a working Bash-like shell which, combined with packages from [scoop](https://scoop.sh/), is complete enough to run this script.

**Comment by atomicwrites** [comment]
Oh wow, somehow I read that Cygwin was supported and in my mind thought mingw32 which I already had installed. In the immortal words of Adam "Well there's your problem." I see WSL is supported, would you recommend that? I was planing on installing it anyways. Thanks for the help.
