### ISSUE TITLE
DMG2IMG - Compiler error on openSSL structures risolved when recompiled from source code

### ISSUE THREAD

**Issue by neo7BF** [myspaghetti/macos-virtualbox#341]
I have installed DMG2IMG compiling from source code. Doing this I had to upgrade file vfdecrypt.c because the istanziation structure of openSSL 1.1.0 are changed. Where may I release this change for the community ?

**Comment by neo7BF** [comment]
I was referring to this point:
Press enter to continue, CTRL-C to exit
Can't find VBoxManage in PATH variable,
checking /mnt/c/Program Files/Oracle/VirtualBox/VBoxManage.exe
Found VBoxManage
Please install the package dmg2img. <------

Anyway, thanks for closing without even a help :(

**Comment by myspaghetti** [comment]
Sorry. This is an issue tracker for the script. If you want to update `vfdecrypt.c` you should contact the maintainers of that code.
