### ISSUE TITLE
bootint.sh: No such file or directory.

### ISSUE THREAD

**Issue by KibSquib48** [myspaghetti/macos-virtualbox#342]
When the script boots into the VM for the setup, it gets to the macos terminal and then says bootint.sh doesn't exist and does nothing. All it says to do is press ctrl c, which I did, but I have no idea what to do with the VM now. Am I supposed to start over?

**Comment by myspaghetti** [comment]
Hi, please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `macOS_troubleshoot.txt` file here.

**Comment by myspaghetti** [comment]
Closing until further information is provided.
