### ISSUE TITLE
Please consider downgrading the dependency on xxd v1.11 to v1.10

### ISSUE THREAD

**Issue by padresmurfa** [myspaghetti/macos-virtualbox#343]
xxd v1.10 seemed to have been preinstalled on my mac (Mojave).

I failed to hunt down v1.11 on any package managers however.

I ended up having to download and build it from source (which I found [here](https://github.com/ConorOG/xxd)), which is not necessarily particularly hard, but if required, it would be excellent to add instructions regarding this and fork the xxd code into myspaghetti/xxd.

p.s. truly amazing work, thanks for open-sourcing this!

**Comment by myspaghetti** [comment]
Thanks!

[Before switching to `xxd` the script used `od`](https://github.com/myspaghetti/macos-virtualbox/issues/261) and it's certainly possible to switch back. `od` is faster but the syntax is a bit less straightforward.

That said, the version of `xxd` that is bundled with Catalina is V1.11 despite reporting that its version number is V1.10. I'll add this information to the dependency error message.

**Comment by myspaghetti** [comment]
Explained which version of `xxd` is required better in [version 0.98.0](https://github.com/myspaghetti/macos-virtualbox/commit/3ee28be973f58fd3049e69219cd922154d3a087e)

**Comment by padresmurfa** [comment]
Awesome, thanks for the update!
