### ISSUE TITLE
Virtualbox is not using hardware-supported virtualization features. Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other Windows features that lock virtualization are turned off. Exiting.

### ISSUE THREAD

**Issue by martinrotter** [myspaghetti/macos-virtualbox#344]
I had uninstalled literally every possible thing, still getting the error, PC is highend i5 processor, all HW-based virtualization capabilities are there.

**Comment by Masamune3210** [comment]
Make sure Virtualization is enabled in all places in bios\efi, make sure Hyper-V, Windows Subsystem for Linux, Windows Sandbox, Windows Hypervisor Platform, and all Windows security settings involving virtualization are disabled. If that error is showing up it means something is still using Hyper-V or is using its own virtualization features that is locking the system

**Comment by martinrotter** [comment]
On my other PC, it all works, you can probably close, will be some fuck-up on my side.

**Comment by redstreet** [comment]
See #398 to disable WSL2 in case it is active.
