### ISSUE TITLE
"xxd" not checked for existence

### ISSUE THREAD

**Issue by martinrotter** [myspaghetti/macos-virtualbox#345]
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 508: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 512: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 512: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 512: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 512: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 514: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 514: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 518: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 518: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 518: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 518: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 523: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 523: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 530: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 530: xxd: příkaz nenalezen      
./macos-guest-virtualbox.sh: řádek 532: xxd: příkaz nenalezen      
                                                                   
stage: create_macos_installation_files_viso                        
Creating EFI startup script                                        
                                                                   
Creating VirtualBox 6 virtual ISO containing the                   
installation files from swcdn.apple.com

**Comment by martinrotter** [comment]
This results in ISO not mounting to VM and scripts fails horribly.

**Comment by myspaghetti** [comment]
Fixed in [version 0.98.1](https://github.com/myspaghetti/macos-virtualbox/commit/cb902fcf82427e0ec2b9fc681056bf7834263875)
