### ISSUE TITLE
"An error has occurred validating the installer data..."

### ISSUE THREAD

**Issue by hires** [myspaghetti/macos-virtualbox#360]
I am installing on Virtualbox 6.1.16 on Linux Mint 19.3 host. The installation boots into Virtualbox with the macOS installer terminal and says it's "Preparing to run macOS Installer..." and then gets to 77.8% and fails with the following message:

"An error has occurred validating the installer data. The download is either damaged or incomplete."

After deleting the temp files and trying again it completed the installation but won't boot. It says "Panic loop detected"

Any help would be appreciated!

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. Please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting text file here.

**Comment by DennisTsiang** [comment]
I get the same issue on both Mojave and Catalina. Happens on the last step inside the VirtualBox VM mac terminal. On Mojave it fails on 9.9%. I'll attach a copy of troubleshoot for Mojave
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5751511/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
@DennisTsiang the file `Mojave_InstallESDDmg.pkg` is corrupt (somewhere between the 3,000,001st byte and the 4,000,000th byte) so you will have to re-download that part or re-download all of the `InstallESDDmg.pkg` file. Here are the md5 sums of the macOS Mojave installer version `10.14.4.0.0.1552634279`:

```
ce2c02a6669dd02d830a97afc285ce17 *Mojave_BaseSystem.chunklist
b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
dbf6d95266beefc887a38c63a7df383a *Mojave_InstallESD.part00
1b5c60cd12a10eacb692f3d36f8046e7 *Mojave_InstallESD.part01
4a3613e31816afc5a750f0c461a54c99 *Mojave_InstallESD.part02
86e61d1dd0ed054e00d4d49ca5bd84f7 *Mojave_InstallESD.part03
e84ab943b9a57a11491ddff9483ac0b3 *Mojave_InstallESD.part04
1d9f2a2a3bbb9d88b15f0114aed56d7d *Mojave_InstallESD.part05
3ffc64e9a5fd3d1cb65314432c3b1c53 *Mojave_InstallESDDmg.pkg
c6ea60bdc05652f06141c284a86b4618 *Mojave_InstallInfo.plist
9ecb9bd94257dbd6eda65049750979c4 *Mojave_AppleDiagnostics.chunklist
46789046cc0a4377c2513cb53fbe00d1 *Mojave_AppleDiagnostics.dmg
```

**Comment by myspaghetti** [comment]
@DennisTsiang the file `Mojave_InstallESDDmg.pkg` is corrupt (somewhere between the 3,000,000,001st byte and the 4,000,000,000th byte) so you will have to re-download that part or re-download all of the `InstallESDDmg.pkg` file. Here are the md5 sums of the macOS Mojave installer version `10.14.4.0.0.1552634279`:

```
ce2c02a6669dd02d830a97afc285ce17 *Mojave_BaseSystem.chunklist
b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
dbf6d95266beefc887a38c63a7df383a *Mojave_InstallESD.part00
1b5c60cd12a10eacb692f3d36f8046e7 *Mojave_InstallESD.part01
4a3613e31816afc5a750f0c461a54c99 *Mojave_InstallESD.part02
86e61d1dd0ed054e00d4d49ca5bd84f7 *Mojave_InstallESD.part03
e84ab943b9a57a11491ddff9483ac0b3 *Mojave_InstallESD.part04
1d9f2a2a3bbb9d88b15f0114aed56d7d *Mojave_InstallESD.part05
3ffc64e9a5fd3d1cb65314432c3b1c53 *Mojave_InstallESDDmg.pkg
c6ea60bdc05652f06141c284a86b4618 *Mojave_InstallInfo.plist
9ecb9bd94257dbd6eda65049750979c4 *Mojave_AppleDiagnostics.chunklist
46789046cc0a4377c2513cb53fbe00d1 *Mojave_AppleDiagnostics.dmg
```

**Comment by DennisTsiang** [comment]
Does it not do a checksum test after downloading?

**Comment by myspaghetti** [comment]
[Nope](https://github.com/myspaghetti/macos-virtualbox/issues/321), sorry.

**Comment by hires** [comment]
Sorry for the late reply, but I ended up doing a manual install with some other instructions I found and got a working VM. So I wasn't able to provide the log file.

I like the completely automated way your script works though. My working install used an OS image downloaded on my mac. Maybe it would be possible to use those instead since I assume they would be undamaged if they come from the App Store.
