### ISSUE TITLE
Unable to install normally

### ISSUE THREAD

**Issue by deweke** [myspaghetti/macos-virtualbox#361]
![image](https://user-images.githubusercontent.com/13085059/103116870-ea087080-46a2-11eb-85dd-d033881e8e4c.png)

CPU：AMD Ryzen 5 4500U with Radeon Graphics Six nuclear
SYSTEM：Windows 10

**Comment by myspaghetti** [comment]
See the built-in documentation under `CPU profiles and CPUID settings`
