### ISSUE TITLE
Running the Script on Windows

### ISSUE THREAD

**Issue by higgy999** [myspaghetti/macos-virtualbox#362]
How would I run this script for Windows 10 like the description says? I have tried to use a git bash but it doesn't have the required libraries and I can't get them because the apt command doesn't exist in it. I tried to install VirtualBox in a Linux subsystem on Windows but that also didn't work.

**Comment by Masamune3210** [comment]
Cygwin

**Comment by myspaghetti** [comment]
>Dependencies

>GNU Bash ≥ 4.3, on Windows run through Cygwin or WSL - see NEM

**Comment by higgy999** [comment]
I should have read more closely or went into the closed issues. Sorry!
