### ISSUE TITLE
MacOS VM started but stay blocked in VirtualBox terminal 

### ISSUE THREAD

**Issue by vinzlac** [myspaghetti/macos-virtualbox#364]
Hi Jack,

I'm currently trying the script on a AMD RIZEN5/Window10/VirtualBob 6.1, and I'm facing the following problem

The script is running well, creating and launching the VM in VirtualBox and after a while is stopping with this log in windows terminal:

```
_Splitting the several-GB InstallESDDmg.pkg into 1GB parts because
VirtualBox hasn't implemented UDF/HFS VISO support yet and macOS
doesn't support ISO 9660 Level 3 with files larger than 2GB.
creating file 'Catalina_InstallESD.part00'
creating file 'Catalina_InstallESD.part01'
creating file 'Catalina_InstallESD.part02'
creating file 'Catalina_InstallESD.part03'
creating file 'Catalina_InstallESD.part04'
creating file 'Catalina_InstallESD.part05'
creating file 'Catalina_InstallESD.part06'
creating file 'Catalina_InstallESD.part07'

stage: create_nvram_files

stage: create_macos_installation_files_viso
Creating EFI startup script

Creating VirtualBox 6 virtual ISO containing the
installation files from swcdn.apple.com


stage: configure_vm

stage: populate_basesystem_virtual_disk
Catalina_BaseSystem.vdi bootstrap virtual disk image exists.

stage: create_bootable_installer_virtual_disk
Creating Catalina installation media virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: b8c80e13-ef1e-4616-b6bb-46be750f50ee

stage: populate_bootable_installer_virtual_disk

Creating VirtualBox 6 virtual ISO containing macOS Terminal script
for partitioning and populating the bootable installer virtual disk.


Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by




pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.

Until the script completes, please do not manually interact with
the virtual machine.

Press enter when the Language window is ready._

```

And in the VirtualBox VM Terminal there's this message that I've put in attachment

And I joined also the log of VirtualBox to complete the investigation

Averything seems to be suspended even if a click enter in the window terminal to continue the proc
![Screenshot-VirtualBox_macOS_29_12_2020_15_58_02 jpg](https://user-images.githubusercontent.com/7504182/103294423-236a1480-49f2-11eb-8432-3be63a63f36c.png)
[VBox log - macOS-2020-12-29-16-11-28.txt](https://github.com/myspaghetti/macos-virtualbox/files/5751171/VBox.log.-.macOS-2020-12-29-16-11-28.txt)

ess

Have you any idea ?

Thanks

Vincent

**Comment by myspaghetti** [comment]
Please see the section `CPU profiles and CPUID settings` in the documentation.

**Comment by vinzlac** [comment]
I saw the section CPU profiles and CPUID settings and I tried with these parameters:

- VBoxManage modifyvm "macOS" --cpu-profile host
- VBoxManage modifyvm "macOS" --cpuidremoveall

 But it still the same, suspended process

Am'I wrong ?

**Comment by Masamune3210** [comment]
Try other cpu profiles. Your host cpu is likely unsupported

**Comment by vinzlac** [comment]
OK but which profile I'm on Rizen 5 and I see only Intel profile ?

**Comment by dustymugs** [comment]
Just an FYI. I use a Ryzen 7 3700x and the following worked for my setup:

```
vboxmanage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "macOS" --cpuidremoveall
```

So there's hope. No guarantees though.

**Comment by vinzlac** [comment]
Thanks @dustymugs , now with the only paramater `vboxmanage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
` it's much better, it's booting with the installation of MacOS
But I'm facing to a new issue, the installation program can find only the locked `Catalina Base System` drive (with a size of 2Go) as available target, and so the installation can go further (without any available drive target)

Do you why ?

Thanks a lot :)
