### ISSUE TITLE
Error at the end of the installer

### ISSUE THREAD

**Issue by LennyLouis** [myspaghetti/macos-virtualbox#366]
Hi, when i try to install with the script the virtual machine everything works until the end of the script. At the end, i restart the virtual machine and i'm again in the MacOS Utilities menu. What should i do ?

![Capture d’écran de 2021-01-03 15-48-24](https://user-images.githubusercontent.com/63062296/103481409-280c3f80-4ddb-11eb-8417-71295f6d77e4.png)
![Capture d’écran de 2021-01-03 16-08-28](https://user-images.githubusercontent.com/63062296/103481899-f183f400-4ddd-11eb-9177-c92e7a9b9f68.png)

**Comment by myspaghetti** [comment]
It appears you didn't follow the instructions on the script and wait for the specified state before pressing enter.

**Comment by ManuelFte** [comment]
Got this issue as well. After the OS had been installed successfully and I was already on the macOS desktop, the VM suddenly crashed, and when I restarted it, I was sent to macOS Utilities. I just had to go to "Startup Disk" in the Apple menu and pick the correct disk (the one **not** including "Base System").

**Comment by LennyLouis** [comment]
Maybe you should try to unmount the virtual disk where there is macos utilities to force your virtual machine to boot on macos directly

**Comment by organicdeveloper-net** [comment]
HELLO SO EXCITING TO GET A REAL REPLY
I have an offer f THAT’S UNIQUE AND DIFFERENT   or anybody that’s interested
IF YOU WOULD LIKE TO DISCUSS MAC OS OR SHARE PERSON EXPERIENCES OR GO INTO DEEPER DETAL ON VIRTUAL BOX
IM YOUR GIRL 😊🎉🎉🎈🎈🎈🎀🎀🎀🎀🎀🎀🎀🎀🥽🧶🎡🎡🎄


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
