### ISSUE TITLE
Getting iMessage to Work

### ISSUE THREAD

**Issue by doritobob269** [myspaghetti/macos-virtualbox#367]
I saw: [this](https://github.com/myspaghetti/macos-virtualbox/issues/163) but just to be clear, do I have to use values found on a physical mac or is there a way to get iMessage and other applications to work without values found from a "genuine Mac"?

**Comment by gprsnlty** [comment]
this is from the Documentation.
The following commented commands, when executed on a genuine Mac,
may provide the values for NVRAM and EFI parameters required by iCloud,
iMessage, and other connected Apple applications.
Parameters taken from a genuine Mac may result in a "Call customer support"
message if they do not match the genuine Mac exactly.
**Non-genuine yet genuine-like parameters usually work**.

**Comment by doritobob269** [comment]
> this is from the Documentation.
> The following commented commands, when executed on a genuine Mac,
> may provide the values for NVRAM and EFI parameters required by iCloud,
> iMessage, and other connected Apple applications.
> Parameters taken from a genuine Mac may result in a "Call customer support"
> message if they do not match the genuine Mac exactly.
> **Non-genuine yet genuine-like parameters usually work**.

I did see this. I don't know what genuine-like parameters would look like. For instance, I don't know how many characters are in `Hardware UUID` nor do I know what an example set looks like. Do you or does anyone have genuine-like parameters I could use that are not directly from a genuine Mac, but could anyone provide values that are similar enough to a genuine Mac's values that would allow me to use such Apple ID services like iMessage and iCloud?

**Comment by myspaghetti** [comment]
No support is offered for getting non-genuine values. There are plenty of sites on the internet that explain how to generate [Mac PlatformInfo](https://www.google.com/search?hl=en&q=Mac+PlatformInfo) but this is not one of them.

**Comment by doritobob269** [comment]
@myspaghetti Gotcha, Thank you
