### ISSUE TITLE
Hardware-Supported Virtualization Detection Issue

### ISSUE THREAD

**Issue by jordanm82** [myspaghetti/macos-virtualbox#370]
All Hardware Supported Virtualization features are turned off and still receiving the error message that something is locking virtualization. Rebooted, checked all features again to be sure, same outcome.

Troublehoot.txt is attached as well as screenshot of Windows Features, memory integrity protection is also turned off.
![image](https://user-images.githubusercontent.com/12875420/103697399-806f4880-4f65-11eb-8c9c-ce145e95a5b9.png)

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/5772523/macOS_troubleshoot.txt)

**Comment by Masamune3210** [comment]
Virtual Machine Platform might be locking it? not sure though

**Comment by jordanm82** [comment]
> Virtual Machine Platform might be locking it? not sure though

I'll give it a shot.

**Comment by jordanm82** [comment]
> > Virtual Machine Platform might be locking it? not sure though
> 
> I'll give it a shot.

Problem remains with "Virtual Machine Platform" feature disabled as well.

**Comment by myspaghetti** [comment]
There are many Windows features and software that block access to VT-x/AMD-V. Check for memory integrity protection or core isolation settings, Device Guard settings, and other installed software or enabled features that may block VT-x/AMD-V.

**Comment by ecate1** [comment]
> > > Virtual Machine Platform might be locking it? not sure though
> > 
> > 
> > I'll give it a shot.
> 
> Problem remains with "Virtual Machine Platform" feature disabled as well.

Try to see if the "hypervisorlaunchtype" parameter is Auto if so put it to off (by administrator bcdedit /set hypervisorlaunchtype off) and restart Windows. I have noticed this problem I use Hyper-V and wsl2, and I can't get the mac os to work with wsl2. @myspaghetti would it be possible to install mac on Hyper-V instead of VirtualBox?

**Comment by myspaghetti** [comment]
>would it be possible to install mac on Hyper-V instead of VirtualBox?

Not at the moment. VirtualBox 6.1.16 still has memory corruption issues on macOS guests under Hyper-V.

If you're really adamant about using Hyper-V you can [enable nested virtualization under WSL2.](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/)

**Comment by ecate1** [comment]
> > would it be possible to install mac on Hyper-V instead of VirtualBox?
> 
> Not at the moment. VirtualBox 6.1.16 still has memory corruption issues on macOS guests under Hyper-V.
> 
> If you're really adamant about using Hyper-V you can [enable nested virtualization under WSL2.](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/)

It seems a bit complicated, but the guide is well detailed, I'll try, thanks.

**Comment by myspaghetti** [comment]
Closing until further details are provided.

**Comment by neolectron** [comment]
Just logging here in case people are still struggling with this (as I just did for several hours).

I had a network bridged connection between my ethernet card and the Hyper-V one.
I had to completely delete the bridge, and kill the `HV Host Service`.

Then I could continue the script normally.

**Comment by piyush1104** [comment]
I was using wsl2 which was giving me the same problem. Switching to wsl1 and turning off "Virtual Machine Platform" feature worked for me.
