### ISSUE TITLE
Big Sur 11.1 crashing after upgrade

### ISSUE THREAD

**Issue by newedgex** [myspaghetti/macos-virtualbox#373]
I setup Catalina with the script where the system works as expected, then I upgrade through the software update and the first reboot works fine (where you set up some agreements on analytics and stuff).
However If I reboot the system again it will end up in a reboot loop and keeps crashing.
I'm using virtualbox 6.1.16-4 although I don't think this has anything to do with virtualbox.

This is always reproducible especially now with the 11.1 update.

**Comment by tcab** [comment]
Upgrading Big Sur from `11` to `11.1`  also crashed my virtualbox mac system on reboot - had to restore from backup and stay on `11` for now.

**Comment by myspaghetti** [comment]
Thanks, I'll mention in the readme that 11.1 is not supported.

**Comment by startergo** [comment]
Can someone post the boot log? You can actually record video inside VirtualBox.

**Comment by Beurt** [comment]
I tried to update a fresh VM (Catalina, default config of `macos-virtualbox`) to Big Sur 11.1. And it worked perfectly (its a a very slow process). Did you guys tried with a fresh VM?

**Comment by karmadice** [comment]
@Beurt I too tried with fresh VM on 2 computers, on first computer it worked. On second computer, it did all the process to upgrade, but it reboots to Catalina.

**Comment by myspaghetti** [comment]
Closing as it seems that the upgrade *can* work from a clean install, and failures are sporadic.
