### ISSUE TITLE
How do you use this program?

### ISSUE THREAD

**Issue by Mrcoolawesome** [myspaghetti/macos-virtualbox#377]
Title says it all, I understand if this seems like a stupid question and don't reply if you don't want to. I got as far as opening the program in Cygwin but when it asks me to press enter the second time it just closes itself and does nothing more after I press enter. Am I missing a step?

**Comment by matton2** [comment]
Instead of clicking to run, open a terminal window, navigate to the dir, and run with ./macos-guest-virtualbox.sh

**Comment by Mrcoolawesome** [comment]
And by terminal window you mean the Cygwin window right? Also I'm not familiar with how to navigate to the dir in the Cygwin window. I also completely understand if you don't wanna describe to me how to do this because this seems like basic stuff.

**Comment by matton2** [comment]
That is correct....you can use `cd` and `../` to navigate around your C drive.  I have not used Cygwin before but it may be possible to right click and launch a terminal window right in the folder where the script is and then run `./macos-guest-virtualbox.sh`

**Comment by Mrcoolawesome** [comment]
okay I got it to run but now it says that I need to make sure that packages are installed

**Comment by matton2** [comment]
Cool.  The script is really well written so it should tell you the packages you need and then a quick google search should provide the instructions for installing on windows.

**Comment by Mrcoolawesome** [comment]
Alright. Thank you very much this was extremely helpful.

**Comment by joey-lg** [comment]
I wanted to install this on windows 10, however when i downloaded everything, it says i dont have them

**Comment by myspaghetti** [comment]
Using the script requires a moderate familiarity with a Linux/Unix command line interface and package manager. If you're running the script on Cygwin, install the dependencies using [cygwin setup](https://cygwin.com/install.html), except `dmg2img` which is downloaded automatically. If you're running the script on WSL1, use `apt` or `yum` or the package manager installed on the WSL1 distro.

Sometimes a moderate familiarity with the `PATH` variable is required, if VirtualBox is not installed in the default path, or if some incompatible executable is found in the `PATH` paths earlier than the required executable.

No support is offered for troubleshooting system settings.
