### ISSUE TITLE
Unable to establish SSL connection to swscan.apple.com

### ISSUE THREAD

**Issue by nikkilocke** [myspaghetti/macos-virtualbox#378]
Any suggestions why this may be happening? On a brand new installation of cygwin.
```
Downloading Apple macOS Catalina software update catalog
--11:38:34--  https://swscan.apple.com/content/catalogs/others/index-10.15-10.14
-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.suc
atalog
           => `Catalina_sucatalog'
Resolving swscan.apple.com... done.
Connecting to swscan.apple.com[2.19.60.18]:443... connected.

Unable to establish SSL connection.

Unable to establish SSL connection.
/dev/null: No such file or directory

Couldn't download the Apple software update catalog.
Exiting.
```

**Comment by myspaghetti** [comment]
It's likely that the version of `wget` is trying to use a version of SSL that is too high or too low for the website it's trying to access.

Try adding `--secure-protocol=TLSv1` to the variable `wgetargs` in line 207 (or 209)

```
if [[ "$(wget --version 2>/dev/null | head -n 1)" =~ ${regex} ]]; then
    wgetargs="-secure-protocol=TLSv1 --quiet --continue --show-progress --timeout=60"  # pretty
else
    wgetargs="-secure-protocol=TLSv1 --continue"  # ugly
fi
```

**Comment by myspaghetti** [comment]
There's a log file called `Catalina_wget.log` that should hopefully tell you what went wrong with `wget`.

**Comment by nikkilocke** [comment]
The wget it was using does not support that parameter.

So I used the cygwin setup program to install a more recent version of wget, and it downloads the files OK now (without the extra parameter).

Can I heap praise on you for such a very prompt response - absolutely marvellous.

**Comment by Drakonas** [comment]
> It's likely that the version of `wget` is trying to use a version of SSL that is too high or too low for the website it's trying to access.
> 
> Try adding `--secure-protocol=TLSv1` to the variable `wgetargs` in line 207 (or 209)
> 
> ```
> if [[ "$(wget --version 2>/dev/null | head -n 1)" =~ ${regex} ]]; then
>     wgetargs="-secure-protocol=TLSv1 --quiet --continue --show-progress --timeout=60"  # pretty
> else
>     wgetargs="-secure-protocol=TLSv1 --continue"  # ugly
> fi
> ```

Just an FYI that this worked for me when I had the issue, even though I had the latest wget as of writing (1.21.3).
