### ISSUE TITLE
How to set up multiple display resolutions to choose from when MacOS is running

### ISSUE THREAD

**Issue by troywweber7** [myspaghetti/macos-virtualbox#379]
I have a 4k monitor and a 1080p primary display on my computer. I'm able to run the command `VBoxManage setextradata "macOS" "VBoxInternal2/EfiGraphicsResolution" "${resolution}"` to change between the resolutions I need, but I was wondering if there is a way to set up both resolutions so that when I'm booted into MacOS and I go to the display settings and select scaled, I can see multiple resolutions to switch between. It's not a huge issue, but rather a quality of life question. If I'm working on my 4k and then move my MacOS VM to my primary display, it would be nice to scale to a lower resolution and not have to use stretch mode (which becomes difficult to read on a 1080p).

If anyone has information on how to do this, I greatly appreciate it. Or if someone knows that there is definitively no way to achieve this, then I suppose the issue can be closed then as well.

**Comment by myspaghetti** [comment]
You have to install [OpenCore](https://github.com/acidanthera/OpenCorePkg/releases) and [inject an EDID](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#edid). No support is offered for OpenCore.

**Comment by troywweber7** [comment]
Ahh, maybe I'll take a look in that direction, then. Thanks for pointing me in the right direction.
