### ISSUE TITLE
check_default_virtual_machine() will always fail

### ISSUE THREAD

**Issue by wwebers** [myspaghetti/macos-virtualbox#380]
I tried the script under Ubuntu and the stage "**check_default_virtual_machine()**" will always fail as the preceding stage "**create_vm()**" only creates the VM config, but without any drive. Thus the start of the VM will always fail.

**Comment by myspaghetti** [comment]
A VM can start without any drives, and in fact the script explicitly relies on the default VM starting without any drives.

Check the VM logs (`VBoxManage showvminfo "${vm_name}" --log 0`) to see what specifically keeps your VM from starting.
