### ISSUE TITLE
Need some help in setting up values in the installer script

### ISSUE THREAD

**Issue by g33kyshivam** [myspaghetti/macos-virtualbox#381]
I asked my friend to give genuine values from a real mac from the commands mentioned in the script. I have filled out most of the stuff just need some clarification on some of it.

```
DmiBIOSVersion="string:MBP7.89"      # Boot ROM Version
DmiOEMVBoxVer="string:1"             # Apple ROM Info - left of the first dot
DmiOEMVBoxRev="string:.23.45.6"      # Apple ROM Info - first dot and onward
```
When I execute the command on the genuine mac ```system_profiler SPHardwareDataType```
The output is sort of for this particular sections is like ( have changed the values but the format and data type is same
```
       Boot ROM Version: 123.2.3.4.5
      SMC Version (system): 1.32f4
```
So what should the final config look like, I'm confused about the string part, Also there is no BIOS version as such for the above command output so I'm guessing it has to be filled via these two values?

**Comment by myspaghetti** [comment]
Some new Macs don't output the Apple ROM Info version so you can leave the variables the way they are or delete the lines entirely. As for the Boot ROM Version, if the value is `123.2.3.4.5` then set the variable as follows:

```
DmiBIOSVersion="string:123.2.3.4.5"
```

If you want to fully emulate a Mac with SMC and so forth you'll need [OpenCore](https://github.com/acidanthera/OpenCorePkg) for which no support is offered by me, but it's great and I recommend it. If you just want to use iMessage and iCloud the variables set in the script are enough.

**Comment by g33kyshivam** [comment]
@myspaghetti Thanks for the quick reply. Actually, I just want to have xcode and most importantly USB support (I know there is no guaranteed support but I will try to see if it works)

**Comment by myspaghetti** [comment]
Oh well you don't need to customize any of the settings for Xcode. The built-in USB passthrough doesn't work for most people, but USB over IP seems to do the trick.

**Comment by g33kyshivam** [comment]
@myspaghetti Is there any blog/tool which you can share for the USB over IP stuff. That would be a great help.

**Comment by myspaghetti** [comment]
Sorry, that's a lot of support for third-party software that I don't want to offer. The most user-friendly solution seems to be the [VirtualHere](https://www.virtualhere.com/home) proprietary software. It supports up to one device on the free trial mode.
