### ISSUE TITLE
support for MinGW/MSYS2

### ISSUE THREAD

**Issue by efa** [myspaghetti/macos-virtualbox#384]
hi,
can you support
https://www.msys2.org/
?

It is quite lighter than Cygwin, but has the necessary dependancy basic packages.
$ pacman -S coreutils wget gzip unzip
$ macos-guest-virtualbox.sh
I tryed to launch the shell, both in MSYS2 and in MinGW, but it is stuck immediately.
I will try to debug what happen and report here

**Comment by myspaghetti** [comment]
There are some [subtle differences](https://github.com/myspaghetti/macos-virtualbox/pull/347) between MSYS2 and Cygwin which make the script incompatible.

While MSYS2 *is* a Unix environment derived from Cygwin, the [project goals](https://www.msys2.org/wiki/How-does-MSYS2-differ-from-Cygwin/) of MSYS2 just happen to provide a Unix environment on their way to build native Windows software.

I'm willing to accept pull requests that make the script work on MSYS2 but only Cygwin is officially supported.

**Comment by efa** [comment]
I can confirm the script work with https://github.com/myspaghetti/macos-virtualbox/pull/347/commits/779de6380959e2dbb22f7687d9af5e876b5d6349
Opened an Issue to MSYS2 shell for the hang that require no spaces between windows options
