### ISSUE TITLE
VM won't start if running headless

### ISSUE THREAD

**Issue by redfive2012** [myspaghetti/macos-virtualbox#386]
I was getting errors at the very beginning of executing the script, trying to install a Catalina guest VM. It would create the VM and attempt to start it the first time, but it would immediately fail. Running the start command manually indicated a "signal 6" error, which led me to a post on the VirtualBox forums. Someone else was getting a signal 6 error after upgrading their VBox _host_ to Catalina (I'm running an Ubuntu 20.04LTS host). They solved it by changing their startvm command to add "--type headless". I added the same option to all of the lines in the script which contained startvm, and it is now pulling down and generating the Catalina install medium.

**Comment by myspaghetti** [comment]
The script is not designed to run in headless mode.
