### ISSUE TITLE
Video Playback

### ISSUE THREAD

**Issue by sethjt33** [myspaghetti/macos-virtualbox#387]
I can't play any type of video file in my installation, does anyone have that same problem or know a fix? Quicktime wont even open a .mov file.  VLC will try and play a video but it crashes the whole system when it does.  Any help would be appreciated.

**Comment by myspaghetti** [comment]
One way to improve graphics performance is to install the [VMWare graphics drivers](https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.1.0/17195230/core/). Another way is to load the virtual disk image in a better virtualization client, like KVM or VMWare.

The script uses VirtualBox because it's cross-platform and widely available, but for actually running a virtual machine it's recommended that you use KVM with GPU passthrough.

**Comment by sethjt33** [comment]
I really only use this install for a iMessage server so I don't need much.  I am really trying to troubleshoot a problem with iMessage not sending mp4 videos.  I thought it might be related to MacOS not playing any kind of video.  So let me ask you my real question. Do you know why iMessage on this MacOS install wont send any videos except videos shot on iphones.  For example, I can take a 40Mb video shot on a iPhone and send it just fine, but if I take a 40Mb mp4 video shot on another device and try and send it with iMessage it will fail every time. This only relates to the iMessage on this installation of MacOS.  I can take those same two videos and download them to a iphone and send them via iMessage just fine.  Any ideas?

**Comment by ImNotRice** [comment]
> Another way is to load the virtual disk image in a better virtualization client, like KVM or VMWare.

How would one load the virtual disk image in VMWare?

**Comment by myspaghetti** [comment]
Convert it to VMDK or another compatible virtual disk image format, then boot. VMWare requires no special configuration for macOS. There are tutorials for setting NVRAM and EFI values on VMWare if you want iMessage etc to work. On the other hand (and you didn't ask but I'm gonna mention it anyway) if you want to boot the disk image on KVM you need to install OpenCore first. There are tutorials for that too, the Proxmox macOS tutorials are particularly well-documented. This is *far* more involved than VMWare but it's open-source and the performance is better.
