### ISSUE TITLE
Documentation missing essential part

### ISSUE THREAD

**Issue by epogenesis** [myspaghetti/macos-virtualbox#391]
Hey myspaghetti,
Firstly, this script is miraculous. Truly. You cannot imagine how many hours I wasted to not get MacOS running before.
The awe this script induced, only raised one issue: While I cannot give much, where do I drop a couple of bucks. Maybe my teensy donation won't help much, but I think there might be one or two guys and gals whom you've helped equally and could spare a dollar or five.

**Comment by myspaghetti** [comment]
Thank you, your sentiment is touching.

Thankfully I'm doing very well and this script does not require additional funding. Here are two great causes that require additional funding right now:

* Health! [You can give £1 to UNICEF for protecting health workers from Coronavirus](https://www.unicef.org.uk/donate/coronavirus/) 
* Privacy! [You can give $3 to Signal for protecting social networking privacy](https://signal.org/donate/)

Thanks for making the world a better place for everybody!

**Comment by epogenesis** [comment]
My sincere respect. As per your advice, I instead donated the funds to help with the distribution of the vaccines. Chapeau and thanks once more

**Comment by jarthod** [comment]
Can't agree more, thanks for this awesome script! (worked perfectly on my Ubuntu 20.10)
And I also wanted to donate something because it's not this often we see this level of quality so as you suggested I donated to a charity instead ;)
Thanks!
