### ISSUE TITLE
Cant install needed dependencies

### ISSUE THREAD

**Issue by studentinneed** [myspaghetti/macos-virtualbox#392]
hi, so im on windows 10 trying to install macOS in my virtualbox. i downloaded cygdrive and was able to download everything else needed i think. however, im not able to find safe downloads for xxd or dmg2img. 

i tried running the script on cygdrive on my windows 10 computer as mentioned above and it tells me "Please make sure a version of xxd which supports the -e option is installed. The -e option should be listed when executing   xxd --help. The package vim-common-8 provides a compatible version on most modern distros." xxd --help just told me command not found. 

i cant find vim-common-8. i have the latest version of vim on my computer but it doesnt work. i was unsure how to proceed because it wont let me without those dependencies.

i am using a windows 10 computer.

**Comment by myspaghetti** [comment]
Cygwin has a separate `xxd` package that you can install by itself, or you can install `vim-common` for which `xxd` is a dependency.

`dmg2img` is not available on Cygwin so the script downloads it automatically from the author's website (unfortunately using an unsecure connection)
