### ISSUE TITLE
Partitioning

### ISSUE THREAD

**Issue by Gokux23** [myspaghetti/macos-virtualbox#394]
![Partitioning](https://user-images.githubusercontent.com/47430258/105660938-2abdfa00-5e9a-11eb-8b6e-3ce0cc9fb54e.PNG)
The script has been like this for a couple hours now. I am not sure if it just stopped working or I have to run the script again. I am on windows 10.

**Comment by myspaghetti** [comment]
See [known issues](https://github.com/myspaghetti/macos-virtualbox/releases/tag/0.98.2)
