### ISSUE TITLE
Storage Size

### ISSUE THREAD

**Issue by Gokux23** [myspaghetti/macos-virtualbox#395]
![StorageSize](https://user-images.githubusercontent.com/47430258/105688155-41c71100-5ec7-11eb-8a8b-52d644571dfa.PNG)

What would be the command to enter when it asks me to increase the virtual disk image size through VBoxManage, that I would enter on my windows cmd correct? Also, when it says "in terminal in the virtual machine", does that mean the macOS I am currently on?

**Comment by myspaghetti** [comment]
For modifying the VDI on the host see [`VBoxManage modifymedium --resize`](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifymedium)

After you modify the VDI, start the virtual machine guest, start the application Terminal in the virtual machine guest, and enter the commands as specified in the documentation.
