### ISSUE TITLE
Stuck in the UEFI Interactive Shell

### ISSUE THREAD

**Issue by helloplayer1** [myspaghetti/macos-virtualbox#397]
After successfully using your tool to set up a virtual machine, I am now stuck at the UEFI Interactive Shell and do not know what to do.
![image](https://user-images.githubusercontent.com/32032467/106268607-a4077500-622b-11eb-85f8-9f7c95d8c632.png)
I have looked up some information about this problem in general, but a solution I have read often does not seem to work for me [Link](https://superuser.com/questions/1235970/stuck-on-uefi-interactive-shell-with-mac-os-x-high-sierra-vm) 

When I try the Boot from File option, I only have one entry there and in it is no file to select:
![image](https://user-images.githubusercontent.com/32032467/106268955-1bd59f80-622c-11eb-9be2-1f9bcacdadd4.png)

Is there any way I can fix this? I was quite happy when the script did run through successfully, but that it does not work no is pretty disappointing :(

**Comment by myspaghetti** [comment]
Assuming `FS0:` is the macOS root partition, you can boot with the following command:
```
fs0:\System\Library\CoreServices\boot.efi
```
If it's not there then perhaps the file system is corrupt.

**Comment by helloplayer1** [comment]
> Assuming `FS0:` is the macOS root partition, you can boot with the following command:
> 
> ```
> fs0:\System\Library\CoreServices\boot.efi
> ```
> 
> If it's not there then perhaps the file system is corrupt.

I think fs0 is empty, doing "cd" while in fs0 does not show anything. As far as I have seen the whole script did run successfully.  What exactly should have happened at the end of the process? I only saw 2 terminal windows and shut down the vm. Was this wrong?

**Comment by myspaghetti** [comment]
The front terminal window should have displayed a percentage progress for the installation, and then a reboot message. Upon reboot the installer continues, then reboots, then the macOS post-install setup process begins.

**Comment by helloplayer1** [comment]
Thanks, it is working now. I guess I must have overread something and thought I just need to reboot. 😄
