### ISSUE TITLE
Dealing with WSL2

### ISSUE THREAD

**Issue by redstreet** [myspaghetti/macos-virtualbox#398]
May I start by saying: thank you for creating this awesome script and sharing it! It's well written, documented, and saves a ton of time!

For WSL2 users, virtualization won't work because WSL2 uses Hyper-V.  The script correctly fails with:
```
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
```
To be more helpful, one option is to mention this in the documentation or in the README.md:

WSL2 users cannot use virtualization as long as WSL2 is enabled. To temporarily disable WSL2, issue this commands in an elevated command prompt.
`bcdedit /set hypervisorlaunchtype off` + reboot --> disables WSL2, allows you to run MacOS on your VirtualBox
`bcdedit /set hypervisorlaunchtype auto` + reboot --> enables WSL2, can't run MacOS

References:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq
https://stackoverflow.com/questions/30496116/how-to-disable-hyper-v-in-command-line

**Comment by myspaghetti** [comment]
This works for WSL2 but not for Device Guard or memory integrity protection. When there's more than one use case with the same error message, I'd rather not point to one solution unless the other cases are extremely rare. I believe memory integrity protection and Device Guard and possibly other virtualization-based security measures are enabled by default on Windows 10, so every Windows 10 user with a new-ish processor will have to manually disable those. I'd rather the readme not get into the nitty-gritty of configuring the OS to work with VirtualBox.

I believe nested virtualization and a built-in Windows Xserver are coming to WSL2 in 2021, and when that happens the recommended method of running the script would be on WSL2, no more Cygwin and no more WSL1. More overhead but more convenient.

**Comment by redstreet** [comment]
Makes sense, and good to know about the expected updates. Agree, related info about OS configuration like this better belongs to a wiki if there is one. Anyway, it's in this thread now :).

Thanks again -- the script worked perfectly on two installs today!
