### ISSUE TITLE
EXITBS:START

### ISSUE THREAD

**Issue by 1333481** [myspaghetti/macos-virtualbox#399]
Im not sure how to fix it ive tried reading ducumentation and I dont understand

**Comment by myspaghetti** [comment]
1) Run the following commands [change "macOS" to match the name of your virtual machine] on the host to remove any VirtualBox CPU configuration from the virtual machine, then try to boot the virtual machine.
```
    VBoxManage modifyvm "macOS" --cpu-profile host
    VBoxManage modifyvm "macOS" --cpuidremoveall
```
2) Try one of the six preconfigured VirtualBox CPU profiles, then boot the virtual machine and see if it gets past the `EXITBS` or whatever boot stage it got stuck on. If it fails, try the another profile. The six preconfigured profiles are `  "Intel Xeon X5482 3.20GHz"  "Intel Core i7-2635QM"  "Intel Core i7-3960X" "Intel Core i5-3570"  "Intel Core i7-5600U"  "Intel Core i7-6700K"`
```
    VBoxManage modifyvm "macOS" --cpu-profile "one_of_the_six_profiles"
```
3) If none of the six profiles work, set the CPU profile to `host` (see stage 1) and then try to find or craft a [CPUID VirtualBox setting](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) that works for your CPU. No support is offered for crafting a matching CPUID.

**Comment by 1333481** [comment]
OMG thx so much
