### ISSUE TITLE
Shell Script Fails to Execute - Demands ZSH version 5.5 although 5.8 is installed

### ISSUE THREAD

**Issue by PB-Coaching** [myspaghetti/macos-virtualbox#401]
As the title states I tried to execute the script from the command line but it complains about my ZSH version. I have version 5.8 installed

**Comment by myspaghetti** [comment]
You should have received this error message:
```
macOS detected. Make sure the script is not executed with the default /bin/bash
which is version 3. Explicitly type the executable path, for example for zsh:
    /path/to/5.5/zsh macos-guest-virtualbox.sh
```

**Comment by PB-Coaching** [comment]
Thanks for the quick reply. Will try once home. Keep up with the great work
