### ISSUE TITLE
Virtual Machine hangs on LOG:EXITBS:START during boot.

### ISSUE THREAD

**Issue by ArangizoKish** [myspaghetti/macos-virtualbox#402]
[VBox.log](https://github.com/myspaghetti/macos-virtualbox/files/5946081/VBox.log)
I attached this log from the VM because it will probably help you find the problem. I am running Ubuntu 20.10 and this happens every time I run the script.

**Comment by myspaghetti** [comment]
Please see [known issues](https://github.com/myspaghetti/macos-virtualbox/releases/tag/0.98.2).

>Guest macOS boot process hangs on “LoadKernelFromStream”, “EndRandomSeed”, or "EXITBS" - see [documentation](https://github.com/myspaghetti/macos-virtualbox/blob/b177b0e760fe7dc9c3703590a2ce4ba2330661c1/README.md#Documentation) regarding VirtualBox CPU profiles and [CPUID settings](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport).
