### ISSUE TITLE
Stuck on first boot

### ISSUE THREAD

**Issue by DylanAkp** [myspaghetti/macos-virtualbox#403]
Hello
I've just started the script with ubuntu 20.04 and the VirtualBox is stuck on first boot
`EBI#LOG:EXITSBS:START] 2021-02-09T15:03:18`

**Comment by myspaghetti** [comment]
Please see [known issues](https://github.com/myspaghetti/macos-virtualbox/releases/tag/0.98.2).

>Guest macOS boot process hangs on “LoadKernelFromStream”, “EndRandomSeed”, or "EXITBS" - see [documentation](https://github.com/myspaghetti/macos-virtualbox/blob/b177b0e760fe7dc9c3703590a2ce4ba2330661c1/README.md#Documentation) regarding VirtualBox CPU profiles and [CPUID settings](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport).
