### ISSUE TITLE
Where do you put the CPUID commands?

### ISSUE THREAD

**Issue by TheBotlyNoob** [myspaghetti/macos-virtualbox#404]
I'm using an AMD Ryzen 9 3950x that is hanging on the boot screen. I found an answer with #364 but I have no idea where to put the CPUID commands, do you put it in the script or just into the command line?
Edit: I'm sorry if this is a stupid question I just can't find anything in the README or issues.

**Comment by myspaghetti** [comment]
You shut down the virtual machine, set the virtual machine's CPU profile or CPUID, power up the machine to see if it boots. If it boots, you shut it down and the script resume from the stage that failed. If it fails to boot, you test another CPU profile or CPUID and repeat.
