### ISSUE TITLE
Readme provides no way to compensate author.

### ISSUE THREAD

**Issue by nicovanrensburg** [myspaghetti/macos-virtualbox#406]
Seriously throw a PayPal in there. This thing is amazing.

**Comment by nicovanrensburg** [comment]
.

**Comment by myspaghetti** [comment]
Thanks!

Consider paying it forward!

* [You can give £1 to UNICEF for protecting health workers from Coronavirus](https://www.unicef.org.uk/donate/coronavirus/) 
* [You can give $3 to Signal for protecting social networking privacy](https://signal.org/donate/)

**Comment by cwegener** [comment]
Totally agree. I've been looking for a solution like this for many years.
You've done an absolutely fantastic job with this.
