### ISSUE TITLE
Cannot get initial system set up

### ISSUE THREAD

**Issue by joejackson3** [myspaghetti/macos-virtualbox#408]
Very impressed by how the script interacts with Virtualbox and pulls the original Catalina image from Apple. Thank you for writing this.

I get to the stage where it says "concatenating ... some files..." and "After shutdown, the initial base system will
be detached from the VM and released from VirtualBox. "
Then the VM restarts and I get a language selection dialogue again and the Recovery console. Going into disk utility, there are four partitions 
1. MacOS Base System (2GB, 1.33 GB used)
2. MacOS Base System (12.24 GB, 1.99 GB used)
3. Catal-files (8.24 GB, 8.24GB used)
4. bootinst-sh (362 KB, 362 KB used).

The root system in Terminal shows all usual system folders (Library, System, Volumes, bin, usr, var and so on).
Both MacOS Base Systems under /Volumes have all the system folders, but there are no Kernel files in /Library, neither in root or in the /Volumes/MacOS Base systems.
In the recovery, I'm unable to reinstall the OS, it says the "This copy of Install macOS Catalina app" is damaged.

Any idea where this went wrong?

PS: The problem is identical when trying this script with Virtualbox 6.1 running in Ubuntu 20.4 and Windows 10.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report.

You're not supposed to manually interact with the virtual machine. The script is not done at that stage and should be performing further stages.

**Comment by maderunner** [comment]
How long does the script take to run at this point? I'm having the same issue. It's been an hour on my end. 
I'm running this on VirtualBox 6.1 on a Mac Air (running Linux Mint as my main OS).

Thanks for all you do.

**Comment by myspaghetti** [comment]
I don't understand, aren't you getting a prompt? The script runs interactively unless you have tesseract installed.

**Comment by joejackson3** [comment]
Hi there. Thank you.
The bash had closed at the point where I had described - I think after it had been hanging at the concatenating stage for a long time. I'll try again and report back....

**Comment by myspaghetti** [comment]
Yes, run `./macos-guest-virtualbox.sh documentation` to see how to resume the script at specific stages.

Please run the script on an interactive prompt. If bash *closes* the script is not running on an interactive prompt.

**Comment by myspaghetti** [comment]
Added check that [the shell is interactive if tesseract is not installed](https://github.com/myspaghetti/macos-virtualbox/commit/b47fbd977e9d6103fb7113651839c22937d58af1)

**Comment by maderunner** [comment]
Worked great! Thanks for all your hard work, very helpful.

..now to figure out how to move this Virtual Box guest to an external drive..

**Comment by joejackson3** [comment]
Thank you. I got much further this time on Ubuntu (I failed on Windows 10 due to a Cygwin "fork access denied error").
Now I'm getting to this stage:
```
The second open Terminal in the virtual machine copies EFI and NVRAM files
to the target EFI system partition when the installer finishes preparing.

After the installer finishes preparing and the EFI and NVRAM files are copied,
macOS will install and boot up when booting the target disk.

```
The partitioning in one of the bash windows finishes within a few seconds.
Then I get this:
```

Please wait

For further information, such as applying EFI and NVRAM variables to enable
iMessage connectivity, see the documentation with the following command:

  ./macos-guest-virtualbox.sh documentation | less -R

That's it! Enjoy your virtual machine.
```
Nothing happens after that. The second bash window remains active, but there is no hard disk activity for at least one hour. The VM does not restart. I assume it's running the nvram.sh script - how long is that expected to run, and would it not generate hard disk activity?

**Comment by myspaghetti** [comment]
The NVRAM script takes less than a second to run. Did the installer not run?

**Comment by joejackson3** [comment]
Hello,
so the first terminal opens up with nvram.sh. Then a second terminal opens on top of that. It runs startosinstall.sh. This goes through the steps of partitioning and formatting and completes within a few seconds. If I bring the other Terminal into the foreground, it still hangs on the nvram.sh with no console output.
I assume from the lengthy printf command within nvram.sh it should put out a command making folders and mounting drives, but nothing is showing up on the console.

**Comment by myspaghetti** [comment]
@joejackson3 please run on the host `./macos-guest-virtualbox.sh troubleshoot` and attach the output `*_troubleshoot.txt` file here. If the first terminal does nothing then the installation files are probably corrupt. The troubleshooting log will hopefully show if they are.

**Comment by joejackson3** [comment]
Thank you! Here goes the troubleshoot.txt output.

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6002563/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
@joejackson3 congrats, you've stumped me! Everything is in order according to the log. I have no idea why `startosinstall.sh` fails!

`startosinstall.sh` executes the following commands:
```
background_pid="$(ps | grep '"'"' sh$'"'"' | cut -d '"'"' '"'"' -f 3)" && \
[[ "${background_pid}" =~ ^[0-9][0-9]*$ ]] && \
disks="$(diskutil list | grep -o "[0-9][^ ]* [GTP]B *disk[0-9]$")" && \
disks="$(echo "${disks}" | sed -e "s/\.[0-9] T/000.0 G/" -e "s/\.[0-9] P/000000.0 G/" | sort -gr | grep -o disk[0-9])" && \
disks=(${disks[@]}) && \
[ -n "${disks[0]}" ] && \
diskutil partitionDisk "/dev/${disks[0]}" 1 GPT APFS "'"${vm_name}"'" R && \
app_path="$(ls -d /Install*.app)" && \
cd "/${app_path}/Contents/Resources/" && \
./startosinstall --agreetolicense --pidtosignal ${background_pid} --rebootdelay 500 --volume "/Volumes/'"${vm_name}"'"' >> "${vm_name}_startosinstall.txt"
```

If the partitioning terminates successfully, then the installation process should be executed. Since the installation files on the host are not corrupt, I assume the installation files on the `Catalina_bootable_installer.vdi` disk image are not corrupt either. `startosinstall.sh` should successfully execute `./startosinstall --...`

Can you confirm that the front terminal (the one that executes `startosinstall.sh`) returns to the prompt at `Install macOS Catalina.app/Contents/Resources`?

**Comment by myspaghetti** [comment]
@joejackson3 congrats, you've stumped me! Everything is in order according to the log. I have no idea why `startosinstall.sh` fails!

`startosinstall.sh` executes the following commands:
```
background_pid="$(ps | grep ' sh$' | cut -d ' ' -f 3)" && \
[[ "${background_pid}" =~ ^[0-9][0-9]*$ ]] && \
disks="$(diskutil list | grep -o "[0-9][^ ]* [GTP]B *disk[0-9]$")" && \
disks="$(echo "${disks}" | sed -e "s/\.[0-9] T/000.0 G/" -e "s/\.[0-9] P/000000.0 G/" | sort -gr | grep -o disk[0-9])" && \
disks=(${disks[@]}) && \
[ -n "${disks[0]}" ] && \
diskutil partitionDisk "/dev/${disks[0]}" 1 GPT APFS "macOS" R && \
app_path="$(ls -d /Install*.app)" && \
cd "/${app_path}/Contents/Resources/" && \
./startosinstall --agreetolicense --pidtosignal ${background_pid} --rebootdelay 500 --volume "/Volumes/macOS"
```

If the partitioning terminates successfully, then the installation process should be executed. Since the installation files on the host are not corrupt, I assume the installation files on the `Catalina_bootable_installer.vdi` disk image are not corrupt either. `startosinstall.sh` should successfully execute `./startosinstall --...`

Can you confirm that the front terminal (the one that executes `startosinstall.sh`) returns to the prompt at `Install macOS Catalina.app/Contents/Resources`?

**Comment by joejackson3** [comment]
Good evening.
The front terminal running startosinstall.sh returns to prompt after "Finished partitioning etc...".
It is however in /private/var/root
I tried to run the last command "./startosinstall " manually. Copying and pasting the command yields an error about an extraneous option after --pidtosignal. If I remove the --pidtosignal option, the command executes without error but returns to prompt after a couple of seconds.

I also noticed that there is no output in the other terminal running nvram.sh (due to to the while true statement in the first line??). Should it not print the commands to console?

**Comment by myspaghetti** [comment]
If I had to guess, the installation files on the `Catalina_bootable_installer.vdi` volume are corrupt even though they're fine on the host. I'd delete the `vdi` files and re-run the script.

**Comment by joejackson3** [comment]
Deleted everything apart from the 7GB Calina package and re-ran the script, with same result.
Then I changed install option to HighSierra. Same behaviour until the end, with the exception of getting, in addition, the statement "By using the agreetolicence option ..." followed by Helper Tool Crashed.
Troubleshoot.txt attached.
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6014566/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
Sorry, no idea. The CPU is very old (540M) so I'm gonna chalk it up to that.

**Comment by joejackson3** [comment]
Thank you for trying hard anyway.
