### ISSUE TITLE
Cygwin error

### ISSUE THREAD

**Issue by cdbarry89** [myspaghetti/macos-virtualbox#409]
Hi,
Apologies but I am new and not sure if this is the correct forum to raise this so please point me in the right direction if necessary. I have freshly installed Cygwin and all the packages listed in the error below but the script still fails to execute.
Suggestions?
Thanks,
Conor

Please make sure the following packages are installed
and that they are of the version specified or newer:
coreutils 8.22   wget 1.14   gzip 1.5   unzip 6.0

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report.

The error message means the script executes the following commands and at least one of them fails:
```
gzip --help
unzip -hh
csplit --help # this checks for coreutils
wget --version
```
If you manually execute each of these commands in Cygwin/mintty/bash you'd see which one(s) fail(s). Then you'll have to install the appropriate package(s) through the Cygwin setup process.

**Comment by myspaghetti** [comment]
Closing until further info is provided.
