### ISSUE TITLE
Ryzen 5 3600 was not starting (solution)

### ISSUE THREAD

**Issue by tuxrevolt** [myspaghetti/macos-virtualbox#411]
Hello, 
I don't know where to put that information so I decided to write it here. 
Might be usefull to add this in the troubleshooting section.

I am using VirtualBox on Fedora 33. 
My CPU is a Ryzen 5 3600.

The vm creation went well but I was stuck at the exitBS thing.
So I opened a terminal and wrote this : 
VBoxManage modifyvm "nameofyourVM" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage modifyvm "nameofyourVM" --cpu-profile "Intel Core i7-6700K"

Then I started the VM and I went on the language selection window.

Hope this helps.
Have a nice day

**Comment by tuxrevolt** [comment]
To complete my solution, here is the modification you have to add to your bash script:
The fonction start at line 652 :

> function configure_vm() {
> print_dimly "stage: configure_vm"
> VBoxManage modifyvm "${vm_name}" --cpus "${cpu_count}" --memory "${memory_size}" \
>  --vram "${gpu_vram}" --pae on --boot1 none --boot2 none --boot3 none \
>  --boot4 none --firmware efi --rtcuseutc on --chipset ich9 ${extension_pack_usb3_support} \
>  --mouse usbtablet --keyboard usb --audiocontroller hda --audiocodec stac9221 **--cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff --cpu-profile "Intel Core i7-6700K"**

If you decide to keep your actual vm, just write the two lines I wrote on my original solution in a terminal. Then, read the script to see what has to be done (3 shell script to launch if my mind is good (I'm so tired haha).

If you don't want to find what has to be done, tweak the file and then launch it. Erase your not working macos vm and let the music play :).

Enjoy

**Comment by myspaghetti** [comment]
Please don't offer solutions without knowing what they do. The CPUID options override the CPU profile option. Use either or, not both.
