### ISSUE TITLE
How to ensure the uniqueness of the virtual machine?

### ISSUE THREAD

**Issue by NilsonC348** [myspaghetti/macos-virtualbox#414]
i have installed a virtual machine using the script,called the machine A below.

i want to create other machines by cloning from the machine A.
but i need to make sure that the virtual machines created by cloning are all different from each other .

that means i need to make sure that the uniqueness of the system and the hardware of these virtual machines.how can i deal with it? or machines created by cloning from the machine A are already uniq from each other.

hoping for help,
if it can use chinese for communication ,would be much better.

**Comment by myspaghetti** [comment]
macOS usually identifies the machine through [values stored in the NVRAM](https://github.com/erikberglund/AppleNVRAM/blob/df3514418a8b3782d252412961e8e40366b8303b/All/README.md) and the EFI. For example when logging into iCloud, macOS and the Apple servers verify the values provided in the script that are set in NVRAM and EFI.

When registering an iCloud account or using Apple services more extensively, more NVRAM and EFI values are checked than the script provides. See [the repository maintained by erikberglund](https://github.com/erikberglund/AppleNVRAM/blob/df3514418a8b3782d252412961e8e40366b8303b/All/README.md) for some idea about the NVRAM values.

Keep in mind that VirtualBox does not (and probably cannot) provide full SMC or any security chip emulation, so identification that requires these chips cannot be provided.
