### ISSUE TITLE
Add support for msys2

### ISSUE THREAD

**Issue by mulder999** [myspaghetti/macos-virtualbox#415]
Detection of VBoxManage is not working in msys2

**Comment by myspaghetti** [comment]
This is a [known issue](https://github.com/myspaghetti/macos-virtualbox/issues/384) and while it's trivial to edit the script to support MSYS2, the goal of MSYS2 is not really to provide a full Unix environment but a development environment, which makes this script a poor fit for MSYS2 or vice-versa.

By the way, when WSL2 built-in X server and nested virtualization arrive (sometime in 2021?) the script support for Cygwin will be deprecated.
