### ISSUE TITLE
Unable to find VBoxManage on Cygwin

### ISSUE THREAD

**Issue by siegfriedbe** [myspaghetti/macos-virtualbox#416]
Whenever i try to use the script it gives this error:

> Can't` find VBoxManage in PATH variable,
checking C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
Please make sure VirtualBox version 5.2 or higher is installed, and that
the path to the VBoxManage.exe executable is in the PATH variable, or assign
in the script the full path including the name of the executable to
the variable cmd_path_VBoxManage

the path to VBoxManage is on the PATH variable and its specified correctly on the cmd_path_VBoxManage variable
im using VirtualBox 6.1.18

**Comment by myspaghetti** [comment]
Thanks for the bug report.

What's the output of `cmd.exe /d /s /c call "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" -v`

**Comment by myspaghetti** [comment]
Thanks for the bug report.

What's the output of `cmd.exe /d /s /c call 'C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' -v`

**Comment by siegfriedbe** [comment]
without "%SYSTEMROOT%\System32" on the PATH variable: cmd.exe: 

> No such file or directory

with "%SYSTEMROOT%\System32" on PATH gave me: 

> /cygdrive/c/WINDOWS/System32/cmd.exe: /cygdrive/c/WINDOWS/System32/cmd.exe: cannot execute binary file

**Comment by siegfriedbe** [comment]
well, now it works, the problem was with my PATH variable.
thanks.

**Comment by KraynSG** [comment]
Hi, I have the same problem but I think it is because I had installed VirtualBox on my D: disc because I don't have space left in my C. How can I change the path to VBoxManage.exe please ?

**Comment by KraynSG** [comment]
Ok thanks

**Comment by KraynSG** [comment]
Sorry how can I open the modified file in Cygwin please ?

**Comment by myspaghetti** [comment]
If you don't have a text editor I suggest using `sed` which is installed on Cygwin by default. The command might look like:
```
sed macos-guest-virtualbox.sh -i -e 's/C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe/D:\\path\\to\\VBoxManage.exe/'
```
Mind the double slashes `\\` which are required because bash/sed interpret the slash as an escape character, so a single slash is written as `\\` on the command line.
