### ISSUE TITLE
Issues with Virtualbox image when attempting to boot into Recovery mode...

### ISSUE THREAD

**Issue by Irishtiger77** [myspaghetti/macos-virtualbox#420]
Setup:  Windows 10 20H2 (OS Build 19042.804) host on Intel i7, 16GB ram.  Virtualbox 6.1.18 r142142 (Qt5.6.2).  MacOS Catalina with 4 GB RAM, 1440x900 display setup, 100GB virtual hdd set up with your script.

Script executes beautifully, I am able to set up and log into Catalina just fine.  Can do most anything there.  The problem comes when I issue the following on the command line (I have no idea how to get into Recovery Mode any other way) to get into Recovery mode:

sudo nvram "recovery-boot-mode=unused"
sudo reboot

Unfortunately, after issuing this command, the log shows that the efi image is corrupt or something and it crashes, kernel panic, tries to reboot, rinse and repeat forever.  Can this scripted vm enter recovery mode?

**Comment by myspaghetti** [comment]
You can edit the NVRAM values from the EFI Internal Shell with the `dmpstore` command or others. No support is offered for editing the NVRAM in this way. Another option is to simply delete the `.nvram` file that is on the host operating system on the same directory as the `.vbox` file for the appropriate virtual machine. You will lose all NVRAM values but the machine should boot into the default macOS environment.
