### ISSUE TITLE
How To Access Terminal When The Step "Press enter when the Terminal command prompt is ready."?

### ISSUE THREAD

**Issue by cheznewa** [myspaghetti/macos-virtualbox#421]
I Can't Get Here And No Demo Video.

**Comment by cheznewa** [comment]
Why Tesseract?
I Not Found The Prompt In The Disk Utility And Win+T Not Work

**Comment by myspaghetti** [comment]
Tesseract performs optical character recognition which automates the installation process. If you don't want to install Tesseract you can manually follow the steps specified by the script. The script only requires that you press enter when the virtual machine is in a specific state. A default install requires pressing enter eight times, twice to review the script welcome message and configuration, and six times to advance from one GUI state to another.

Follow the instructions (pressing enter when the correct state is avaiable) carefully from start to finish and you should be through with it with eight presses of the Enter key.

**Comment by cheznewa** [comment]
I Installed It, But Is Very Open The Terminal At Disk Utility?

**Comment by cheznewa** [comment]
It's Auto, And OK The Terminal Prompt Is Outside The Disk Utility

I Closed If All Done ...

**Comment by cheznewa** [comment]
The Steps Is No Ignoed, When Auto, So, He Open Two Terminal And Execute.
![VirtualBox_macOS_10_03_2021_18_18_22](https://user-images.githubusercontent.com/61405797/110670532-c77bf300-81cd-11eb-9c8e-a744f8f75d94.png)

**Comment by fakheet** [comment]
I think I know what he's asking, I ran into the same issue: after setting the CPU mode I don't know how to resume the script on the "Press enter when the Terminal command prompt is ready" step so that it would continue the installation

**Comment by myspaghetti** [comment]
Oh I see. The script stages are specified when running `./macos-guest-virtualbox.sh documentation` and specific stages can be given as command-line options. For example `./macos-guest-virtualbox.sh populate_bootable_installer_virtual_disk create_target_virtual_disk populate_macos_target_disk`

**Comment by fakheet** [comment]
yeah, that was in the docs about resuming, it's just that from their names it's not very clear which of those are "that part where I wait for the language screen". I personally just re-did the install completely and successfully got my VM working, but a bit more simple naming could potentially be nice
