### ISSUE TITLE
MLB and ROM values are different from script values

### ISSUE THREAD

**Issue by gkip0** [myspaghetti/macos-virtualbox#422]
In the script, I set MLB and ROM values. When I finish the installation and check in the terminal of the virtual machine, the values of MLB and ROM are different from the values I set. What's wrong.

My installation environment is:

MacOS 10.15.7

VirtualBox 6.1.6 installing HighSierra

**Comment by myspaghetti** [comment]
The NVRAM values need to be loaded through the EFI Internal Shell. From the documentation:

>When resetting or powering up the VM, immediately press Esc when the VirtualBox logo appears. This boots into the EFI Internal Shell or the boot menu. If the boot menu appears, select "Boot Manager" and then "EFI Internal Shell" and then allow the startup.nsh script to execute automatically, applying the NVRAM variables before booting macOS.

If the NVRAM values are not applied, see the section "Changing the EFI and NVRAM parameters after installation" in the documentation, perhaps the script failed to copy the required to the EFI System Partition.

**Comment by gkip0** [comment]
Thank you so much. It worked！！！
