### ISSUE TITLE
Script never gets to the language window

### ISSUE THREAD

**Issue by Zeputee** [myspaghetti/macos-virtualbox#424]
Everything has gone fine so far without error, but the script says to press enter when the Language screen pops up, but virtual box is just stuck on the black screen with white text, the last message reads:

[eb|#log:exitbs:start]

**Comment by Zeputee** [comment]
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6173051/macOS_troubleshoot.txt)
 Here's the troubleshoot.txt file

**Comment by myspaghetti** [comment]
This is a known issue. Please see the "CPU profiles" section available through the [documentation command](https://github.com/myspaghetti/macos-virtualbox/blob/b177b0e760fe7dc9c3703590a2ce4ba2330661c1/README.md#Documentation).

**Comment by piyush1104** [comment]
What should I do once I change my CPU profiles and have booted successfully in the virtual machine with language window appeared. What stage should I start with? Should I do - `./macos-guest-virtualbox.sh populate_basesystem_virtual_disk and_all_subsequent_stages`  ?

**Comment by myspaghetti** [comment]
Generally speaking, `./macos-guest-virtualbox.sh [stage_that_was_aborted] and_all_subsequent_stages`
