### ISSUE TITLE
startosinstall.sh fails with "Helper Tool crashed....."

### ISSUE THREAD

**Issue by Gloobyy** [myspaghetti/macos-virtualbox#425]
![image](https://user-images.githubusercontent.com/81111374/111917846-7b943e00-8a58-11eb-8e11-7b14dc15d82a.png)
[macOSHighSierra_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6178187/macOSHighSierra_troubleshoot.txt)
[VBox.log](https://github.com/myspaghetti/macos-virtualbox/files/6178189/VBox.log)

**Comment by myspaghetti** [comment]
Thanks for the detailed report.

My first guess would be CPU incompatibility with the 2009 Xeon. The logs don't show any other issues. I'll rest the script with High Sierra again in a couple of days just to make sure it still works, and if it does I'll most likely chalk this one to an absent CPU instruction that macOS calls.

**Comment by myspaghetti** [comment]
Thanks for the detailed report.

My first guess would be CPU incompatibility with the 2009 Xeon. The logs don't show any other issues. I'll test the script with High Sierra again in a couple of days just to make sure it still works, and if it does I'll most likely chalk this one to an absent CPU instruction that macOS calls.

**Comment by Gloobyy** [comment]
could be right, i’ll have to try a different cpu profile when i get home.

**Comment by myspaghetti** [comment]
Closing for now.
