### ISSUE TITLE
How to transport MacOS BigSur VM from one computer to another one.

### ISSUE THREAD

**Issue by cgilles** [myspaghetti/macos-virtualbox#428]
Hi,

First i want to thanks developer from this project. I'm lead coordinator from digiKam open source photo manager,

https://www.digikam.org/

...and we use a MacOS BigSur 11.2.3 VM to build daily deployments of application PKG installer. The VM installation from scratch take around 8 hours to compile all dependencies with macports, and all work as expected.

VM installation and configuration : 

https://invent.kde.org/graphics/digikam/-/blob/master/project/bundles/CD/ContinuousDeploy.txt#L64

Macports install and dependencies : 

https://invent.kde.org/graphics/digikam/-/tree/master/project/bundles/macports

Recently i need to upgrade the computer to a more recent one with SSD to replace the HDD, and i need to transport the VM from older computer to new one. The host Linux OS and the VirtualBox still the same. Note : the MacOS VM disk is a fixed size (128 Gb), not a dynamic one as set by default in your script (i can provide a small PR for that). 

I tried the classic way virtualbox OVA. It do not work.
I tried to import the VM XML definitions with VBoxManage CLI tool and it do not work.

So i finally reinstall all from scratch. This take a while but all work as expected.

So my Q is how to transport the VM safety from one computer to another one.

Best regards

Gilles Caulier

**Comment by myspaghetti** [comment]
1. Create and configure a new VM: `./macos-guest-virtualbox.sh create_vm configure_vm`
2. From the command line or the GUI, attach the macOS disk image you want to use.
3. Optionally, copy the `.nvram` file from the previous VM's `.vbox` directory if desired (not required unless you're trying to connect to iCloud etc)
