### ISSUE TITLE
[Question] How to upgrade the VM using InstallESDmg.pkg ?

### ISSUE THREAD

**Issue by philphirn** [myspaghetti/macos-virtualbox#429]
I know this is a non-script question but I've seen people with good knowledge about macOS so just asking.

I'd first successfully installed High Sierra using this script on Virtual Box. Now I want it to upgrade to Catalina. I've downloaded all the files which are downloaded by this script. If I install using this script a fresh Installation is created. If I try to run `BaseSystem.dmg` it'll download the files again which I don't want to do as they're huge. And InstallESDmg.pkg will of course fail because it's unable to find the other required files which I've downloaded.

So my question is can I upgrade my VM using the downloaded files only ? If yes then how ?

**Comment by myspaghetti** [comment]
If you're patient you could study the script function `populate_bootable_installer_virtual_disk()` line-by-line and find out how it creates the `macOS__bootinst.txt` file, which is what you need. Here's what it does in a nutshell:

* Partitions a disk that's at least 12GB large as a GPT JHFS+ disk: `diskutil partitionDisk "/dev/disk9999" 1 GPT JHFS+ "Install" R`
* Restores `BaseSystem.dmg` onto the disk: `asr restore --source "/path/to/BaseSystem.dmg" --target /Volumes/Install --erase --noprompt`
* Creates the required directory structure: `mkdir /path/to/Install*.app/Contents/SharedSupport`
* Copies the required files, `*.chunklist` `*.plist` `*.dmg` (including the renamed `InstallESD.dmg`), to the `SharedSupport` directory
* Replaces the occurrence of `InstallESDDmg.pkg` with `InstallESD.dmg` in the plaintext file `InstallInfo.plist`
* Deletes a few extraneous lines for an unused file (the chunklist) listed in the plaintext file `InstallInfo.plist`

And then you have a bootable macOS installer.

**However** if you've already successfully downloaded the required files you can let the script perform these steps for you (simply abort after the bootable installer has been populated) or, if you don't mind re-downloading the files, you can download Catalina from the Apple App Store and run the installer from inside the VM.

**Comment by philphirn** [comment]
Ok thanks @myspaghetti .

Based on the above answer I've 2 more questions :
* How did the `InstallESDDmg.pkg` become InstallESD.dmg ? Using `xar` ? But I don't find `xar` as a dependency in script.
* Will the bootable installer created by script be able to upgrade my macOS VM without erasing data ?

And if possible can you show me how to skip the download part of script ? Because my version of the Catalina install files is little bit old. So will new ones will be downloaded ?

**Comment by myspaghetti** [comment]
* `InstallESDDmg.pkg` is simply renamed `InstallESD.dmg`, the files are identical
* Yes, the macOS bootable installer performs upgrades very well.
* You can run the script like so:

```
./macos-guest-virtualbox.sh prompt_delete_existing_vm create_vm configure_vm populate_basesystem_virtual_disk create_bootable_installer_virtual_disk populate_bootable_installer_virtual_disk
```

Make sure you edit the script variables at the top of the script so `vm_name` is *different* from the VM you want to keep so it doesn't delete it.

**Comment by philphirn** [comment]
@myspaghetti thank you so much.

One more thing the script is amazing.
I'll try all the steps you mentioned tomorrow (I don't have access to the system right now) and update here. 

Till then you can close this if you want.

**Comment by philphirn** [comment]
@myspaghetti got back from work. Tested the thing out.

At the first time I just copy pasted the command but this used to fail at the last stage saying that `Failed to attach viso` .

Then I realised you'd probably forgot to add the create_viso... (smth like that) argument which creates the viso file.

After running with the argument. The script fails at the population stage wherein it copies and reassembles InstallESD.dmg file. Then I realised (again 😅) that the part of the script which splits InstallESD did not ran at all . Now when I get back again I've to do this.

But one more thing , that splitting part is in the download part(function) which I don't want to run.

So should I run that manually or what should I do ?

**Comment by philphirn** [comment]
Ah thanks 👍.
No need to be sorry.

I did whatever was required including what you said then the final result is the image below.
Now the question is how can I use it to upgrade the VM ? And secondly the virtual disk on which high Sierra is installed is of smaller size which might not be enough for Catalina . So is there any fix for that ? 

![Final Result](https://user-images.githubusercontent.com/49480205/112667437-3cfcea00-8e83-11eb-9dcc-74b10117c034.png)

**Comment by myspaghetti** [comment]
"Reinstall macOS" will install Catalina, but the command-line installer is more reliable. You can increase the virtual disk image size as described in the documentation section "Storage size":

>The script by default assigns a target virtual disk storage size of 80GB, which is populated to about 25GB on the host on initial installation. After the installation is complete, the VDI storage size may be increased. First increase the virtual disk image size through VirtualBox Manager or VBoxManage, then in Terminal in the virtual machine execute the following command:
```
    sudo diskutil repairDisk disk0
```
>After it completes, open Disk Utility and delete the "Free space" partition so it allows the system APFS container to take up the available space, or if that fails, execute the following command:
```
    sudo diskutil apfs resizeContainer disk1 0
```
>Both Disk Utility and diskutil may fail and require successive resize attempts separated by virtual machine reboots.

**Comment by philphirn** [comment]
@myspaghetti successfully increased disk size.

Now only thing remaining is upgrade. One question : If I press reinstall macOS then won't be my previous data erased ??

And secondly what's the command line command for performing the upgrade ?

**Comment by myspaghetti** [comment]
>And secondly what's the command line command for performing the upgrade ?

`startosinstall` (and the GUI) perform an upgrade by default unless erasing the target is specified. If you're unsure, make a copy of the `.vdi` before trying.

**Comment by philphirn** [comment]
@myspaghetti thanks it worked.

I used the GUI method to upgrade. It successfully upgraded my VM.
The only problem I faced was that after shutting down my VM , VirtualBox showed that the VM is inaccessible as it's unable to attach bootable installer which is already attached. 
The Fix for this is to manually edit the `.vbox` file with any text editor and remove the lines containing the bootable installer under `<AttachedDevices>` and `<DeviceRegistry>` .
Just writing this here so if anyone encounters such problem, they can refer this.

Also I've a suggestion for you, why don't you enable GitHub Discussions for this repo so that people can ask questions like this there and issues remains solely for addressing issues with the script ?

![Success](https://user-images.githubusercontent.com/49480205/112744125-cf53d980-8fba-11eb-8bdc-c7d3d5552c40.png)

**Comment by myspaghetti** [comment]
The answer is kind of rude - I _don't want_ non-issue discussions. People are spreading misinformation (in particular about CPU Profile / CPUID settings) that they've read on other sites and the more it's repeated the more Google spreads it.

The odd general question is fine, but a discussion forum would largely be unmoderated and a breeding ground for misinformation. With technical issues, I feel it's better to have authoritative answers rather than a bunch of wrong answers and "Google it" and "have you tried turning it off and on again?"

**Comment by philphirn** [comment]
@myspaghetti ah I understand.

I've 2 more general questions :

* Is it possible to change the nvram variables after the installation of macOS is finished ? If yes then how ?
* Apple is migrating to M1 chips with ARM arch. Will this affect your script for non-Mac laptops & PCs ?

**Comment by philphirn** [comment]
@myspaghetti 
Thanks 👍
I read the documentation regarding NVRAM & EFI values and everything is clear save one which I want to ask.

My Real MacBook Air doesn't print Apple ROM Info for which you have written in docs that it's ok. But it prints the boot ROM Info in the format given below :

`Boot ROM Version: XXXX.XX.XX.X.X (iBridge: XX.XX.XXXXX.X.X,X)` where X represents any number between 0-9.

Now my questions :

1) Does iBridge mean Apple ROM ?

For my 2nd & 3rd question I want you to refer the snippet of your script below :

```
macos-guest-virtualbox.sh
...
DmiBIOSVersion="string:MBP7.89"      # Boot ROM Version
DmiOEMVBoxVer="string:1"             # Apple ROM Info - left of the first dot
DmiOEMVBoxRev="string:.23.45.6"      # Apple ROM Info - first dot and onward
...```

2) In these 3 parameters, you have used a `string:` thing. So should I remove that `string:` or not ?

3) If iBridge means Apple ROM Info than how should I assign the values ? If you could give an example. If iBridge doesn't mean Apple ROM Info than what should be done with those two variables ? Should we assign the default value ?

Thanks for the help

**Comment by myspaghetti** [comment]
>Does iBridge mean Apple ROM ?

I don't know but it doesn't get checked when logging in to iCloud or iMessage etc. When registering an account, more NVRAM, EFI, and SMC values are queried, so registering requires a full Mac-like set of values that can be provided by OpenCore. The values provided by the script are only sufficient for logging in to an existing account.

>should I remove that string: or not ?

Keep it, otherwise VirtualBox might interpret the string as an int or float or something crazy.

>If iBridge means Apple ROM Info than how should I assign the values ?

Most likely it's not necessary and not checked when logging in to iCloud or iMessage etc. If you really want to assign each and every EFI and NVRAM and SMC value to mirror your genuine Mac you'll need OpenCore, but that's overkill if you just want to log in to an existing iCloud account.
