### ISSUE TITLE
A critical error occured

### ISSUE THREAD

**Issue by Enzo-ltz** [myspaghetti/macos-virtualbox#430]
Hello,

I'm currently trying to install macos on VirtualBox for some lesson.

When I execute the script, it works until the end, but when the VM starts, after the loading of about 15min with the apple disapear, it gives me an error : 

VirtualBox - Guru Meditation : 
A critical error occured during the execution .... 

There is the error message I get in French : 
![image](https://user-images.githubusercontent.com/71329859/112481647-83fdb900-8d77-11eb-991a-b7605aaf4e06.png)

I hope somebody can help me, I can't find anyone else encoutering the same issue.

**Comment by myspaghetti** [comment]
Hi, please attach the VirtualBox log or run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `macOS_troubleshoot.txt` file here.

**Comment by Enzo-ltz** [comment]
Hi, when I woke up this morning and runned it once more, it didn't crash anylonger. This is strange since I tried 4 times yesterday and 2 days ago, with rebooting and many tries, but nothing worked.... Seems to be fixed by obscure forces.

I've no error logs now, so I'll send u if it comes to crash again !

**Comment by notbenoit** [comment]
Hi,
Thanks for this handy script.
While running it successfully (after setting the CPU profile to a Intel Core i7 with `--cpu-profile "Intel Core i7-3960X"`, I'm running a AMD Ryzen 3600), I have the same issue as the original author of this issue. Here is the [macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6406433/macOS_troubleshoot.txt) file. Curious to see what could be the reason of the failure here. Thanks for your help.

**Comment by Enzo-ltz** [comment]
Hi,

It probably won't help you much, but here is what I did when the error occured :
Stop all my computer, and reboot it. Then I launched the virtual machine and it worked successfully.
I still don't understand why, but this is Windows after all !

I'm still using it pretty often for my online course and it's working perfectly (exept the latency but this is probably normal) !

**Comment by notbenoit** [comment]
Thanks for your help @Enzo-ltz. It worked 🎉 , a reboot solved it, I should have thought about it, WIndows...  🤦‍♂️
