### ISSUE TITLE
system-id location problem

### ISSUE THREAD

**Issue by gkip0** [myspaghetti/macos-virtualbox#431]
Hello, I found a problem recently.
The system-id of MacBookPro is in IODeviceTree:/efi/platform/system-id;
However, the system-id of the virtual machine is in the IODeviceTree:/options/system-id
How can I put system-id in IODeviceTree:/efi/platform/system-id?

**Comment by myspaghetti** [comment]
The VM EFI values limited to what VirtualBox recognizes as input. If you want a more flexible and comprehensive solution, you will need to use OpenCore. No support is offered for OpenCore.
