### ISSUE TITLE
3d graphics failure

### ISSUE THREAD

**Issue by 708145h** [myspaghetti/macos-virtualbox#435]
I noticed on other Mac guest  scripts on GitHub that there can be issues with 3d graphics, a game I want to play won't launch. is there anyway around this? im using Mac host and guest

**Comment by myspaghetti** [comment]
VirtualBox does not support 3D acceleration for macOS hosts. The recommended solution is using QEMU over KVM with GPU passthrough, which requires a physical GPU supported by macOS.
