### ISSUE TITLE
Having trouble setting it up

### ISSUE THREAD

**Issue by jemunm378** [myspaghetti/macos-virtualbox#437]
I install all the packages. But go this error: "please make sure the coreutils and gzip packages are the gnu variant" How can i fix it?

**Comment by ashabuzaid** [comment]
When running Cygwin64 Net Release Setup Program (setup-x86_64.exe) you will run into a pane called **Select Packages**. There you must change the **View** option to **Full**, then use the search box to locate the packages you need. Once you locate your package, scroll over to the right of the table under the column **New** where you find the word **Skip**. Click on **Skip** and highlight the latest package release. Once you're done, click **Next** in the bottom right corner and continue with the setup process of Cygwin64. Hope this helps! I'm trying this for this first time myself, as well.

**Comment by myspaghetti** [comment]
@jemunm378 please paste/attach the output of the following commands:
```
gzip --help
unzip -hh
csplit --help 
wget --version
```

**Comment by jemunm378** [comment]
@myspaghetti I did what you said. And it worked, but I had this message now:  "Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off." Virtualization is enabled. And i have WSL2 enabled. Do I need to turn WSL2 off?

**Comment by jemunm378** [comment]
> @jemunm378 please paste/attach the output of the following commands:
> 
> ```
> gzip --help
> unzip -hh
> csplit --help 
> wget --version
> ```

^

**Comment by Masamune3210** [comment]
Yes, you must turn off Hyper-V and WSL as only one hypervisor can use the virtualization features of the cpu at a time

**Comment by mejiacsd** [comment]
I am having difficulties running this as well. 
 
 Virtual Box installed 6.1
 Attached is the Cygwin  status.
 
 I run, and then it prints:
 `Please make sure that the following packages are installed and that they of the version specified or newer:
 coreutils 8.22 wget 1.14 gzip1.5 unzip 6.0
 Please make sure the coreutils and gzip packages are the GNU variant.
 `
 and closes the terminal. I needed to frame-by-frame my screen recording to get that information.
 
 
 
![image](https://user-images.githubusercontent.com/50032086/113934319-76e6be00-97aa-11eb-96a3-781223672513.png)


Am confused about what I am running incorrectly.

**Comment by myspaghetti** [comment]
@mejiacsd please run the following commands in a terminal and attach the *output* of these commands:
```
gzip --help
unzip -hh
csplit --help 
wget --version
```

**Comment by mejiacsd** [comment]
@myspaghetti 

PATH did not get set right, needed to manually adjust it in Win10.
I fixed the PATH and this is the resulting output:
[output.log](https://github.com/myspaghetti/macos-virtualbox/files/6274914/output.log)



Now the script runs and gives me the line:
`2021/04/07 15:40:19 Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.`
[setup.log](https://github.com/myspaghetti/macos-virtualbox/files/6274904/setup.log)

**Comment by jemunm378** [comment]
@Masamune3210 I did it. And it didn't work. Unless there's something else I need to disable 😕

**Comment by myspaghetti** [comment]
@mejiacsd if you already have Cygwin installed with all the packages you don't need use the installer again. No support is offered for dealing with an anti-virus that is blocking the installation of Cygwin.

@jemunm378 there are many apps and features that block VirtualBox from using VT-x/AMD-V. Other than the ones listed there's Core Isolation (of which memory integrity protection is a part), Device Guard, and other features. No support is offered for disabling Windows features that block VirtualBox from using VT-x/AMD-V. Generally speaking, running the following command as admin then rebooting twice has worked for several people:
```
bcdedit /set hypervisorlaunchtype off 
```
But this assumes that you have no other VT-x/AMD-V-blocking features enabled.

**Comment by mejiacsd** [comment]
@myspaghetti Windows updated this morning and the script runs fine now. No idea, Thank you for your timely replies, and the script itself.
