### ISSUE TITLE
Line 14: Syntax error during install

### ISSUE THREAD

**Issue by ashabuzaid** [myspaghetti/macos-virtualbox#438]
![image](https://user-images.githubusercontent.com/75393626/113909624-bbfbf780-978c-11eb-8bcf-07366eb92af9.png)

What did I do now? lol I took a look at the file via Notepad (Windows 10) and didn't see anything out of the ordinary syntax wise.

**Comment by myspaghetti** [comment]
Seems like git is set to convert Unix line endings to Windows line endings. Either configure git to use the repository's line endings or [download the script from your browser.](https://raw.githubusercontent.com/myspaghetti/macos-virtualbox/master/macos-guest-virtualbox.sh)

**Comment by ashabuzaid** [comment]
Thank you! Issue persists on Lines 49, 56, 57, etc. Thanks for the help!
