### ISSUE TITLE
newfs_hfs fails: resource busy

### ISSUE THREAD

**Issue by Tux** [myspaghetti/macos-virtualbox#439]
This started so promising :)
```
virtualbox-6.1.18-lp152.587.1.x86_64
dmg2img-1.6.7-lp152.1.2

Linux 5.3.18-lp152.66-default [openSUSE Leap 15.2]  x86_64  27950 Mb

Extension Packs: 1
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Version:      6.1.18
Revision:     142142
Edition:
Description:  Oracle Cloud Infrastructure integration, USB 2.0 and USB 3.0 Host Controller, Host Webcam, VirtualBox RDP, PXE ROM, Disk Encryption, NVMe.
VRDE Module:  VBoxVRDP
Usable:       true
Why unusable:
```
Your shell starts, but fails in the terminal-window executing `/Volumes/bootinst-sh/bootinst.sh` saying
```
    Restoring  ....10....20..newfs_hfs: cannot create filesystem on /dev/rdisk0s2: Resource busy

/sbin/newfs_hfs failed with error 256

Could not restore - image data corrupted
```
The FS where the VM's reside is an xfs file system with 2.3Tb free space

**Comment by Tux** [comment]
![20210408174834](https://user-images.githubusercontent.com/2492/114059343-90fccb00-9894-11eb-81de-31572c238f19.png)

**Comment by myspaghetti** [comment]
Hi, please run `./macos-guest-virtualbox.sh troubleshoot` and attach the resulting `.txt` file here.

**Comment by Tux** [comment]
![20210408184407](https://user-images.githubusercontent.com/2492/114065216-b391e280-989a-11eb-98a0-fedb48bf37ec.png)
[OSX-Catalina_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6280198/OSX-Catalina_troubleshoot.txt)
I started from scratch. I had the error I reported to start with trice but now I got this

**Comment by myspaghetti** [comment]
Thanks! Everything seems to be configured correctly. I'm going to take a wild guess and say macOS is attempting to perform CPU operations not supported by the Xeon E3-1245, resulting in memory corruption or other errors. See the documentation command about unsupported CPUs.

VirtualBox offers the following preconfigured CPU profiles: `"Intel Xeon X5482 3.20GHz"  "Intel Core i7-2635QM"  "Intel Core i7-3960X"  "Intel Core i5-3570"  "Intel Core i7-5600U"  "Intel Core i7-6700K"`

You can set them manually with `VBoxManage` or add them to the script on line `657`:
```
654    VBoxManage modifyvm "${vm_name}" --cpus "${cpu_count}" --memory "${memory_size}" \
655     --vram "${gpu_vram}" --pae on --boot1 none --boot2 none --boot3 none \
656     --boot4 none --firmware efi --rtcuseutc on --chipset ich9 ${extension_pack_usb3_support} \
657      --mouse usbtablet --keyboard usb --audiocontroller hda --audiocodec stac9221
```

Add `--cpu-profile "PROFILE"`. You'll have to find a working profile with trial and error or you could delve deeper into macOS and CPUID settings and make a [custom CPUID.](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport)

**Comment by Tux** [comment]
It worked almost flawless on my laptop
```
Linux 5.11.11-1-default [openSUSE Tumbleweed 20210406]  HP ZBook 15G3 Core(TM) i7-6820HQ CPU @ 2.70GHz/2700(8 cores) x86_64  32020 Mb
virtualbox-6.1.18-4.1.x86_64

Extension Packs: 1
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Version:      6.1.18
Revision:     142142
Edition:
Description:  Oracle Cloud Infrastructure integration, USB 2.0 and USB 3.0 Host Controller, Host Webcam, VirtualBox RDP, PXE ROM, Disk Encryption, NVMe.
VRDE Module:  VBoxVRDP
Usable:       true
Why unusable:
```
My disk was full so I had to create free space and start over

It did not recognize started terminal(s)
I have a working Catalina VM. Feel free to close this issue!

**Comment by myspaghetti** [comment]
Thanks. Since you're running Linux I heartily recommend creating or converting the virtual disk image to `vmdk`, installing and configuring OpenCore, and booting the image on QEMU/KVM. If you're running High Sierra and have a spare compatible GPU it's a world of difference. If you don't have a compatible GPU, QEMU and OpenCore still offers a few nice benefits, with the price being your time spent configuring them.
