### ISSUE TITLE
"Couldn't download the Apple software update catalog."

### ISSUE THREAD

**Issue by SWORDISA212** [myspaghetti/macos-virtualbox#442]
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6319020/macOS_troubleshoot.txt)

   When running the "macos-guest-virtualbox" script I get the following issue defined in the title. Attached is the troubleshoot log. Sorry if I missed something that was mentioned I'm new at this. I did make sure all the required dependences were installed.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report! Does the script directory happen to have a file with a name ending with `_wget.log` like `Catalina_wget.log`? That should tell you what went wrong with the download. The troubleshoot log only provides information about VirtualBox and the script configuration;

**Comment by SWORDISA212** [comment]
> Hi, thanks for the bug report! Does the script directory happen to have a file with a name ending with `_wget.log` like `Catalina_wget.log`? That should tell you what went wrong with the download. The troubleshoot log only provides information about VirtualBox and the script configuration;
________________________________________________________________________________________________________________________________
Sadly the log only says "DEBUG output created by Wget 1.11.4 on Windows-MinGW."
![image](https://user-images.githubusercontent.com/82597089/114908898-8c7f6780-9dea-11eb-99da-9abf4525032b.png)
[Catalina_wget.log](https://github.com/myspaghetti/macos-virtualbox/files/6319907/Catalina_wget.log)
I reran the script to see if I could get a different output or error log for Catalina_wget.txt but to no avail.

**Comment by myspaghetti** [comment]
The script is not tested on MiniGW. Please use Cygwin or WSL1. MiniGW is a software development environment and not a full Unix shell.

**Comment by SWORDISA212** [comment]
> The script is not tested on MiniGW. Please use Cygwin or WSL1. MiniGW is a software development environment and not a full Unix shell.
_________________________________________

That's confusing, i thought i was using Cygwin? I don't even know what MiniGW looks like. From what I see MiniGW is apart of Wget. How do i test to make sure I'm using Cygwin? I am using the Cygwin terminal.

**Comment by myspaghetti** [comment]
Run `which -a wget` and it'll show all the `wget` executables in the directories listed in the `PATH` variable. It's likely that MiniGW wget (and the rest of the MiniGW utilities) are in a higher-priority directory. If that's the case, either remove the directory from the `PATH` variable or move it to a lower priority (for example replace `PATH=/path/to/MiniGW/bin:/path/to/cygwin/bin` with `PATH=/path/to/cygwin/bin:/path/to/MiniGW/bin`)

**Comment by SWORDISA212** [comment]
> Run `which -a wget` and it'll show all the `wget` executables in the directories listed in the `PATH` variable. It's likely that MiniGW wget (and the rest of the MiniGW utilities) are in a higher-priority directory. If that's the case, either remove the directory from the `PATH` variable or move it to a lower priority (for example replace `PATH=/path/to/MiniGW/bin:/path/to/cygwin/bin` with `PATH=/path/to/cygwin/bin:/path/to/MiniGW/bin`)

____________________________________________________________________________________________________________________________________
I got it!!!  Thank you, I removed wget from the path environment then uninstalled the version of wget I got from their site and reinstalled wget through Cygwin packages and it worked. I appreciate you helping me out. 
![image](https://user-images.githubusercontent.com/82597089/115011217-62768580-9e7c-11eb-860b-a9c1fe5303d1.png)
