### ISSUE TITLE
[Feature Request] Continue from stage X

### ISSUE THREAD

**Issue by Tschrock** [myspaghetti/macos-virtualbox#444]
Thanks for this amazing script!
Since it's common (at least in my experience) to have to tweak the cpu profile to get the VM to boot properly, it would be nice if there was an easy way to continue from the stage where it got stuck.

Currently you have two choices if there's an error in a stage:
1. Run the whole script again, which repeats a number of things like downloading the software catalogue and spliting the package into parts (luckily it doesn't have to redownload the whole install package)
2. Look up the list of stages and run each remaining stage yourself.

It would be useful to have a way to tell the script "Start at stage X and continue from there".

**Comment by myspaghetti** [comment]
That would be nice, though specifying one stage name and, say, "continue" is not so different from specifying "`populate_basesystem_virtual_disk create_bootable_installer_virtual_disk populate_bootable_installer_virtual_disk create_target_virtual_disk populate_macos_target_disk`. I can see how the latter can be a hassle if copy-paste is not available for some reason.

**Comment by myspaghetti** [comment]
That would be nice, though specifying, say, `./macos-guest-virtualbox.sh populate_basesystem_virtual_disk  continue` is not so different from specifying `./macos-guest-virtualbox.sh populate_basesystem_virtual_disk create_bootable_installer_virtual_disk populate_bootable_installer_virtual_disk create_target_virtual_disk populate_macos_target_disk`. I can see how the latter can be a hassle if copy-paste is not available for some reason.

**Comment by myspaghetti** [comment]
Added `and_all_subsequent_stages` to [version 0.98.5](https://github.com/myspaghetti/macos-virtualbox/commit/0855b1ea50b07fb4f17b4126b67e05d7d1972d4a)
