### ISSUE TITLE
issue in installation proccess

### ISSUE THREAD

**Issue by jafarsadeghi** [myspaghetti/macos-virtualbox#446]
![Screenshot from 2021-04-18 21-04-08](https://user-images.githubusercontent.com/45605914/115153127-a38fb500-a089-11eb-860b-7711795284a2.png)

i have this issue in installing way , what should i do?

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. You could just try running `./macos-guest-virtualbox.sh configure_vm and_all_subsequent_stages` and see if whatever issue existed no longer prevents the VM from being configured.

Or, you could manually run `VBoxManage modifyvm "macOS" --cpus "2"` and post here whatever unintelligible error VirtualBox spits out and we'll try to figure it out.

**Comment by jafarsadeghi** [comment]
`jafar@jafar-VivoBook-ASUSLaptop-X430FN-S430FN:~/macos-virtualbox$ ./macos-guest-virtualbox.sh configure_vm and_all_subsequent_stages
./macos-guest-virtualbox.sh: line 22: 4: command not found

The command "VBoxManage list extpacks" either does not list the Oracle VM
VirtualBox Extension Pack, or lists one or more extensions as unusable.
The virtual machine will be configured without USB xHCI controllers.

Catalina selected to be downloaded and installed

stage: configure_vm

Error: Could not configure virtual machine "macOS".
Please execute the stage configure_vm again before resuming the script
as described in the documentation.

Exiting.
jafar@jafar-VivoBook-ASUSLaptop-X430FN-S430FN:~/macos-virtualbox$ VBoxManage modifyvm "macOS" --cpus "2"
jafar@jafar-VivoBook-ASUSLaptop-X430FN-S430FN:~/macos-virtualbox$ ./macos-guest-virtualbox.sh configure_vm and_all_subsequent_stages
./macos-guest-virtualbox.sh: line 22: 4: command not found

The command "VBoxManage list extpacks" either does not list the Oracle VM
VirtualBox Extension Pack, or lists one or more extensions as unusable.
The virtual machine will be configured without USB xHCI controllers.

Catalina selected to be downloaded and installed

stage: configure_vm

Error: Could not configure virtual machine "macOS".
Please execute the stage configure_vm again before resuming the script
as described in the documentation.

Exiting.
jafar@jafar-VivoBook-ASUSLaptop-X430FN-S430FN:~/macos-virtualbox$ ./macos-guest-virtualbox.sh configure_vm and_all_subsequent_stages
./macos-guest-virtualbox.sh: line 22: 4: command not found

The command "VBoxManage list extpacks" either does not list the Oracle VM
VirtualBox Extension Pack, or lists one or more extensions as unusable.
The virtual machine will be configured without USB xHCI controllers.

Catalina selected to be downloaded and installed

stage: configure_vm

Error: Could not configure virtual machine "macOS".
Please execute the stage configure_vm again before resuming the script
as described in the documentation.

Exiting.
jafar@jafar-VivoBook-ASUSLaptop-X430FN-S430FN:~/macos-virtualbox$ bash ./macos-guest-virtualbox.sh configure_vm and all_subsequent_stages

One or more specified arguments is not recognized.

Recognized stages:

    check_shell
    check_gnu_coreutils_prefix
    set_variables
    welcome
    check_dependencies
    prompt_delete_existing_vm
    create_vm
    check_default_virtual_machine
    prepare_macos_installation_files
    create_nvram_files
    create_macos_installation_files_viso
    configure_vm
    populate_basesystem_virtual_disk
    create_bootable_installer_virtual_disk
    populate_bootable_installer_virtual_disk
    create_target_virtual_disk
    populate_macos_target_disk
    prompt_delete_temporary_files

Other recognized arguments:

    documentation
    troubleshoot
    and_all_subsequent_stages

View documentation by entering the following command:
  ./macos-guest-virtualbox.sh documentation | less -R
`
i have do those things and result came like above :)
thank you for nice response time:)

**Comment by myspaghetti** [comment]
> ./macos-guest-virtualbox.sh: line 22: 4: command not found

This is strange. Please run `bash -x ./macos-guest-virtualbox.sh configure_vm` and post the output here, preferably attached as a `.txt` file.

**Comment by jafarsadeghi** [comment]
[output.txt](https://github.com/myspaghetti/macos-virtualbox/files/6331810/output.txt)
this is the output file

**Comment by myspaghetti** [comment]
There's a stray new line after `cpu_count=`, should be on a single line `cpu_count=4`

**Comment by jafarsadeghi** [comment]
that issue handled , but this issue poped up :
stage: populate_macos_target_disk
Could not configure virtual machine storage controller. Exiting.
what shoud i do for this?
thank you for your help.

**Comment by myspaghetti** [comment]
What's the output of the following commands:
```
VBoxManage storagectl "macOS" --remove --name SATA
VBoxManage storagectl "macOS" --add sata --name SATA --hostiocache on
```

**Comment by jafarsadeghi** [comment]
in first attempt the output was nothing for both of them, 

in second attempt for each command the output was like below:

first command second attempt : 
`VBoxManage: error: Could not find a storage controller named 'SATA'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "RemoveStorageController(Bstr(pszCtl).raw())" at line 1062 of file VBoxManageStorageController.cpp
`
second command second attempt:
`VBoxManage: error: Storage controller named 'SATA' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1078 of file VBoxManageStorageController.cpp
`

**Comment by myspaghetti** [comment]
It's likely the virtual machine was not completely shut down when the command was executed, should be fine now. You should be able to resume the script with `./macos-guest-virtualbox.sh populate_macos_target_disk and_all_subsequent_stages`

**Comment by jafarsadeghi** [comment]
thank you i installed successfully thank you
