### ISSUE TITLE
CPU error on startup, now can't continue.

### ISSUE THREAD

**Issue by SuperBoyne** [myspaghetti/macos-virtualbox#447]
While booting macOS had a CPU error, so I used CTRL+C on the bash script, and fixed the problem. When I tried to run the script again so I could continue, it just asked if it could delete macOS. How do I continue?

**Comment by myspaghetti** [comment]
You can continue the script from the stage that was aborted as specified in the documentation, for example if you aborted at the "welcome" stage you can run `./macos-guest-virtualbox.sh welcome and_all_subsequent_stages`

**Comment by SuperBoyne** [comment]
Thanks man, you're the best!
