### ISSUE TITLE
Recovering Catalina_InstallESD.part files

### ISSUE THREAD

**Issue by Whysp3r** [myspaghetti/macos-virtualbox#449]
Hi, 
First thanks for the script, installation process worked perfectly.

The thing is I was running out of space and by mistake (not really a mistake actually ...) I've deleted the Catalina_InstallESD.part files. I thought it was just some installation files not needed anymore...

Is there a way to recover or extract them (like from Catalina_InstallESDDMG.pkg ) while keeping the state of the virtual machine ? Or I need to re-create a vm from scratch ?

Thanks

**Comment by myspaghetti** [comment]
Thank you!

>I thought it was just some installation files not needed anymore...

They aren't needed! They are an exact copy of the file `Catalina_InstallESDDMG.pkg` which are delivered into the virtual machine through a virtual ISO. The script uses the VirtualBox VISO format, which presents itself as an ISO 9660 file system, and macOS does not support ISO 9660 file system files that are larger than 2GB like InstallESDDmg.pkg, so it has to be split.

You can create them with the following command:
```
split --verbose -a 2 -d -b 1000000000 "Catalina_InstallESDDmg.pkg" "Catalina_InstallESD.part"
```

However, in the interest of saving space, you can delete all the files on the script directory except the `Catalina_bootable_installer.vdi` file which is the only file necessary to create new macOS virtual machines. Simply create an empty `.vdi` file that's large enough for macOS (25GB or more), boot the bootable installer, run Disk Utility and erase/format the empty virtual disk to HFS+ or APFS, then run the command-line installer (or the graphical installer, but it tends to crash in the VM).

**Comment by myspaghetti** [comment]
Thank you!

>I thought it was just some installation files not needed anymore...

They aren't needed! They are an exact copy of the file `Catalina_InstallESDDMG.pkg` and they're split so they can be delivered into the virtual machine through a virtual ISO. The script uses the VirtualBox VISO format, which presents itself as an ISO 9660 file system, and macOS does not support ISO 9660 file system files that are larger than 2GB like InstallESDDmg.pkg, so `InstallESDDMG.pkg` has to be split, and the script splits it into 1,000,000,000 byte files.

You can create split it with the following command:
```
split --verbose -a 2 -d -b 1000000000 "Catalina_InstallESDDmg.pkg" "Catalina_InstallESD.part"
```

However, in the interest of saving space, you can delete all the files on the script directory except the `Catalina_bootable_installer.vdi` file which is the only file necessary to create new macOS virtual machines. Simply create an empty `.vdi` file that's large enough for macOS (25GB or more), boot the bootable installer, run Disk Utility and erase/format the empty virtual disk to HFS+ or APFS, then run the command-line installer (or the graphical installer, but it tends to crash in the VM).

**Comment by myspaghetti** [comment]
Thank you!

>I thought it was just some installation files not needed anymore...

They aren't needed! They are an exact copy of the file `Catalina_InstallESDDMG.pkg` and they're split so they can be delivered into the virtual machine through a virtual ISO. The script uses the VirtualBox VISO format, which presents itself as an ISO 9660 file system, and macOS does not support ISO 9660 file system files that are larger than 2GB like InstallESDDmg.pkg, so `InstallESDDMG.pkg` has to be split, and the script splits it into 1,000,000,000 byte files.

You can split it with the following command:
```
split --verbose -a 2 -d -b 1000000000 "Catalina_InstallESDDmg.pkg" "Catalina_InstallESD.part"
```

However, in the interest of saving space, you can delete all the files on the script directory except the `Catalina_bootable_installer.vdi` file which is the only file necessary to create new macOS virtual machines. Simply create an empty `.vdi` file that's large enough for macOS (25GB or more), boot the bootable installer, run Disk Utility and erase/format the empty virtual disk to HFS+ or APFS, then run the command-line installer (or the graphical installer, but it tends to crash in the VM).

**Comment by Whysp3r** [comment]
This is just perfect, so many thanks !!!
