### ISSUE TITLE
Will this work with a modern 5600x? 

### ISSUE THREAD

**Issue by adamraetz** [myspaghetti/macos-virtualbox#451]
I get to the following piece and then it hangs.

> Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.
Until the script completes, please do not manually interact with
the virtual machine.
Attempting automated recognition of virtual machine graphical user interface.
Please wait
Failed automated recognition of virtual machine graphical user interface.
Please press enter as directed.
Press enter when the Language window is ready.

Wondering if I just dont have a supported processor. Or am I missing something else?

Thank you so much.

[macos-guest-virtualbox.txt](https://github.com/myspaghetti/macos-virtualbox/files/6373150/macos-guest-virtualbox.txt)

**Comment by Jonel-Code** [comment]
Hello, 
For those people who still looking for answer on this question I am able to complete the script execution on my 5600x after I edited the CPU profile. 
If you encounter the same issue with this thread: #499 , you will only need to stop the script and close the VM then proceed with editing the VM's CPU profile using the command below:
`VBoxManage modifyvm "{vm_name}" --cpu-profile "Intel Xeon X5482 3.20GHz"`
Note that by default the `vm_name` is `macOS`
After editing the CPU profile you can resume the process again by running the command: 
`bash ./macos-guest-virtualbox.sh populate_bootable_installer_virtual_disk and_all_subsequent_stages`

if you still encounter the issue with #499 after this steps, You can switch with different cpu profile which you can see on "Available CPU profiles" section after running the `bash ./macos-guest-virtualbox.sh documentation` then repeat the same script above.

PS. I am running windows 11 on 5600x and Virtualbox 6.1

Hope it helps.
