### ISSUE TITLE
Bluetooth passthrough

### ISSUE THREAD

**Issue by guanzhangrtk** [myspaghetti/macos-virtualbox#454]
Hi, first off thanks for making this script, it saved me a lot of time to quickly setup a macOS VM so I don't have to actually fiddle around trying to do this manually.

I was wondering if anybody has experience setting up Bluetooth on the macOS guest VM. I've tried on both macOS Big Sur and Windows 10 as host and both have their own issues. This is done on a MacBookPro10,1 so the hardware is definitely supported.

On macOS, it simply would not work. I think I somehow have to prevent the host macOS from taking over the Bluetooth but haven't figured out how to do that yet.

On Windows, it does work out of the box (just need to connect the USB device from the host to the guest), but after some time Bluetooth would stop working and if you go to System Preferences it would be completely hung and the only thing I can do to get it working again is to completely shut down the VM and power it back on.

This may be outside the scope of this script but I figure since there are many users who use this to make macOS VMs perhaps someone has had experience with it.

Thanks in advance for any insights you can provide.

**Comment by myspaghetti** [comment]
Hi, glad you're enjoying the script. VirtualBox USB passthrough is not that great, but I'm glad it (sometimes) works for you with a Bluetooth USB device. Proper solutions would be:

* Using QEMU-over-KVM with OpenCore but that would require manually configuring both QEMU and OC. This is actually my recommended solution as the script has always been a stop-gap measure for creating an initial VM disk image that gets ported to better virtualization software.
* Filing a bug report with the VirtualBox team for a macOS guest on a macOS host, which _is_ officially supported but probably isn't a high priority: recently Oracle introduced a host-freezing bug to macOS audio so I doubt they'd put in the time to fix USB passthrough or any macOS-on-macOS bug, as there's no business case for them for this sort of virtualization.
* Fixing VirtualBox yourself (if you feel like doing that, maybe you should get hired by Oracle first!)
* Using some USB-over-IP software. These work well enough and have been used by a few people who raised similar issues before.
