### ISSUE TITLE
Systen-ID bug

### ISSUE THREAD

**Issue by dhia-e-rzig** [myspaghetti/macos-virtualbox#460]
Hi there,
I added my parameters (UUID, ROM, etc.) from my old mac but I am still having a problem sigining into iMessage. I get the call customer service message, and when I run the iMessageDebug tool ( https://www.tonymacx86.com/threads/how-to-fix-imessage.110471/) I get System ID: false value, and I also can't find it using IOReg ( I think it is loaded into the NVRAM however, as I can see a value using nvram-xp). Any idea how to fix this ?

The old macbook in question has not been in use for a while.

**Comment by myspaghetti** [comment]
This could happen if you've tried to log in to iMessage and later changed some values. macOS stores the original value and then compares it to the new value, and reports an error. The easiest way to fix it is to make a new VM with the correct value from the start, but there are also guides on the internet for erasing the old value from macOS.

**Comment by dhia-e-rzig** [comment]
Nope, still not working, tried recreating the VM from scratch with the right parameters and I am still getting this message. Screenshots attached for reference.  

![imessage-debug-log](https://user-images.githubusercontent.com/46030840/117549805-6aa08b80-b00a-11eb-92bb-ca9e62db7ed4.png)
![imessage-message](https://user-images.githubusercontent.com/46030840/117549806-6b392200-b00a-11eb-99d2-deb55dca9c69.png)

**Comment by myspaghetti** [comment]
It still shows System ID failed. Are you sure you actually wrote the value to NVRAM? What does `nvram 7C436110-AB2A-4BBB-A880-FE41995C9F82:system-id` output on the virtual machine Terminal?
