### ISSUE TITLE
How to give permission to delete temporary files

### ISSUE THREAD

**Issue by KraynSG** [myspaghetti/macos-virtualbox#463]
When I try to delete the temporary files with the command "./macos-guest-virtualbox.sh prompt_delete_temporary_files"
in Cygwin, it respond : 

-bash: ./macos-guest-virtualbox.sh: Permission denied

How can I give the permission to delete it ?

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report! Please run the following command and attach the `debug.txt` file here:
```
bash -x ./macos-guest-virtualbox.sh prompt_delete_temporary_files 2> debug.txt
```

**Comment by KraynSG** [comment]
Thanks for the amazing respond time !

**Comment by chapit-nicolas** [comment]
[debug.txt](https://github.com/myspaghetti/macos-virtualbox/files/6479335/debug.txt)

In case where @KraynSG did not add the debug.
Got the same issue.

**Comment by myspaghetti** [comment]
@chapit-nicolas the `debug.txt` shows that the VM is running, and the script won't delete the temporary files unless the virtual machine is powered off and without a suspended state.

Another possible issue is that the script directory was copied and the script file lost its execution permission. In which case, you can run the script with `bash ./macos-guest-virtualbox.sh prompt_delete_temporary_files` or you can add the execution permission with `chmod u+x macos-guest-virtualbox.sh` and then run the script with `./macos-guest-virtualbox.sh prompt_delete_temporary_files`

**Comment by chapit-nicolas** [comment]
Arff right, there was a message saying that...
Sorry.

@KraynSG Was it the same reason for you?

**Comment by KraynSG** [comment]
Idk
