### ISSUE TITLE
The installer is stuck in this screen

### ISSUE THREAD

**Issue by leoheck** [myspaghetti/macos-virtualbox#464]
Hello there, I am trying to run this tool, but I am stuck here, did I do something wrong?
Do you have any idea of what is going on? 
![image](https://user-images.githubusercontent.com/1277920/118409026-d617d800-b65e-11eb-91f6-f27bbf00ba78.png)

**Comment by leoheck** [comment]
Now I am stuck here. I am not sure if I have to interact with the Script/VM or I have to level it there for hous.
![image](https://user-images.githubusercontent.com/1277920/118410453-e089a000-b665-11eb-9ae1-47781ccc69f9.png)

**Comment by myspaghetti** [comment]
Duplicate, see [release notes](https://github.com/myspaghetti/macos-virtualbox/releases) "known issues" section or search the documentation for `CPU`
