### ISSUE TITLE
Script didn't detect xxd wasn't installed when using Cygwin

### ISSUE THREAD

**Issue by manningb** [myspaghetti/macos-virtualbox#465]
"xxd.exe: /dev/urandom: No such file or directory"

I had been getting this error.  It had notified me that wget, and a number of other packages were not installed on Cygwin, but did not detect that xxd wasn't installed. After installing xxd on Cygwim, the script worked.

Thank you for making this script!

**Comment by myspaghetti** [comment]
Technically `xxd` was installed, just not a version of `xxd` that supports Cygwin's `/dev/urandom`

Fixed check in [commit 4051918 (40519182cc77f59736505a8ad612559cfa7f5406)](https://github.com/myspaghetti/macos-virtualbox/commit/40519182cc77f59736505a8ad612559cfa7f5406)
