### ISSUE TITLE
Installation seems successfull but boot on repair utilities

### ISSUE THREAD

**Issue by Fl0ux** [myspaghetti/macos-virtualbox#466]
Hello,

First, thanks for your work !

I am running your script from a Linux machine (Manjaro) with a Ryzen 5 processor. I had to do the cpuid and cpu profile trick so the VM can boot. After that, I resumed the installation with 
`./macos-guest-virtualbox.sh populate_bootable_installer_virtual_disk`

Everything seems to run flawlessly and I do not see any error anywhere. Your script finish saying 
`If the partitioning fails, exit the script by pressing CTRL-C
Otherwise, please wait.
Waiting for the VirtualBox GUI to shut off.
Please wait      
Catalina_BaseSystem.vdi successfully detached from
the virtual machine and released from VirtualBox Manager.`

But then when I boot the VM it asks me for my language and then it shows the repair utilities window.

Am I missing something stupid or is there a problem somewhere ?

Thanks for your time !

**Comment by myspaghetti** [comment]
`populate_bootable_installer_virtual_disk` is not the last stage of the script, you need to execute the subsequent stages too.
