### ISSUE TITLE
When setting up, after it gives me the system specs, it says crtl-c or enter, i clicked enter and the program exits.

### ISSUE THREAD

**Issue by coolio79** [myspaghetti/macos-virtualbox#467]
Pls help

**Comment by myspaghetti** [comment]
Running the script interactively requires running the script in an interactive shell. Make sure you run the script in an interactive session of `bash` or `zsh`.

**Comment by coolio79** [comment]
How am i supposed to do that?

**Comment by coolio79** [comment]
I just ran it in cmd as admin, and the same error is happening
am i doing something wrong?

**Comment by myspaghetti** [comment]
Starting with version `0.98.8` the script doesn't check `stdout` any more, instead it checks the `bash` or `zsh` invocation options, making things slightly more tedious for everybody but less prone to confuse people who don't know if their shell is interactive or not.
