### ISSUE TITLE
I runned the program and it says I need unzip, gzip, wget, and courutils. How can i download these as I they are tar file, and I dont know how to download tar files.  Can someone send them, that would be helpful.

### ISSUE THREAD

**Issue by yessir12345** [myspaghetti/macos-virtualbox#470]
Do you know how to download unzip, gzip, wget, and courutils for the script?

**Comment by yessir12345** [comment]
Anybody help?

**Comment by yessir12345** [comment]
Pls help

**Comment by yessir12345** [comment]
I'm running windows 10. And I don't know how to install these files. And for the gzip, wget, and coreutils when I go to the download page on GNU they are all tar. And for unzip their website gives me a zip file with no program in it.

**Comment by Masamune3210** [comment]
Please fully read the main page once again, as it clearly states that you use a package manager to install these
