### ISSUE TITLE
Error when booting the system for the first time

### ISSUE THREAD

**Issue by silveralextv** [myspaghetti/macos-virtualbox#475]
I have this window on first time system boot
![Error Screen](https://i.ibb.co/2MPwXJh/Virtual-Box-mac-OS-05-06-2021-10-27-31.png)

The script run verification process :
![Error](https://i.ibb.co/rvK93qj/Capture-d-cran-de-2021-06-05-10-30-57.png)

I run the script on Ubuntu 20.04

Can you help me ?

**Comment by myspaghetti** [comment]
`If booting fails, exit the script by pressing CTRL-C then see the documentation for information about applying different CPU profiles.`
