### ISSUE TITLE
Keyboard and Mouse not working after Big Sur software update

### ISSUE THREAD

**Issue by 7heMeowMeowCat** [myspaghetti/macos-virtualbox#479]
I installed macOS Catalina from this script, and keyboard and mouse were working fine. But when I updated to Big Sur through software update, the keyboard and mouse stopped working completely. I tried googling, applied the suggested fixes (installed _"VirtualBox 6.1.22 Oracle VM VirtualBox Extension Pack"_ extension pack: https://www.virtualbox.org/wiki/Downloads, then went into the VM's _settings_ > _USB_ and selected _USB 3.0 (xHCI) Controller_ , and also tried adding my keyboard and mouse on this screen), but none seemed to work. I'm on Virtual Box Version 6.1.22.

**Comment by myspaghetti** [comment]
Hi, would you mind posting the output of the following command:
```
VBoxManage showvminfo "macOS" --machinereadable --details | grep usb
```
Substitute "macOS" with the name of the VM with the issues.

**Comment by 7heMeowMeowCat** [comment]
```
hidpointing="usbtablet"
hidkeyboard="usbkbd"
usb="off"
```

**Comment by myspaghetti** [comment]
Can you check or recall anything else that might have affected the VM mouse and keyboard? I have updated from the latest Catalina to the latest Big Sur and could not reproduce any issue with mouse or keyboard input.
