### ISSUE TITLE
Updating to MacOS Monterey leads to an infinite boot sequence.

### ISSUE THREAD

**Issue by ActuallyZach** [myspaghetti/macos-virtualbox#484]
I hope this is the right place to ask this, I am not really sure of anywhere else too,

I started off using this installer to create a Catalina VM. From the Catalina VM, I used the Big Sur updater from the App Store to update the VM. This update went smoothly, so I then downloaded the beta profile for Monterey. I let the installer run and it gets to the point of rebooting to the Apple logo. Here it makes it almost to the end of the bar, but about 5/6ths of the way did when it rebooted again. This time it did not make it back to the Apple logo. It is now just stuck on a seemingly infinite sequence of logging text to the screen. 

The text it is logging is,
```
AppleKeyStore: 1149:1266 operation failed (sel: 7 ret: e00002bc, -1, 100000)
IOConsoleUsers: time(0) 0->0, lln 0, llk 1,
IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sw 0x0
Failed e00002be to create GTraceBuffer cdgtrace for decoder and count 1024
```

I am not sure why this has happened, as the Big Sur update went all good. Is there any known fix to this? Or any possible steps I can take to update to Monterey?

**Comment by myspaghetti** [comment]
There was an issue with `AppleKeyStore` with the Big Sur beta too. Maybe it'll get resolved by the time Monterey hits release candidate.

**Comment by myspaghetti** [comment]
There was an issue with `AppleKeyStore` with the Big Sur beta too. Maybe it'll get resolved by the time Monterey hits release candidate.

Meanwhile if you still want to run Monterey you could try installing it on an empty volume (don't upgrade an existing system) and then set USB to version 1.1 and disable VM network adapters, that worked around the `AppleKeyStore` issues with the Big Sur beta.

**Comment by zoolino** [comment]
Sam here, clean installed Monterey on Virtual Box, installation went fine but on restart I get stuck on same error, above tips did not help. Any adive?

**Comment by myspaghetti** [comment]
The release version (12.0.1) installs, boots, and performs fine.

**Comment by myspaghetti** [comment]
After further testing, the most often-successful way to install Monterey is to download it through Software Update and select a non-system volume as the installation target. Upgrading in-place may lead to a boot loop, installing onto an empty volume seems to work more consistently.

**Comment by CalculonPrime** [comment]
> 
> 
> The release version (12.0.1) installs, boots, and performs fine.

That's not what I'm finding.  If I use the latest official image linked from this page:
https://7labs.io/tips-tricks/macos-monterey-direct-download.html
macOS Monterey 12.0.1 (21A559) / October 25, 2021
SHA256: 9630e14e5142937a08bc01dea96fead4477e5722fa8390d712ecae318acaf476

Then whether I install it as an upgrade to a working Catalina system, or install it to an empty drive, after the initial reboot, then it enters a reboot loop where it gets to the Apple logo + progress bar, and then randomly restarts after 1 or sometimes 10 minutes.

**Comment by myspaghetti** [comment]
@CalculonPrime try installing it from a working Catalina system onto an empty volume using Software Update. This should enable you to boot both Catalina and Monterey. I suspect that upgrading Catalina or installing from a bootable installer onto an empty volume upgrades the boot process, which results in boot issues. However, keeping Catalina intact and installing Monterey from Catalina onto an empty volume has consistently resulted, under my limited testing, in a working dual-boot Monterey and Catalina VM.

**Comment by CalculonPrime** [comment]
> 
> 
> @CalculonPrime try installing it from a working Catalina system onto an empty volume using Software Update. This should enable you to boot both Catalina and Monterey. I suspect that upgrading Catalina or installing from a bootable installer onto an empty volume upgrades the boot process, which results in boot issues. However, keeping Catalina intact and installing Monterey from Catalina onto an empty volume has consistently resulted, under my limited testing, in a working dual-boot Monterey and Catalina VM.

I'm using the installer pkg mentioned above to install within Catalina to a new disk volume, so I believe that's the exact case you suggested.  Catalina is not modified, yet the new disk ends up an infinite boot loop after the in-OS installation bit finishes.  It boots up to the progress bar, reaches between 28%-18% complete, and then reboots.

So, not working for me.

**Comment by CalculonPrime** [comment]
Looks like the missing piece of the puzzle here is the # of CPUs you choose.  If you choose 2 CPUs, it will install and boot.  If you choose 4 CPUs (which my Catalina system had configured), it will loop during installation and if you toggle it on an installed Monterey system it will kernal panic and crash a few seconds after you reach the desktop (try doing 'about this computer').

So looks like VirtualBox is not handling some magic that runs with > 2 CPUs for Monterey.

**Comment by CalculonPrime** [comment]
Actually, even 2 CPUs doesn't seem to be completely stable.  I've had two reboots with 2 CPUs though sometimes the system can go for hours without crashing.  Also, XCode 13.1 appears to be unusable with Monterey + VirtualBox at the moment, as when I run the Simulator, SpringBoard keeps crashing with an illegal instruction.

**Comment by FlorianLeMenn** [comment]
Hello, I have the same problem, with kernel panic reboot, I try different solution and now it's work : 
VirtualBox configuration : 
![image](https://user-images.githubusercontent.com/4291551/159434322-b106360f-679d-4596-bfd0-2ee93574ba33.png)
VirtualBox Manage conf : 
```
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac19,1"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Mac-AA95B1DDAB278B95"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage setextradata "macos" "VBoxInternal/TM/TSCMode" "RealTSCOffset"
```

**Comment by CalculonPrime** [comment]
Thanks, yes the line:

`VBoxManage setextradata "macos" "VBoxInternal/TM/TSCMode" "RealTSCOffset"`

seems to be what fixes things.  

Now, the only remaining issue with Monterey + VirtualBox is that Recovery Mode is unreachable.  If you try to "boot from file" in the VirtualBox BIOS and dive into the Recovery Partition, in Catalina there was a boot.efi file under the GUID, but not in Monterey.  (Actually, I think the issue started with Big Sur but I don't have a BIg Sur VM.)

**Comment by joaomcferreira** [comment]
I have just tried the instructions given by @FlorianLeMenn and I was finally able to upgrade to Monterey without any problems. Started installations from zero, on VirtualBox, removed the execssive files; run the VBoxManage commands and the upgrdade now is successful for the first time for me. I am running Debian11 with VirtualBox 6.1.32.

Thank you

**Comment by goodfellasthai** [comment]
> Thanks, yes the line:
> 
> `VBoxManage setextradata "macos" "VBoxInternal/TM/TSCMode" "RealTSCOffset"`
> 
> seems to be what fixes things.
> 
> Now, the only remaining issue with Monterey + VirtualBox is that Recovery Mode is unreachable. If you try to "boot from file" in the VirtualBox BIOS and dive into the Recovery Partition, in Catalina there was a boot.efi file under the GUID, but not in Monterey. (Actually, I think the issue started with Big Sur but I don't have a BIg Sur VM.)

This is also what fixed it for me, I wasn't specifically setting any VirtualBox params other than the script generated ones, once I changed RealTSCOffset there was no more boot loop during the Monterey upgrade from the default Catalina install, recommend adding to the the script @myspaghetti 

I added the below to the configure_vm section in the script
VBoxManage setextradata "${vm_name}" \
 "VBoxInternal/TM/TSCMode" "RealTSCOffset"

Also loving your work @myspaghetti  - this is an amazing script for running a macOS installation on VirtualBox from Windows - top work.

**Comment by myspaghetti** [comment]
Thank you @goodfellasthai , incorporated in [version 0.99.2.0](https://github.com/myspaghetti/macos-virtualbox/commit/2c0d789424cbb60ed8242d6c134a1663d8e542fb)

**Comment by Kamushy** [comment]
had the same issue, attempted to fix using the method by @FlorianLeMenn but it did not solve it, any help is appreciated 

kamushy#0992
