### ISSUE TITLE
tried on AMD ryzen 3600 with asus b550 mobo not working

### ISSUE THREAD

**Issue by rustPyth** [myspaghetti/macos-virtualbox#485]
thanks for the code, but
tried on AMD ryzen 3600 with asus b550 mobo on windows 10 not working.
the same computer with linux mint not working.
please pic
![VirtualBox_macOS_17_06_2021_10_11_41](https://user-images.githubusercontent.com/78695866/122367813-ae18de80-cf54-11eb-9e18-59fc176839ef.png)

**Comment by r8dhex** [comment]
I have a Ryzen 3600 and B550 as well. On Linux Mint, I was able to make it run with the following steps
1. CTRL-C to stop the sctript, then power off the VM
2. execute the following commands (replace the VM name, with the name of your VM)
```
VBoxManage modifyvm "Mac OSX Catalina" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff 
VBoxManage setextradata "Mac OSX Catalina" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3" 
VBoxManage setextradata "Mac OSX Catalina" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0" 
VBoxManage setextradata "Mac OSX Catalina" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple" 
VBoxManage setextradata "Mac OSX Catalina" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" 
VBoxManage setextradata "Mac OSX Catalina" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage modifyvm "Mac OSX Catalina" --cpu-profile "Intel Core i7-6700K"
```
3. restart the script with these parameters
`./macos-guest-virtualbox.sh check_default_virtual_machine and_all_subsequent_stages`
