### ISSUE TITLE
Script exits with "Error while starting the virtual machine."

### ISSUE THREAD

**Issue by omid3098** [myspaghetti/macos-virtualbox#487]
I've tried both with Cygwin and wsl2
script exits at ```stage: check_default_virtual_machine```

[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6734485/macOS_troubleshoot.txt)

**Comment by myspaghetti** [comment]
From the log:
```
00:00:02.593793 HM: HMR3Init: Attempting fall back to NEM: AMD-V is not available
```
See the readme section about NEM. There are many features that block VirtualBox from accessing AMD-V, like WSL2, Windows Sandbox, Device Guard, Core Isolation, and others.
