### ISSUE TITLE
Where are all the files stored?

### ISSUE THREAD

**Issue by bengroves2004** [myspaghetti/macos-virtualbox#492]
Where are the files used for the installation and the temporary files stored so i can delete them

**Comment by Masamune3210** [comment]
the script has a cleanup function iirc that you can call if you are done setting everything up

**Comment by myspaghetti** [comment]
The script writes files only to the shell's working directory. In case you have other files in that directory, you can run `./macos-guest-virtualbox.sh delete_temporary_files` to delete temporary files when the virtual machine is powered off. Generally speaking, every created file except `macOS.vdi` (or the `.vdi` with the name of your virtual machine) is a temporary file.
