### ISSUE TITLE
Once installed, can this Catalina instance be upgraded to Big Sur?  

### ISSUE THREAD

**Issue by Irishtiger77** [myspaghetti/macos-virtualbox#493]
The OS is prompting me to install Big Sur.  I have no idea if this is a good thing to do or if this scheme supports that.

**Comment by myspaghetti** [comment]
The VM can be upgraded to the latest version of Big Sur without issue. If you don't want any of the new features there's no real reason to update, performance is largely the same on all supported macOS versions, though High Sierra anecdotally and subjectively seems more responsive to me.
