### ISSUE TITLE
Change resolution after creating machine

### ISSUE THREAD

**Issue by Staubgeborener** [myspaghetti/macos-virtualbox#495]
Any chance to change the `resolution` parameter after setting up the macOS machine e.g. in virtualbox or with this script?

**Comment by myspaghetti** [comment]
`VBoxManage setextradata "macOS" "VBoxInternal2/EfiGraphicsResolution" "1920x1200"`

Replace "`macOS`" and "`1920x1200`" with the desired VM name and display resolution. The readme has a list of supported display resolutions, but non-supported might work too. If you want display scaling, you'll have to install OpenCore which is quite a bit more involved.
