### ISSUE TITLE
Highlight need for CygWin on Windows in README or script

### ISSUE THREAD

**Issue by jmynes** [myspaghetti/macos-virtualbox#497]
I had to read through (closed) Issue #426 before I realized I wasn't reading the README carefully enough.

The script seems to hang indefinitely when I let PowerShell or Git Bash try to handle things, but runs quickly and flawlessly on Cygwin.

Alternatively, adding a printout comment in the script that reminds people it's tested only for Cygwin (on Windows) may be just as useful, as it was otherwise difficult to figure out what was causing it to fail (such as missing dependencies, etc)

**Comment by jmynes** [comment]
Also, there's a typo "supprort" in the CPU section of the documentation.

**Comment by myspaghetti** [comment]
The typo was [fixed over a month ago](https://github.com/myspaghetti/macos-virtualbox/commit/1c28c6c98724e3e25a62f24842e3f5508cba479a), I hope there isn't an old version of the script floating around on the internet.

The very first line in the readme is "**`macos-guest-virtualbox.sh` is a Bash script**", I see no need to mention that Bash scripts do not work on `cmd.exe` or PowerShell. Git-Bash might be confusing to some but I think it's on Git to explain that Git-Bash is not Bash, but only a Git environment that behaves like Bash.
