### ISSUE TITLE
VM Black window - stuck on attempting automated recognition of Virtual machine graphical user interface

### ISSUE THREAD

**Issue by DavidLuong98** [myspaghetti/macos-virtualbox#499]
Here is the log and thanks in advance for the help. [macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/6873247/macOS_troubleshoot.txt)

```
Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.

Until the script completes, please do not manually interact with
the virtual machine.

Attempting automated recognition of virtual machine graphical user interface.
Please wait
Failed automated recognition of virtual machine graphical user interface.
Please press enter as directed.



```
 
![Errpng](https://user-images.githubusercontent.com/23180943/126884962-ad5ac650-1ae2-4090-b2f2-ab678e9af8d2.png)

**Comment by DavidLuong98** [comment]
@myspaghetti

**Comment by myspaghetti** [comment]
Duplicate - see [documentation](https://github.com/myspaghetti/macos-virtualbox#cpu-compatibility)

**Comment by DavidLuong98** [comment]
@myspaghetti would be helpful if you could point out in particular in the documentation where I may be going wrong.

**Comment by myspaghetti** [comment]
I linked to the exact paragraph.

>Unsupported features

>CPU compatibility

>macOS guests on VirtualBox are incompatible with some CPU models. If the guest macOS boot process hangs on “LoadKernelFromStream”, “EndRandomSeed”, or "EXITBS", see the documentation command regarding VirtualBox CPU profiles and CPUID settings. Some CPU models released in 2020 and later may fail to start or complete the installer, and may require manually adjusting the CPUID settings.

**Comment by myspaghetti** [comment]
I linked to the exact paragraph.

>Unsupported features

>CPU compatibility

>macOS guests on VirtualBox are incompatible with some CPU models. If the guest macOS boot process hangs on “LoadKernelFromStream”, “EndRandomSeed”, or "EXITBS", see the documentation command regarding VirtualBox CPU profiles and CPUID settings. Some CPU models released in 2020 and later may fail to start or complete the installer, and may require manually adjusting the CPUID settings.

The script output you pasted above also points to this exact section:

>This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.

**Comment by ImNotRice** [comment]
Hello, I already tried all the commands in documentation, with no luck. I have a Ryzen 7 2700X, and the boot process hangs on "EXITBS." How exactly should I "manually adjust the CPUID settings?" Thanks.
