### ISSUE TITLE
Getting error of packages

### ISSUE THREAD

**Issue by harpreet9629** [myspaghetti/macos-virtualbox#509]
Press enter to continue, CTRL-C to exit
Please make sure the following packages are installed
and that they are of the version specified or newer:

    coreutils 8.22   wget 1.14   gzip 1.5   unzip 6.0

Please make sure the coreutils and gzip packages are the GNU variant.

**Comment by myspaghetti** [comment]
The script by design does not require elevated privileges and should not be run with elevated privileges. It's expected that the system administrator manually install the dependencies for the script.

**Comment by harpreet9629** [comment]
I installed all packages but still get error

**Comment by myspaghetti** [comment]
Would you mind posting the output of these commands?
```
gzip --help 1>/dev/null
unzip -hh 1>/dev/null
csplit --help 1>/dev/null
wget --version 1>/dev/null
```

**Comment by harpreet9629** [comment]
its solved thank you
