### ISSUE TITLE
See the "documentation command" for further information.

### ISSUE THREAD

**Issue by ZeroOneZero** [myspaghetti/macos-virtualbox#511]
I redirected the command “./macos-guest-virtualbox.sh documentation” to get a better view of it. Then I formatted the file for you cause I noticed a few references to “documentation command” in your README.md didn’t redirect me anywhere. You could have those redirect users to this file.

I exported the stylized html version from Dillinger. I zipped it cause GitHub wouldn't allow me to add that file.
[documentation.md.zip](https://github.com/myspaghetti/macos-virtualbox/files/6922023/documentation.md.zip)

I'm including the md version as well.
[documentation.md](https://github.com/myspaghetti/macos-virtualbox/files/6922025/documentation.md)

I hope this helps because your script helped me. ~~Only one additional... how to get Big Sur?~~

**Comment by myspaghetti** [comment]
The point of the documentation command is to be live, offline documentation. Thank you for the effort but there is no need to put it online. The macOS VM may be updated to Big Sur through Software Update.
