### ISSUE TITLE
[PopOs 21.04] Broken install

### ISSUE THREAD

**Issue by dodalovic** [myspaghetti/macos-virtualbox#513]
Upon running, I'm getting this and nothing happens further:

![image](https://user-images.githubusercontent.com/6358061/128295822-9dad676c-03c2-4ef4-9ea4-36bd52113a18.png)

Virtual box 6.1

**Comment by myspaghetti** [comment]
Please see [documentation](https://github.com/myspaghetti/macos-virtualbox#cpu-compatibility) regarding CPU compatibility.
