### ISSUE TITLE
I need further instructions on how to start the installation

### ISSUE THREAD

**Issue by GrueseGehenRaus** [myspaghetti/macos-virtualbox#514]
What do I have to do with the "macos-guest-virtualbox.sh" file?

**Comment by myspaghetti** [comment]
macOS: install VirtualBox, install a package manager such as homebrew, pkgsrc, nix, or MacPorts and use it to install all the dependencies (except VirtualBox), run the script on an interactive `bash` shell (or `zsh` shell)

Linux: use your system's package manager to install all the dependencies, run the script on an interactive `bash` shell (or `zsh` shell)

Windows:

1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (with or without Extension Pack)
2. Install [Cygwin](https://cygwin.com/install.html) with `coreutils`  `bash` `gzip`  `unzip`  `wget` and `xxd` selected from the full package list
3. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
4. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`./macos-guest-virtualbox.sh`)

Windows may have Hyper-V installed or have other features or software that block VirtualBox from accessing VT-x/AMD-V hardware-supported virtualization. You may need to configure your system to allow VirtualBox access to hardware-supported virtualization.

Some CPUs are not supported. You may need to use one of the predefined CPU profiles or manually configure VirtualBox's CPUID settings.
