### ISSUE TITLE
I keep getting stuck here when installing, 

### ISSUE THREAD

**Issue by HiWhsp** [myspaghetti/macos-virtualbox#515]
![微信截图_20210808184129](https://user-images.githubusercontent.com/51939970/128630465-0e239a0e-0133-4b29-a54f-bc2cb3d47b4e.png)
the following is the final log
![111](https://user-images.githubusercontent.com/51939970/128630487-55658bd9-5848-4cc6-a68a-16bcfd592133.png)

**Comment by myspaghetti** [comment]
See the readme or release notes regarding "EXITBS"
