### ISSUE TITLE
Stuck on Boot Screen

### ISSUE THREAD

**Issue by harpreet9629** [myspaghetti/macos-virtualbox#516]
[macOS-2021-08-10-20-04-11.log](https://github.com/myspaghetti/macos-virtualbox/files/6962492/macOS-2021-08-10-20-04-11.log)

Before its running fine.

But suddenly it stuck on Boot Screen

**Comment by myspaghetti** [comment]
From the log:

`00:00:01.759106 HM: HMR3Init: Attempting fall back to NEM: AMD-V is not available`

It's likely that some Windows Update or administrator action enabled [one of the many features that block VirtualBox from using AMD-V](https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/virtualization-apps-not-work-with-hyper-v), such as Hyper-V, WSL2, Windows Sandbox, memory integrity protection, Application Guard, Credential Guard, Device Guard, and others.

You'll have to hunt around the Windows features and disable the ones that block VB from using AMD-V.
