### ISSUE TITLE
Machine Disappears from VirtualBox when Shutdown 

### ISSUE THREAD

**Issue by d86592** [myspaghetti/macos-virtualbox#517]
I installed the machine, it all went fine. I go through the setup process and when i am finished, I shut it down. I go back into VirtualBox to use it again a bit later, and there are no virtual machines in my menu. What should i do to be able to use the VM again? I am running PopOS 21.04 and installed Catalina.

**Comment by myspaghetti** [comment]
You probably ran the script as root, and then accessed VirtualBox as a regular user. The script is not meant to be run as root. Use the script to configure a new virtual machine and then attach the existing disk image to the newly-configured virtual machine. See the documentation for how to do this.
