### ISSUE TITLE
Virtuablox Error (supr3HardenedWinReSpawn)

### ISSUE THREAD

**Issue by Zazou89** [myspaghetti/macos-virtualbox#518]
Hello,
I'm trying to install the script but I have an error :

![image](https://user-images.githubusercontent.com/206181/129479775-25985d7a-6ceb-4dac-8fc7-b0314c992a5e.png)

Do you know why ?
Thank you !

**Comment by Masamune3210** [comment]
Literally tells you the problem in the error box, the kernel driver is either not installed correctly or is stuck. Try rebooting
