### ISSUE TITLE
iMessage/iCloud not working

### ISSUE THREAD

**Issue by Xoroxa** [myspaghetti/macos-virtualbox#519]
Hey,

I changed the values in the config of the script to custom values, however, I still can't sign in to iMessage or iCloud. I ran iMessageDebug and it stated that I had all the values but it had stated that the "SmUUID" failed, the "System-ID" failed, and the "BoardSerialNumber" was (null). Is this is an issue with one of the values I set?

Thanks

**Comment by Xoroxa** [comment]
Hey, so that fixed the BoardSerielNumber, however, the SystemID is still equal to failed. 
![image](https://user-images.githubusercontent.com/34523791/129983149-50074ad7-09c0-4919-b1e3-27ad14eadcdf.png)
![image](https://user-images.githubusercontent.com/34523791/129983173-af02141e-06b7-40d0-b332-5a6e33cb55d1.png)

**Comment by myspaghetti** [comment]
iMessage records the system ID when you first attempt to log in. If you subsequently change the system ID, it will report an error. While you could find some guides on the internet for resetting iMessage activation, it might be quicker to double-check the values you entered in the script and then creating a new VM. I recommend not starting iMessage until all the parameters show up correctly in System Profiler.
