### ISSUE TITLE
August 21, 2021: What are the latest updates regarding having this script work with WSL2?

### ISSUE THREAD

**Issue by jmaldon1** [myspaghetti/macos-virtualbox#521]
Really looking forward to using this script, but I keep reading how you cannot be running WSL2 on your computer for it to work, due to issues with virtualization. Just wondering what are the latest updates/timelines on having this script work?

**Comment by Masamune3210** [comment]
The timeline is out of our hands for that, as it hinges on whenever Microsoft decides nested virt is stable and ready for public

**Comment by myspaghetti** [comment]
* You could upgrade Windows 10 to any Windows 10 Insider Preview build 21362 or higher and use WSLg (WSL2 with a GUI)
* When Windows 10 build 21362 or higher becomes the Release (with a capital R) release, it will gradually be pushed to all compatible devices (probably nearly all devices that run Windows 10) and almost everyone will be able to enjoy WSLg
* You could [follow this tutorial](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/) and build your own WSL2 kernel which supports nested virtualization.

**Comment by jmaldon1** [comment]
Got it. So microsoft hasnt said any timelines of when nested virt will be released? Or when any of these windows builds will be ready?

**Comment by myspaghetti** [comment]
[21H2](https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/).

>Broad availability of Windows 10, version 21H2 will begin later in the second half of this calendar year. [2021]

**Comment by myspaghetti** [comment]
Well you can get the Dev build and the Beta build right now through Windows Insider. The "Release" release is scheduled for [21H2](https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/):

>Broad availability of Windows 10, version 21H2 will begin later in the second half of this calendar year. [2021]

**Comment by myspaghetti** [comment]
Well you can get the Dev build and the Beta build and the Release Preview build, with WSLg, right now through Windows Insider. The "Release" release is scheduled for [21H2](https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/):

>Broad availability of Windows 10, version 21H2 will begin later in the second half of this calendar year. [2021]

**Comment by myspaghetti** [comment]
Looks like I was wrong, the Dev build and Beta build are now Windows 11. [There are no plans to ship WSLg on Windows 10.](https://github.com/microsoft/wslg/issues/347#issuecomment-877695975)

**Comment by jmaldon1** [comment]
Ah ok, seems like Windows 11 will be released late 2021 or early 2022.

**Comment by myspaghetti** [comment]
This is unexpected for me. I thought WSLg was coming to Windows 10. Now that I know that it isn't, I guess Cygwin and WSL1 support are here to stay.

**Comment by jmaldon1** [comment]
> This is unexpected for me. I thought WSLg was coming to Windows 10. Now that I know that it isn't, I guess Cygwin and WSL1 support are here to stay.

Would there need a separate windows 11 script?

**Comment by myspaghetti** [comment]
The script runs fine on WSLg, I just wanted to drop Cygwin and WSL1 so I can remove all the Windows-specific code.

**Comment by jmaldon1** [comment]
> The script runs fine on WSLg, I just wanted to drop Cygwin and WSL1 so I can remove all the Windows-specific code.

I guess here to stay until windows 11 becomes widely adopted, huh?

**Comment by myspaghetti** [comment]
I'll see if `vboxdrv` can be built against the WSLg kernel.

**Comment by myspaghetti** [comment]
Good news, it works. Bad news, it's really slow.

See issue #523
