### ISSUE TITLE
Upgrade to newer MacBook Pro in script

### ISSUE THREAD

**Issue by enigma0456** [myspaghetti/macos-virtualbox#527]
HP Probook 4440s i5 16gb running Xubuntu 20.04 Used the script to generate a Catalina machine. That machine upgraded to Big Sur with subsequent updates. After learning about MacOS and being stuck with small disk and unremovable installers I generated a usb installer, cloned the machine, deleted the disk, created a bigger blank disk and installed Big Sur from the usb. Great fun learning about MacOS and hope to have a real one some day. Meanwhile, studying the specs, I realize that the template is a MacBook Pro 11.2 circa 2014. Since my vm runs well (the sound even works well) I hope to keep upgrading it - maybe Monterey this Fall but because the template is a 2014 machine I expect that Apple will somehow disallow upgrades for it in the near future. What would be required to bump up the extra data specs to present a newer MacBook as the vm? Some of the specs seem to just need a value (NO_DEVICE_SN for example) but others like the DmiBoardProduct look to be very specific. What would be required to move up to maybe a 2016 or even later machine?

**Comment by myspaghetti** [comment]
Sure, if the specs for Monterey require updating the default values in the script they will be updated in future releases.

As far as I'm aware Monterey installs fine with the current configuration, and Apple has not published the system requirements yet. They did [restrict some features](https://www.apple.com/macos/monterey-preview/) to newer models. These features require Bluetooth and WiFi, which aren't available on VirtualBox macOS VMs anyway. If you want to use these features I recommend using hardware passthrough on KVM.
