### ISSUE TITLE
Stuck on installation, help

### ISSUE THREAD

**Issue by qhu91it** [myspaghetti/macos-virtualbox#532]
My laptop: Dell G3 | Intel(R) Core(TM)
 i7-8750H CPU @ 2.20GHz   2.21 GHz | 16GB
Windows 10
VirtualBox 6.1.26
tesseract v5
---------------------------
I stuck on this step, don't know what to do next, if I shutdown manually then the scrip can show completed but virtual box can not boost to macos.
![image](https://user-images.githubusercontent.com/5744633/134780378-d6299895-0a59-4640-a7ab-2d24544c8b30.png)

**Comment by myspaghetti** [comment]
The script is not compatible with minigw. Those prompts that say "Press enter when..." are supposed to be interactive.
