### ISSUE TITLE
Is the download really slow?

### ISSUE THREAD

**Issue by ha-ves** [myspaghetti/macos-virtualbox#533]
Talking about Apple as a huge company, of course, their CDN would be as fast as possible. Is it the limitation of wget?

**Comment by myspaghetti** [comment]
Download speed varies. From personal experience I've seen it go up to several megabytes (tens of megabits).

**Comment by myspaghetti** [comment]
Download speed varies. From personal experience I've seen it go up to several megabytes (tens of megabits) per second.
