### ISSUE TITLE
Time Machine support

### ISSUE THREAD

**Issue by ilippert** [myspaghetti/macos-virtualbox#536]
It would be so great, if I could attach a USB storage to my Linux system on which a time machine backup can be found - and then use it to restore it in the virtual box. Any chance this might be possible?

**Comment by myspaghetti** [comment]
I have not tested this myself, but as far as I recall Time Machine works fine off of local area network storage, so attaching the storage to the host and exposing it to the guest as local area network storage should work.

**Comment by ilippert** [comment]
Hm, thank you, uuh, I have a simple external USB disk. My linux system finds it. Exposing it as a Shared Folder in Virtual Box did not make it findable for macOS.

**Comment by myspaghetti** [comment]
You should configure your Linux host as a Time Machine drive with netatalk and avahi. See for example [this tutorial](https://www.grizzly-hills.com/2019/11/02/ubuntu-19-10-setting-up-time-machine/). The macOS guest should have a virtual network adapter that is exposed to the host.

**Comment by ilippert** [comment]
For anybody looking into this - my solution was to attach the USB powered time machine hard disk in the VirtualBox preferences to the macOS virtual machine, and voila, it got recognised.
