### ISSUE TITLE
Catalina fails to boot for some reason, but doesn't say why

### ISSUE THREAD

**Issue by quisys** [myspaghetti/macos-virtualbox#539]
After the part of the script where everything is downloaded, the ISO is split, and the machine boots for the first time, I am met with this cryptic string of errors. Nothing further happens.

https://www.photobox.co.uk/my/photo/full?photo_id=504143587701

Any advice is appreciated. I'm running with zsh under Artix Linux.

**Comment by Masamune3210** [comment]
Photo link doesnt work, just redirects to the main page of the website

**Comment by quisys** [comment]
![macerror](https://user-images.githubusercontent.com/56238271/136664535-78b380fa-b31c-4008-8dfe-ba44686060fd.png)
Forgot I could attach files here :P

**Comment by myspaghetti** [comment]
See release notes, readme, or documentation about `EXITBS` and CPU compatibility.
