### ISSUE TITLE
[suggestion] Add an option to use aria2c to download files

### ISSUE THREAD

**Issue by EvilSquirrelGuy** [myspaghetti/macos-virtualbox#541]
Hi, i was wondering if it would at all be possible to allow the script to use `aria2c` as opposed to `wget` to download files. This would allow for faster download times as the program splits downloaded files over multiple parallel connections. 

To my knowledge, `aria2c` is supported on Windows as well as Linux so it shouldn't cause platform incompatibilities.

**Comment by myspaghetti** [comment]
Thanks for the suggestion. Currently I have no plans to implement this or accept pull requests for changing the download software. From (very brief) testing that I just did, multiple connections to the Apple SWCND servers cannibalized each other's download speed, so there's probably no benefit to using multiple connections.

**Comment by myspaghetti** [comment]
Thanks for the suggestion. Currently I have no plans to implement this or accept pull requests for changing the download software. From (very brief) testing that I just did, multiple connections to the Apple SWCDN servers cannibalized each other's download speed, so there's probably no benefit to using multiple connections.
