### ISSUE TITLE
Create macOS Big Sur installer in macOS RECOVERY ( without Full macOS or VM )

### ISSUE THREAD

**Issue by heinthanth** [myspaghetti/macos-virtualbox#543]
I've read the scripts and able to create macOS installer USB using `asr`, `diskutils` in recovery shell ( like the script use ). 

But with macOS big sur, I only get `InstallAssistant.pkg`. How can I use it to create bootable USB installer in recovery shell.

( In real mac, we can just install the pkg and `/Applications/Install*.app/Contents/Resouces/createinstallationmedia`. But dunno how in recovery shell. )

Not an issue with the script. Just want to figure out and contribute.

**Comment by myspaghetti** [comment]
I tried extracting `InstallAssistant.pkg` in the recovery environment but it didn't extract `SharedSupport.dmg` so obviously the installer wouldn't run, and I have a feeling that even if it did extract successfully it would have failed like previous versions. Still, I'm open to this method if it ever actually works.
