### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by benni347** [myspaghetti/macos-virtualbox#545]
Hello,
So when I run the script it's stuck on Press enter when the Language window is ready. and nothing happens in the VBox and it's already been there since 3 hours. 
![image](https://user-images.githubusercontent.com/64905406/139506597-47f7309f-ed90-4dfb-bb8f-3012e201c490.png)

**Comment by myspaghetti** [comment]
If booting fails, exit the script by pressing CTRL-C then see the documentation for information about applying different CPU profiles in the section `CPU profiles and CPUID settings`
