### ISSUE TITLE
No Graphics 

### ISSUE THREAD

**Issue by mendelsphotography** [myspaghetti/macos-virtualbox#546]
hi there is no graphics I tried installing additional Guest ISO but it asked me for permiosn to run and then after allowing does not work still and Imovie says no graphics and cant open

**Comment by myspaghetti** [comment]
For GPU acceleration you will have to either use High Sierra with a compatible physical Nvidia GPU and GPU passthrough on KVM, or any recent version of macOS and a physical Intel CPU/GPU that supports Intel GVT-g passthrough on KVM. No support is offered for configuring KVM.

**Comment by mendelsphotography** [comment]
so i can do like windows I need an actual graphics card not Intel based Gpu

**Comment by myspaghetti** [comment]
You have to have either High Sierra and a supported Nvidia graphics card, or any recent version of macOS and a supported Intel CPU/GPU with Intel GVT-g.

**Comment by myspaghetti** [comment]
You have to have either High Sierra and a supported Nvidia graphics card, or any recent version of macOS and a supported Intel CPU/GPU with Intel GVT-g or two GPUs of which one supports GVT-d.

**Comment by mendelsphotography** [comment]
ok thanks
