### ISSUE TITLE
access to apple store

### ISSUE THREAD

**Issue by fhenryco** [myspaghetti/macos-virtualbox#548]
Is it possible (legal?) to register to have access to the app store with this VM ?

**Comment by myspaghetti** [comment]
The Apple Store app is not available on Intel Macs.

**Comment by fhenryco** [comment]
So this VM is only interesting on a MAC hardware since otherwise  it cannot even be used to test IoS app from the appstore, right ?

**Comment by fhenryco** [comment]
or is there another way (alternative to appstore ?, or the appstore to get the app on an iphone and then transfer the app to the VM ?) to get those apps ?

**Comment by myspaghetti** [comment]
* The App Store and the Apple Store are two different stores, the title says Apple Store but the comment says App Store.
* Intel Macs have never run iOS apps. VirtualBox runs macOS virtual machines only with the Intel kernel/binaries.
* You appear to be looking for either an iOS virtual machine or an M1 (Apple Silicon) macOS virtual machine. This project about for VirtualBox Intel macOS virtual machines.

**Comment by fhenryco** [comment]
OK so let me specify that my first question was only about the app store for intel MAC not iOS  : i dont understand why, but with your VM even after all those steps to have  my Apple Id and so on (defining a passwd , answering questions), verify with my email, then i'm not able to sign in with same login and passwd i just defined 2 minutes before so i cant access the app store (the Intel MAC one) so i was wondering wether i'm blocked because my PC hosting the VM is not identified as a regular MAC (?)

**Comment by myspaghetti** [comment]
Apple IDs cannot be registered with the VM, registration requires NVRAM parameters and other hardware configuration that is not available on the VM.

You don't need an Apple ID to access the App Store, but you can use an existing Apple ID if you want to.
