### ISSUE TITLE
How to edit set_variables?

### ISSUE THREAD

**Issue by Ameryss** [myspaghetti/macos-virtualbox#553]
Im very new to emulating so please excuse me if this is dumb. I dont want to use catalina but I dont know how to edit set_variables. I use windows 10. If anyone answers this, please be descriptive because im very new to this. Thank you.

**Comment by myspaghetti** [comment]
1. [Download the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
2. Use your favorite text editor to edit line 19 from `macOS_release_name="Catalina"` to the version you want, for example `macOS_release_name="HighSierra"` and save the file

or

2. Edit the file from the shell, for example with `sed -i "19s/Catalina/HighSierra/1" macos-guest-virtualbox.sh`
