### ISSUE TITLE
legal

### ISSUE THREAD

**Issue by baptx** [myspaghetti/macos-virtualbox#557]
I noticed there was no discussion on the legality of using this script. Is it legal to use it on non-Apple hardware?
It looks like it is not (in this case it could be mentioned in the readme to inform users at least):
https://serverfault.com/questions/992776/using-macos-as-a-vm-and-a-legal-copy
https://www.quora.com/How-can-I-legally-run-MacOS-in-a-virtual-machine
https://www.quora.com/Is-MacOS-free-to-run-on-a-virtual-machine
https://www.quora.com/Is-it-illegal-to-run-OSX-in-a-virtual-machine-I-remember-Apple-saying-their-OS-was-free

**Comment by myspaghetti** [comment]
Please don't use quora as a source for anything ever.

**Comment by baptx** [comment]
@myspaghetti People are using "Apple’s EULA" as the source. So there is no longer a legal issue when using it on non-Apple hardware?

**Comment by Masamune3210** [comment]
No, it's definitely a issue. It expressly states in the terms of use for Mac os that it's only free for use on apple hardware. Most people just don't care as unless you are doing it for sale or on a large scale apple doesn't really care
