### ISSUE TITLE
legal

### ISSUE THREAD

**Issue by baptx** [myspaghetti/macos-virtualbox#558]
I noticed my issue https://github.com/myspaghetti/macos-virtualbox/issues/557 was deleted but the question was not answered. It would be useful to have an answer / discussion as a reference for people who have the same question instead of doing censorship by removing the issue, which is clearly not nice and welcoming for an open-source project that should be transparent with the community.
Here was the question:
Is it legal to use this script to setup a macOS virtual machine on non-Apple hardware?
It looks like it is not so it could be useful to inform users in the README but maybe it changed recently or the way the script works is legal.
Here are several related discussions mentioning Apple's EULA as the source:
https://serverfault.com/questions/992776/using-macos-as-a-vm-and-a-legal-copy
https://www.quora.com/How-can-I-legally-run-MacOS-in-a-virtual-machine
https://www.quora.com/Is-it-illegal-to-run-OSX-in-a-virtual-machine-I-remember-Apple-saying-their-OS-was-free
https://www.quora.com/Is-MacOS-free-to-run-on-a-virtual-machine

**Comment by myspaghetti** [comment]
I asked you before, do not use quora for legal advice.
