### ISSUE TITLE
Trouble with apple certificates

### ISSUE THREAD

**Issue by magictom42** [myspaghetti/macos-virtualbox#560]
I am having trouble with wget during download of the su catalog in the macos-virtualbox script on a Mac (Catalina). When I start wget isolated, the log file says:

--2021-11-20 16:47:38--  https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Loaded CA certificate '/etc/ssl/cert.pem'
Certificates loaded: 132
Resolving swscan.apple.com... 2.19.100.101
Caching swscan.apple.com => 2.19.100.101
Connecting to swscan.apple.com|2.19.100.101|:443... connected.
Created socket 6.
Releasing 0x00007fcfd275d470 (new refcount 1).
ERROR: The certificate of 'swscan.apple.com' is not trusted.

I tried to work around this wget step by downloading the file via Firefox. This worked, but later on, when it comes to the installation within the virtual machine, I get errors saying that some installation files are damaged. I have installed the ca-certificate package, but that didn't help. Any idea?

**Comment by myspaghetti** [comment]
If you're on a Debian-based system (like Ubuntu) update your trusted certificates with `sudo dpkg-reconfigure ca-certificates`

If you're on a different type of system either find a way to update the system's certificates or edit line `257` in the script to allow untrusted certificates: `wgetargs="--quiet --continue --show-progress --timeout=60 --no-check-certificate"`

I do recommend trying to load the correct certificates, it'll generally make your system more secure.

**Comment by magictom42** [comment]
@myspaghetti Thanks, I got it working now! I used the --no-check-certificate option.
