### ISSUE TITLE
Cannot come out of boot loop after updating to Monterey (Tried installing it in diff volume without success)

### ISSUE THREAD

**Issue by gyani-sunkara** [myspaghetti/macos-virtualbox#561]
Trying to update to Big Sur or Monterey for last two days, 
Can't find Big Sur on app store
Monterey is in infinite boot loop
-> When Monterey is installed in a fresh volume added through VM it goes into loop while booting from the new volume
-> Booting from the old existing volume just gets me to Catalina prior to installation
Any help is appreciated

**Comment by joaonunatingscode** [comment]
I'm also having this problem

**Comment by gyani-sunkara** [comment]
I am able to download Big Sur from [MacOS Archieve](https://support.apple.com/en-in/HT211683)
[Direct Big Sur link](https://apps.apple.com/us/app/macos-big-sur/id1526878132?mt=12)

Trying out installation

**Comment by myspaghetti** [comment]
From the [very little testing that was reported on the issue tracker,](https://github.com/myspaghetti/macos-virtualbox/issues/484#issuecomment-964997875) installing Monterey from Catalina onto an empty volume using the default configuration (mainly two CPU cores) boots and works, though CalculonPrime reported somewhat frequent crashes, either every few hours or when running certain apps.

**Comment by gyani-sunkara** [comment]
Big Sur installed and booted successfully
Monterey still in boot loop

Closing issue

**Comment by CalculonPrime** [comment]
Why was this issue closed?  It was opened against Monterey and the last comment admits Monterey still has the problem.

**Comment by myspaghetti** [comment]
Because the script doesn't support Big Sur nor Monterey. Both work, but they need to be installed manually and not through the script.

**Comment by CalculonPrime** [comment]
So you mean you've found a workaround to a Monterey machine rebooting periodically with 4 cpus?  Or you mean you just run it with 2 or fewer cpus?  Because, no matter what I do or how I configure the vbox file, it always reboots for me in a short time with > 2 cpus.

**Comment by myspaghetti** [comment]
The script doesn't support Monterey. This is an issue tracker for the script. Since this is not an issue with the script, the issue is closed.
