### ISSUE TITLE
how to run the script

### ISSUE THREAD

**Issue by LeeChunJun** [myspaghetti/macos-virtualbox#563]
Hello, I have no idea how to run this "macos-guest-virtualbox.sh", so i first download cygwin64 and then install it in my windows 10. 
Is it right way to run this script?

**Comment by myspaghetti** [comment]
* Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (with or without Extension Pack)
* Install [Cygwin](https://cygwin.com/install.html) with `coreutils`  `bash` `gzip`  `unzip`  `wget` and `xxd` selected from the full package list (and optionally `tesseract-ocr` and `tesseract-ocr-eng`)
* Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
* Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`./macos-guest-virtualbox.sh`)

**Comment by LeeChunJun** [comment]
thank you for help me. And i find "dmg2img" in Dependencies. Do i need install it in my cygwin?

**Comment by myspaghetti** [comment]
`dmg2img` is [not currently available on Cygwin](https://cygwin.com/cgi-bin2/package-grep.cgi?grep=dmg2img&arch=x86_64) so thet script downloads it automatically.

**Comment by LeeChunJun** [comment]
thank you. I have installed Mac in my virtual box.
