### ISSUE TITLE
Disable SIP option 77 is not working with High Sierra

### ISSUE THREAD

**Issue by ssavva05** [myspaghetti/macos-virtualbox#564]
Thanks for the script, it is ideal for my needs! I face an issue with flag 77 to disable SIP in High Sierra VM is there any other way to disable SIP in High Sierra?

**Comment by myspaghetti** [comment]
The value needs to be set in NVRAM from the EFI Internal Shell. Press ESC when the virtual machine boots and select boot options and the EFI Internal Shell, then let the `startup.nsh` script run or manually set the NVRAM value.

**Comment by ssavva05** [comment]
> The value needs to be set in NVRAM from the EFI Internal Shell. Press ESC when the virtual machine boots and select boot options and the EFI Internal Shell, then let the `startup.nsh` script run or manually set the NVRAM value.

My vm is looping the bios options and don't let me choose the boot drive. I have to change some settings I guess.

**Comment by ssavva05** [comment]
> The value needs to be set in NVRAM
what is the exact line that I have to add?
