### ISSUE TITLE
Change CPU profile for AMD processor

### ISSUE THREAD

**Issue by toelke** [myspaghetti/macos-virtualbox#566]
Hey,

when running the script I got an error:

```
Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49
```

I could fix it using `vboxmanage modifyvm macOS --cpu-profile "Intel Xeon X5482 3.20GHz"`.

I have a:

```
processor	: 15
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 96
model name	: AMD Ryzen 7 PRO 4750U with Radeon Graphics
```

**Comment by CDeLeon94** [comment]
I added
```
( VBoxManage modifyvm "${vm_name}" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff >/dev/null 2>&1 )
( VBoxManage modifyvm "${vm_name}" --cpu-profile "Intel Core i7-6700K" >/dev/null 2>&1 )
```
after line 677 of the script, just before `startvm` is called. 

This seemed to be the most straight forward way to get everything to run correctly. 

I wasn't sure about the procedure for setting the cpu-profile otherwise.

**Comment by matusnovak** [comment]
> ( VBoxManage modifyvm "${vm_name}" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff >/dev/null 2>&1 )
> ( VBoxManage modifyvm "${vm_name}" --cpu-profile "Intel Core i7-6700K" >/dev/null 2>&1 )

I can confirm that this also works for the AMD Threadripper 3970X
