### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by kiatchun** [myspaghetti/macos-virtualbox#569]
I installed all the packages with Cygwin, but the script is still not working. 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/93459510/147031072-98d6bb11-2f6c-4ece-979b-a4f48f017d1c.png">

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

Please post the output of the following commands:

```
gzip --help 2>/dev/null
unzip -hh 2>/dev/null
csplit --help 2>/dev/null
wget --version 2>/dev/null
```

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report!

Please post the output of the following commands:

```
[[ -z $( gzip --help 2>/dev/null ) ]] && echo gzip failed
[[ -z $( unzip -hh 2>/dev/null ) ]] && echo unzip failed
[[ -z $( csplit --help 2>/dev/null ) ]] && echo coreutils failed
[[ -z $( wget --version 2>/dev/null ) ]] && echo wget failed
```

**Comment by kiatchun** [comment]
I reinstalled cygwin and it is working now. I guess it was a problem with my cygwin install.
