### ISSUE TITLE
Can't boot into the installer, known situation

### ISSUE THREAD

**Issue by PeterDaveHello** [myspaghetti/macos-virtualbox#572]
I'm testing this script on Linux Mint 20.3, which is based on Ubuntu 20.04, with command: `macos-guest-virtualbox.sh`, but just got stocked here, even though I retried the process several times, same problem every time:

![image](https://user-images.githubusercontent.com/3691490/149632456-7a2b1915-829e-4156-b62c-a91eee652981.png)

There's no error from the shell script, but every time it starts to boot the VM, there are errors in VM's screen that I can't easily understand.

Not sure if anyone got the same situation or is there anything I can do to dig deeper? Thanks!

shell script output:

```
Catalina_BaseSystem.dmg --> Catalina_BaseSystem.img


decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...             100.00%  ok
opening partition 5 ...             100.00%  ok
opening partition 6 ...             100.00%  ok
opening partition 7 ...             100.00%  ok

Archive successfully decompressed as Catalina_BaseSystem.img
Converting from raw image file="Catalina_BaseSystem.img" to file="Catalina_BaseSystem.vdi"...
Creating dynamic image with size 2138558464 bytes (2040MB)...


stage: create_bootable_installer_virtual_disk
Creating Catalina installation media virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 12b265b6-ec0b-408c-9b72-7c0be66bf303

stage: populate_bootable_installer_virtual_disk

Creating VirtualBox 6 virtual ISO containing macOS Terminal script
for partitioning and populating the bootable installer virtual disk.


Starting virtual machine "macOS".
This should take a couple of minutes. If booting fails, exit the script by
pressing CTRL-C then see the documentation for information about applying
different CPU profiles in the section CPU profiles and CPUID settings.

Until the script completes, please do not manually interact with
the virtual machine.

Attempting automated recognition of virtual machine graphical user interface.
Please wait ...
```

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. The exit error message indicates CPU incompatibility. [I've chosen not to support incompatible CPUs.](https://github.com/myspaghetti/macos-virtualbox#cpu-compatibility) You may try using one of the six built-in CPU profiles provided by VirtualBox, or manually specifying your own CPUID settings. Mind that, unlike QEMU that lets you use CPU mnemonics (and hence makes it easy to match your physical CPU properties with the virtual CPU properties), VirtualBox requires [specifying the hex codes for the CPUID leaves](https://en.wikipedia.org/wiki/CPUID) which is a pain and the main reason I chose not to support this feature.

**Comment by PeterDaveHello** [comment]
@myspaghetti thanks for the help, I found that CPU profile "Intel Xeon X5482 3.20GHz" will work ;)

**Comment by mherrmann** [comment]
Had the same problem on an AMD 5950x. The following command got me one step further:

    VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
