### ISSUE TITLE
link to download dmg2img not working

### ISSUE THREAD

**Issue by GuihongWang** [myspaghetti/macos-virtualbox#575]
link to download dmg2img not working 
but i found a backup on the weyback machine，but archive.org is not accessible in some areas

**Comment by myspaghetti** [comment]
Link's back up now but I'll keep this bug open while I procrastinate about finding a more reliable solution.

**Comment by GDWGH** [comment]
> Link's back up now but I'll keep this bug open while I procrastinate about finding a more reliable solution.

Like putting it on GitHub? I have a working (but not permanent) [server](http://build.marisa.ml)

**Comment by myspaghetti** [comment]
@Lekensteyn would you be inclined to host win32 signed binaries of [dmg2img](https://github.com/Lekensteyn/dmg2img) on github?

**Comment by GDWGH** [comment]
and what is this ![image](https://user-images.githubusercontent.com/57795156/152334403-9e0f16f6-123b-425d-8500-1c8abc2e95c6.png) 　@myspaghetti

**Comment by myspaghetti** [comment]
@GDWGH would you mind starting a different issue for the new question?

**Comment by GDWGH** [comment]
> @GDWGH would you mind starting a different issue for the new question?

I will (but I'm not used to reopening an issue)

**Comment by thispsj** [comment]
Hi @myspaghetti if Lekensteyn doesn't reply then I'm ready to host on GitHub.

**Comment by uakbr** [comment]
Hey, I just ran into this problem as well

**Comment by Danik1601** [comment]
> Hey, I just ran into this problem as well

Right now you can manually download it from the abovementioned [Wayback Machine](https://web.archive.org/web/20190322013244/http://vu1tur.eu.org/tools/dmg2img-1.6.6-win32.zip) and unpack manually in your script folder. The script is smart enough to use this manually provided package

**Comment by myspaghetti** [comment]
Wayback Machine workaround implemented in version 0.99.1.8

**Comment by GuihongWang** [comment]
> Wayback Machine workaround implemented in version 0.99.1.8

but in my region    i can't use wayback machine

**Comment by laiTM2007** [comment]
I think you can host now - after all, Lekensteyn didn't reply, and he doesn't need to host an old version specifically

> Hi @myspaghetti if Lekensteyn doesn't reply then I'm ready to host on GitHub.

**Comment by PaiGack** [comment]
可以使用这个地址下载 http://vu1tur.eu.org/tools/dmg2img-1.6.7-win32.zip
