### ISSUE TITLE
Can't boot when I use a different CPU profile

### ISSUE THREAD

**Issue by GDWGH** [myspaghetti/macos-virtualbox#576]
![image](https://user-images.githubusercontent.com/57795156/152334403-9e0f16f6-123b-425d-8500-1c8abc2e95c6.png)     when i first startup from other cpu profile

**Comment by GDWGH** [comment]
I use CPU profile marked on the red line

**Comment by myspaghetti** [comment]
The six preconfigured CPU profiles aren't compatible with every (or even most) CPUs, if the macOS VM doesn't boot with no profile or with none of the preconfigured profiles, you might have to se tthe [CPUID](https://en.wikipedia.org/wiki/CPUID) manually with the [VirtualBox `--cpuid` option](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport). No support is offered for that feature.

**Comment by GDWGH** [comment]
> The six preconfigured CPU profiles aren't compatible with every (or even most) CPUs, if the macOS VM doesn't boot with no profile or with none of the preconfigured profiles, you might have to se tthe [CPUID](https://en.wikipedia.org/wiki/CPUID) manually with the [VirtualBox `--cpuid` option](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport). No support is offered for that feature.

How do I set the CPUID? I can't set it up

**Comment by myspaghetti** [comment]
Sorry, I don't offer support for CPUID settings

**Comment by GDWGH** [comment]
> Sorry, I don't offer support for CPUID settings

so which command can I set the CPUID?

**Comment by GDWGH** [comment]
When I tried the new configuration it worked thanks@myspaghetti ![20220204093228.png](https://user-images.githubusercontent.com/57795156/152457750-fb629b47-3ffb-48e0-8f57-ebaf253ecf29.png)
