### ISSUE TITLE
Error while starting the virtual machine

### ISSUE THREAD

**Issue by alphaonex86** [myspaghetti/macos-virtualbox#577]
Hi,
I'm with debian sid, when I try your script I have:
stage: check_default_virtual_machine

Checking that VirtualBox starts the virtual machine without errors.
Error while starting the virtual machine.
Exiting.

And When I try start the VM created I have:
The virtual machine 'macOS' has terminated unexpectedly during startup with exit code 1 (0x1).

Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

**Comment by Masamune3210** [comment]
This has nothing to do with the script, Get VirtualBox into a sane state again and make sure other VM's are working first

**Comment by myspaghetti** [comment]
Googling "MachineWrap" leads me to believe the VirtualBox driver `vboxdrv` is not properly configured or installed.
