### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by Sorinaki** [myspaghetti/macos-virtualbox#582]
echo -e "\nError: Could not configure virtual machine \"${vm_name}\"."
    echo -e "Please execute the stage ${low_contrast_color}configure_vm${default_color} again before resuming the script"
    echo -e "as described in the documentation.\n"
    echo "Exiting."
- what documentation? Not that I can't see what the problem is, but the error is patronizing the user, implying that he did not do his part.

**Comment by myspaghetti** [comment]
I'm sure you'll find this reply patronizing, but I have no idea how you could have reached any stage of the script without seeing at least two messages telling you how to access the documentation.

The error message doesn't mean "why didn't you read the documentation?", it means "if you want to know how to resume the script, please read the documentation."

**Comment by myspaghetti** [comment]
Ommited mention of documentation from error message in commit 48f33a7
