### ISSUE TITLE
iMessage again, sorry :/

### ISSUE THREAD

**Issue by pnix44** [myspaghetti/macos-virtualbox#584]
I know this has been mentioned multiple times, but I am pulling out my hair trying to figure this out. I have spent the last 5 days trying every method described. I have generated SMBIOS files using https://github.com/corpnewt/GenSMBIOS , I have used Clover configurator to generate SMBIOS config, and I have even taken the exact config from a macbook pro trying to get this to work. I followed the previous threads and documentation provided from the commands and I still receive the error, "username or password is incorrect" Any thoughts?

**Comment by myspaghetti** [comment]
Probably the username or password is incorrect.

**Comment by pnix44** [comment]
Password was correct. The issue was not reloading the EFI settings after the install. That part was somewhat confusing. I thought I only needed to do that if I didn't preload the genuine mac settings before running the installer.

**Comment by myspaghetti** [comment]
Weird that you got "username or password is incorrect" when the error message is usually "Could not sign in" and "An error occurred during activation."

**Comment by TheAwesomeGcdm** [comment]
> Password was correct. The issue was not reloading the EFI settings after the install. That part was somewhat confusing. I thought I only needed to do that if I didn't preload the genuine mac settings before running the installer.

How did you go about doing that? I can’t seem to figure out how to even see my config files on my efi.

**Comment by myspaghetti** [comment]
When resetting or powering up the VM, immediately press Esc when the VirtualBox logo appears. This boots into the EFI Internal Shell or the boot menu. If the boot menu appears, select "Boot Manager" and then "EFI Internal Shell" and then allow the `startup.nsh` script to execute automatically, applying the NVRAM variables before booting macOS.
