### ISSUE TITLE
How can I change display resolution after install the system? 

### ISSUE THREAD

**Issue by GuihongWang** [myspaghetti/macos-virtualbox#587]

**Comment by myspaghetti** [comment]
Duplicate of #542

>`VBoxManage setextradata "macOS" "VBoxInternal2/EfiGraphicsResolution" "1920x1200"`

>Replace "`macOS`" and "`1920x1200`" with the desired VM name and display resolution. The readme has a list of supported display resolutions, but non-supported might work too. If you want display scaling, you'll have to install OpenCore which is quite a bit more involved.
