### ISSUE TITLE
Attempting automated recognition of virtual machine graphical user interface.

### ISSUE THREAD

**Issue by leoheck** [myspaghetti/macos-virtualbox#589]
Hi, I am trying to use the script but this step never ends
```
Attempting automated recognition of virtual machine graphical user interface.
``` 

![image](https://user-images.githubusercontent.com/1277920/158065871-943e56b3-00b6-473c-bf72-6637b026c4f2.png)

How long does it take to detect VM's graphical user interface?
The process does not pass through this part for me.
Is this an issue or something that I might be doing wrong?

Also, my machine uses this `i9-11900H` processor, I don't know if a different process regarding the ones being used by the script might be related to this step of the script.

**Comment by myspaghetti** [comment]
Boot failed with `EXITBS`; see [CPU compatibility](https://github.com/myspaghetti/macos-virtualbox#unsupported-features).

**Comment by leoheck** [comment]
There is nothing explaining how to diagnose this. Do you have any tip?

The "documentation" link, points to this (whit is the same text) https://github.com/myspaghetti/macos-virtualbox#documentation

And the  "CPUID Settigns" links this`teleport` thing here: https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport

**Comment by leoheck** [comment]
Does the output of this command help something?

```
➜  ~ VBoxManage list hostcpuids
Host CPUIDs:

Leaf no.  EAX      EBX      ECX      EDX
00000000  0000001b 756e6547 6c65746e 49656e69
00000001  000806d1 0f100800 7ffafbbf bfebfbff
00000002  00feff01 000000f0 00000000 00000000
00000003  00000000 00000000 00000000 00000000
00000004  1c004121 02c0003f 0000003f 00000000
00000005  00000040 00000040 00000003 11121020
00000006  0017eff7 00000002 00000009 00000000
00000007  00000002 f3bfa7eb 18c05fde fc100510
00000008  00000000 00000000 00000000 00000000
00000009  00000000 00000000 00000000 00000000
0000000a  08300805 00000000 0000000f 00008604
0000000b  00000001 00000002 00000100 0000000f
0000000c  00000000 00000000 00000000 00000000
0000000d  000002e7 00000a88 00000a88 00000000
0000000e  00000000 00000000 00000000 00000000
0000000f  00000000 00000000 00000000 00000000
00000010  00000000 00000004 00000000 00000000
00000011  00000000 00000000 00000000 00000000
00000012  00000000 00000000 00000000 00000000
00000013  00000000 00000000 00000000 00000000
00000014  00000001 0000004f 00000007 00000000
00000015  00000002 00000082 0249f000 00000000
00000016  000009c4 00001324 00000064 00000000
00000017  00000000 00000000 00000000 00000000
00000018  00000008 00000000 00000000 00000000
00000019  00000007 00000014 00000003 00000000
0000001a  00000000 00000000 00000000 00000000
0000001b  00000000 00000000 00000000 00000000
0000001c  00000000 00000000 00000000 00000000
80000000  80000008 00000000 00000000 00000000
80000001  00000000 00000000 00000121 2c100800
80000002  68743131 6e654720 746e4920 52286c65
80000003  6f432029 54286572 6920294d 31312d39
80000004  48303039 32204020 4730352e 00007a48
80000005  00000000 00000000 00000000 00000000
80000006  00000000 00000000 01007040 00000000
80000007  00000000 00000000 00000000 00000100
80000008  00003027 00000000 00000000 00000000
80000009  00000000 00000000 00000000 00000000
```

**Comment by leoheck** [comment]
There is no other place where this `cpu_profile` variable is being used on this script
![image](https://user-images.githubusercontent.com/1277920/158622174-6b6c3b1f-e69c-4041-816c-eba8730df3e7.png)

**Comment by myspaghetti** [comment]
No support is offered for configuring the CPUID settings. VirtualBox uses [hex CPUID leaves](https://en.wikipedia.org/wiki/CPUID) which are a pain to configure.

**Comment by leoheck** [comment]
Ok, I could understand what I should have done.

I've never seen this part here when the issue happens
```
![image](https://user-images.githubusercontent.com/1277920/158627738-c8bb67ea-598d-44a1-b87b-2610e4ff0041.png)
```
Well, now I could force this profile, here
![image](https://user-images.githubusercontent.com/1277920/158627181-903795df-e759-44ca-9245-e474a5f8ee09.png)

An environment variable to do this without having to change the script would be good like:
```bash
export OVERRIDE_CPU_PROFILE="Intel Core i7-6700K"
./macos-guest-virtualbox.sh
```

Then, I am here now. It does not have a hard drive, should I do something manually?

![image](https://user-images.githubusercontent.com/1277920/158627105-887846d0-7d95-419b-8710-eb63783447d5.png)

**Comment by leoheck** [comment]
Oh, I see, maybe the process was running and I interrupted it.

**Comment by cederom** [comment]
I had the same problem, but I am working on AMD FX CPU so  for me Xeon worked out :-)

It would be really nice to have this CPUID variable as part of the basic configuration next to RAM amount and CPU Cores settings! :-)
