### ISSUE TITLE
Lion

### ISSUE THREAD

**Issue by enigma0456** [myspaghetti/macos-virtualbox#593]
Using the script I have created several macos vms, upgraded them, cloned them, etc. Works great - even resolved the kernel panic with the Monterey updates. I was gifted an old 2007 MBpro running Tiger. I upgraded the ram, gave it an ssd and managed to upgrade it to Lion which is as far as it can go. I have no installation dvd. I have been attempting to make a virtualbox Lion. It doesn't seem possible to get into recovery with the script generated machines. I had thought to make a time machine backup of the physical machine and then restore it to a virtual one. I added a second blank vdi to the Monterey machine thinking I would restore to that and then remove the Monterey disk and boot from the restored Lion. Nope. Apple thinks the Time Machine backup is from too old a machine and won't restore it. Since then I have tried numerous other machinations. It is fairly simple (if time consuming) to make a copy of the pohysical disk onto a usb backup disk. It is also easy enough to make a usb installer with the Lion dmg. Can't get Virtualbox to boot from the usb so no go there. Studying the script, I see in the beginning that it is specifically keyed to go out and retrieve High Sierra, Mojave or Catalina. Is there a way to plug in the install dmg for Lion by editing the script or is that just not feasible. I know this isn't practical really but it is a challenging puzzle (at least for me). So - is it conceivable or is this totally not possible? Thanks for any thoughts on this.

**Comment by myspaghetti** [comment]
There's a [similar question about older versions of macOS.](https://github.com/myspaghetti/macos-virtualbox/issues/206#issuecomment-627302651)

>When you have a working installation of macOS, it's very easy to create installation media for any available version of macOS as early as Tiger. Versions up to 10.12 use `asr restore`

Download the Lion disk image, restore it onto a USB storage device with `asr restore`, plug the USB device into the faulty Mac, and boot from the USB device.

Incidentally this is the reason I wrote the script in the first place. I had a faulty MacBook Pro but no other Macs handy to create a bootable install media, so I created one manually and thought "this should be automated."

**Comment by Ketchup901** [comment]
> Download the Lion disk image, restore it onto a USB storage device with `asr restore`, plug the USB device into the faulty Mac, and boot from the USB device.

How does one download the disk image? Specifically for Snow Leopard.

**Comment by myspaghetti** [comment]
I believe Snow Leopard [10A432](https://www.google.com/search?hl=en&q=10a432) is available through an Apple Developer account
