### ISSUE TITLE
macOS doesn't run for me

### ISSUE THREAD

**Issue by YeiserDeveloper** [myspaghetti/macos-virtualbox#599]
***I need help on this error***
 
> VBoxManage: error: Machine settings file '/home/****/VirtualBox VMs/macOS/macOS.vbox' already exists
>   VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
>   VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 274 of file VBoxManageMisc.cpp

***It also does not run when starting in virtualbox***

**Comment by myspaghetti** [comment]
When running the script, there is a prompt to delete an existing virtual machine if it has the name specified in the script. You can delete it or choose a different name for the virtual machine.
