### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Hello202I** [myspaghetti/macos-virtualbox#601]
I know this is dumb, but how do i install the macOS on the virtual machine? Thank you.

**Comment by myspaghetti** [comment]
If you're using Windows without [software and features that block VirtualBox VT-x/AMD-V access](https://github.com/myspaghetti/macos-virtualbox#virtualbox-native-execution-manager-nem):

* Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) (with or without Extension Pack)
* Install [Cygwin](https://cygwin.com/install.html) with `coreutils`  `bash` `gzip`  `unzip`  `wget` and `xxd` selected from the full package list (and optionally `tesseract-ocr` and `tesseract-ocr-eng`)
* Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
* Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash -i macos-guest-virtualbox.sh`)

If VT-x-/AMD-V is not accessible, or if the CPU is incompatible, you'll have a bit of unsupported manual configuration to do.
