### ISSUE TITLE
CYGWIN req's

### ISSUE THREAD

**Issue by Agilurso** [myspaghetti/macos-virtualbox#602]
Worked like a champ on CYGWIN.  Please add to the README:

For CYGWIN install, make sure the latest of the following are installed.:
coreutils
gzip
unzip
wget
xxd

**Comment by myspaghetti** [comment]
Cygwin has always been mentioned on the readme in every version since the very first version of the script.

**Comment by Agilurso** [comment]
yep.  Thought it might be helpful to list the dependencies that are necessary from a default CYGWIN install.  Your script lists gzip/unzip/wget/coreutils.  Doesn't list xxd.

**Comment by myspaghetti** [comment]
`xxd` is mentioned twice in the depenencies section in the readme, twice in the script's top comment block, and has its own runtime dependency check:

```
# check that xxd supports endianness -e flag
if [[ -z "$(xxd -e -p -l 16 /dev/urandom 2>/dev/null)" ]]; then
    echo "Please make sure a version of xxd which supports the -e option is installed."
    echo -e "The -e option should be listed when executing   ${low_contrast_color}xxd --help${default_color}"
    echo "The package vim-common-8 provides a compatible version on most modern distros."
    exit
fi
```
