### ISSUE TITLE
EXITBS:START Error on AMD Zen 2 CPU

### ISSUE THREAD

**Issue by Guy-Incognito** [myspaghetti/macos-virtualbox#603]
Hi!

On AMD Zen 2 CPUs, the installer gets stuck with  "EXITBS:START".
One needs to set a cpu-profile in order for the installation to work.
E.g. `VBoxManage modifyvm "VM name" --cpu-profile "Intel Xeon X5482 3.20GHz"`

Could you include a check in your script for future users?
Thanks

**Comment by myspaghetti** [comment]
Sorry, CPU checks are not planned to be implemented due to the vast number of CPUs out there.

**Comment by Danik1601** [comment]
Changing CPU profile did not help me at all on my AMD Ryzen 3600 (Zen 2). I only managed to solve this problem using a bunch of commands from [this article](https://www.geekrar.com/how-to-install-macos-catalina-on-virtualbox-on-amd-systems/)

**Comment by Masamune3210** [comment]
Changing the CPU profile being emulated definitely works, installed just fine on my 3700X a couple months ago
