### ISSUE TITLE
"This mac is no longer eligible to create Apple ID accounts" after Catalina install

### ISSUE THREAD

**Issue by benwiley4000** [myspaghetti/macos-virtualbox#610]
I'm on a macOS 10.14 Mojave host, ran this script (with the option to gather info from my system set to yes) and got a Catalina VM set up. When I got to the step for logging in to Apple services it said "this mac is no longer eligible to create Apple ID accounts. Create an account on a different device." Note that I had previously tried to install a Monterey VM without this script (which worked also), but I couldn't log in with my apple ID there either, however the error message was different, about an UNSUPPORTED_APPLE_ID.

Is there something I forgot to do that is important to make this work?

And yes I am also logged into my Apple ID from the host.

**Comment by myspaghetti** [comment]
When registering an Apple ID, there are checks for some parameters that are not configured by the script. The registration process can tell that it's not a genuine Apple device and fails.

If you wish to create a VM that's indistinguishable from a genuine Apple device (for the purpose of registering an Apple ID) you're going to have to figure out which parameters the registration process checks.

You can start by applying all the hundreds of EFI and NVRAM parameters from a genuine Mac...

**Comment by benwiley4000** [comment]
Thanks so much for the info! I think I will probably just dual boot to
avoid this issue. A shame they don't make it simpler.

Le mer. 6 juill. 2022, 3 h 06 p.m., Jack ***@***.***> a
écrit :

**Comment by Masamune3210** [comment]
To be fair, they don't want it to be simple. It's very much intentional
