### ISSUE TITLE
VM is missing after first shutdown

### ISSUE THREAD

**Issue by ravenala** [myspaghetti/macos-virtualbox#617]
Hello there,

I just used the script to install Catalina on Vbox (Ubuntu 20.04 with Virtualbox 6.1). It all went fine and I had MacOS running but then I shut it down and closed Vbox without paying too much attention and now when I launch virtualbox the new VM does not appear and I can't figure out where it is gone.

Did I do something wrong or is there a glitch here ?

I had Virtualbox already installed on the system and some other VMs in it that are still fine.

Many thanks,

R.

**Comment by myspaghetti** [comment]
This is usually caused when the script runs with elevated privileges. When VirtualBox is subsequently launched with other (user) privileges, it can't find or access the admin/root/superuser VMs. The files need to be moved and their filesystem security preferences (permissions) need to allow the logged-in user to access them.

**Comment by ravenala** [comment]
> This is usually caused when the script runs with elevated privileges. When VirtualBox is subsequently launched with other (user) privileges, it can't find or access the admin/root/superuser VMs. The files need to be moved and their filesystem security preferences (permissions) need to allow the logged-in user to access them.

You are right. I did run the script with superuser privileges (for no reason). I find my VM again if I run virtualbox as root. Cheers.
