### ISSUE TITLE
Virtualbox is not using hardware-supported virtualization features.

### ISSUE THREAD

**Issue by KDJDEV** [myspaghetti/macos-virtualbox#629]
"Virtualbox is not using hardware-supported virtualization features.
Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity
protection, and other Windows features that lock virtualization are turned off.
Exiting."

I am aware that this is an issue that you receive quite frequently. However, I've already gone through every issue thread and tried all of the troubleshooting steps suggested(disabling Hyper-V, Windows Sandbox, WSL2, memory integrity
protection etc.) I understand if you cannot help, as it may just be a quirk of my computer or some software I have installed. However, I can run VirtualBox perfectly fine normally, and I don't see why it shouldn't work when invoked from bash script.

Here is my macOS_troubleshoot.txt:
[macOS_troubleshoot.txt](https://github.com/myspaghetti/macos-virtualbox/files/9847950/macOS_troubleshoot.txt)

Additionally, I'll mention that I'm using Cygwin, as I don't know if that can be inferred from the troubleshooting file.
Thanks for your time!

**Comment by Masamune3210** [comment]
use the bcdboot command to completely disable the hypervisor before it even gets a chance to load. If that doesn't fix it, something else installed on your computer is using a hypervisor and you will have to figure that out for yourself

**Comment by HuettmannH** [comment]
have this message also under macOS Monterey with Monterey

**Comment by KDJDEV** [comment]
> use the bcdboot command to completely disable the hypervisor before it even gets a chance to load. If that doesn't fix it, something else installed on your computer is using a hypervisor and you will have to figure that out for yourself
