### ISSUE TITLE
Unable to boot after updating to macOS Ventura

### ISSUE THREAD

**Issue by manfromarce** [myspaghetti/macos-virtualbox#630]
Everything worked fine with Monterey after adding:
```
<ExtraDataItem name="VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" value="1"/>
<ExtraDataItem name="VBoxInternal/TM/TSCMode" value="RealTSCOffset"/>
```
to the virtual machine.
But after updating to macOS Ventura the system experienced panic in the last reboot after having finished installing, and now it boot loops.

**Comment by anprdev** [comment]
Same issue here so I have to reinstall all.
But very good Job myspaghett.
Thanks for this

**Comment by KingsMMA** [comment]
Was there a fix for this?
It required me to update in order to install XCode but updating bootloops.

**Comment by myspaghetti** [comment]
macOS Ventura is not currently supported, there's no officially supported fix.

**Comment by ZenulAbidin** [comment]
Ventura dropped support for a lot of CPUs and iGPUs older than Kaby Lake so if you get a boot loop, that is probably way.
