### ISSUE TITLE
KVM support

### ISSUE THREAD

**Issue by cserby** [myspaghetti/macos-virtualbox#632]
We're looking into using KVM as a hypervisor. Roughly how much effort would it take to port the script to use libvirt / virsh instead of VBoxManage? Are there any parts of the script that heavily rely on VirtualBox functionalities?

**Comment by myspaghetti** [comment]
The main reason the script relies on VirtualBox is for multiplatform support. QEMU/KVM is definitely the superior virtualization solution for macOS on x86 processors.

Other than multiplatform support, the script relies on VirtualBox keyboard input and (optionally) taking guest screenshots, both of which are available on KVM through [virsh](https://www.libvirt.org/manpages/virsh.html#screenshot).

While I'm not sure about macOS support, KVM definitely works on Windows 11 through WSL2 and runs better than VirtualBox in my opinion.

**Comment by myspaghetti** [comment]
The main reason the script relies on VirtualBox is for multiplatform support. QEMU/KVM is definitely the superior virtualization solution for macOS on x86 processors.

Other than multiplatform support, the script relies on VirtualBox keyboard input and (optionally) taking guest screenshots, both of which are available on KVM through [virsh](https://www.libvirt.org/manpages/virsh.html#screenshot).

While I'm not sure about macOS host support, KVM definitely works on Windows 11 hosts through WSL2 and runs macOS guests better than VirtualBox in my opinion.

**Comment by myspaghetti** [comment]
Another difference is [the use of `-drive /shared_folder` in QEMU/KVM](https://qemu-project.gitlab.io/qemu/system/images.html#virtual-fat-disk-images) in place of the convoluted VISO system in VirtualBox. And of course, all the `VBoxManage` commands have to be rewritten as `qemu` commands.

Switching to KVM can actually streamline the script considerably.

**Comment by myspaghetti** [comment]
Closing issue, unlikely to happen unless a new maintainer picks it up.
