### ISSUE TITLE
cpu-profile in basic vm configuration setting 

### ISSUE THREAD

**Issue by cederom** [myspaghetti/macos-virtualbox#633]
Hello world :-)

Because OS under VM is picky about CPU it would be really nice to have `--cpu-profile` setting explicitly set as part of basic VM configuration, right next to CPU Cores, RAM amount, etc. This is a quite trivial change.

How to make this work is described in https://github.com/myspaghetti/macos-virtualbox/issues/589 but this does not quite obviously come from a current documentation that states changes should be performed on a powered off VM and that breaks whole process.

Thanks for considering and Big THANK YOU for this Marvelous Tool! :-)

**Comment by myspaghetti** [comment]
Glad to hear you found the script useful!

I suppose the documentation could point out that these settings can be modified by modifying the script, too.

**Comment by myspaghetti** [comment]
Implemented by merging [pull request 656](https://github.com/myspaghetti/macos-virtualbox/commit/963da33b87facfccb51e6a2a000dc588d273a45f)

**Comment by cederom** [comment]
TANK U SIR! :-)
