### ISSUE TITLE
please add support for Apple Silicon

### ISSUE THREAD

**Issue by efa** [myspaghetti/macos-virtualbox#634]
hi, I read someone asked support for Big Sur and Monterey in https://github.com/myspaghetti/macos-virtualbox/issues/547
but this only a part of my request.
I need to test some Apple silicon binaries, so I'm requesting to support arm64 architecture

**Comment by myspaghetti** [comment]
VirtualBox is a virtualization hypervisor for x86 hardware. Adding support for other processors is beyond the scope of the script.
