### ISSUE TITLE
VDI in /tmp by default

### ISSUE THREAD

**Issue by blabno** [myspaghetti/macos-virtualbox#636]
The disk image is stored by default in /tmp folder (on linux) which causes problems after reboot.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. The script stores all of its files (except for the VirtualBox VM configuration, which is created by VirtualBox and stored according to its configuration) in the working directory where it is executed. If it's executed on `/tmp` its files are created there, if it's executed on `~/Downloads` its files are created there, and so on. You can choose where to store the files according to the working directory of the script.
