### ISSUE TITLE
Alias `rm=rm -i` causes minor issue

### ISSUE THREAD

**Issue by golimarrrr** [myspaghetti/macos-virtualbox#638]
I have that alias in my shell and it seems to propagate to the shell that runs the scripts, so at some stages the process seem to stall.
Then I press Enter (or 'y' so as to confirm the `rm -i` command) and it continues.
Could this alias be ignored while the script is running?

**Comment by myspaghetti** [comment]
Thanks for the bug report! Fixed in [version 0.99.2.1](https://github.com/myspaghetti/macos-virtualbox/commit/eceafbe5b360e329ee716791ba4a9e301d2e748c)
