### ISSUE TITLE
Error While Starting VM?

### ISSUE THREAD

**Issue by Redneckatvs** [myspaghetti/macos-virtualbox#648]
Not sure why trying to use this script, it doesn't work for whatever reason? 
Here's what I'm getting, anyone have any ideas?

root@XXXX:/mnt/c/Users/XXXXXX/downloads#  zsh -i macos-guest-virtualbox.sh

Push-button installer of macOS on VirtualBox

This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.

The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.

Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:

  macos-guest-virtualbox.sh documentation | less -R

Press enter to review the script configuration

vm_name="macOS"
macOS_release_name="Catalina"    # install "HighSierra" "Mojave" "Catalina"
storage_size=80000               # VM disk image size in MB, minimum 22000
storage_format="vdi"             # VM disk image file format, "vdi" or "vmdk"
cpu_count=2                      # VM CPU cores, minimum 2
memory_size=4096                 # VM RAM in MB, minimum 2048
gpu_vram=128                     # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution

These values may be customized as described in the documentation.

Press enter to continue, CTRL-C to exit
Can't find VBoxManage in PATH variable,
checking /mnt/c/Program Files/Oracle/VirtualBox/VBoxManage.exe
Found VBoxManage

The command "VBoxManage list extpacks" either does not list the Oracle VM
VirtualBox Extension Pack, or lists one or more extensions as unusable.
The virtual machine will be configured without USB xHCI controllers.

Catalina selected to be downloaded and installed

stage: prompt_delete_existing_vm

stage: create_vm

stage: check_default_virtual_machine

Checking that VirtualBox starts the virtual machine without errors.
Error while starting the virtual machine.
Exiting.

**Comment by myspaghetti** [comment]
Hi, thanks for the bug report. Please attach the VirtualBox VM log here, or run `macos-guest-virtualbox.sh troubleshoot` and attach the resulting `macOS__troubleshoot.txt` file here. The log says why the VM fails to start. You can remove any personal information if you like (generally, your username or home directory name).

**Comment by Redneckatvs** [comment]
Hey, thanks for the reply, I have experience with windows/linux virtual machines, but for whatever reason, I was enough of an idiot to not enable virtualization in the bios. after a lot of messing around with things (just note I was running this script on a windows machine) I got it working, and I have to say I am impressed, once you get the required packages installed it works  good, you did a really good job on this one.
