### ISSUE TITLE
complaint about WSL2 or WSLg

### ISSUE THREAD

**Issue by kklmn** [myspaghetti/macos-virtualbox#650]
Hello,

In trying to install in Cygwin in W11 I get a complaint about WSL. I run it in cmd, not in WSL, tried as admin as well.
Tried it in WSL as well, with the same output.

```
These values may be customized as described in the documentation.

Press enter to continue, CTRL-C to exit
The script appears to be executed on WSL2 or WSLg.
Mind that WSL2 and WSLg require kernel module compilation and
custom configuration that is not supported by the script.
If the script does not detect the vboxdrv kernel module, it exits.

c:\Users\konkle\Downloads\Mac\macos-virtualbox-master>
```

Please guide me. Thanks!

**Comment by myspaghetti** [comment]
The prompt `c:\Users\konkle\Downloads\Mac\macos-virtualbox-master>` implies the script is running on `cmd.exe`, and `cmd.exe` is likely calling `wsl.exe` when the bash script is loaded. If you want to use Cygwin you should to run the script from the Cygwin terminal explicitly. That said, if you have WSL2 installed, VirtualBox won't have access to hardware acceleration and the script will exit.

**Comment by kklmn** [comment]
thank you!
