### ISSUE TITLE
Ventura after Installation first startup Problem

### ISSUE THREAD

**Issue by Dravion** [myspaghetti/macos-virtualbox#652]
Hi,
In the last years i have managed to run any MacOS version from MacOS 10.0 (with QEMU PPC) up to 
any Intel version since Leopard (10.5.x) on Virtualbox 6.x and now 7.x version. My last VM i could install was Monterey including
all updates. If a Monterey update is available, i just can install it without any Problems.

But for some strange reason, Ventura is very different. I was not able to do a Virtualbox 7.1.x InPlace upgrade via Softwareupdate or
a Upgrade by ISO image or ripping the BaseSystem.dmg from the ISO and installing it. It also doesn't work with a Clean install from a
fresh or inherited (cloned) (from a  working Monterey VM).

What's happed:
After i prepared my VM with all params necessary so it runs for Monterey (like 
VBoxManage setextradata "MacOS-Ventura" "VBoxInternal/Devices/efi/0/Config/DmiSystemFamily" "MacBook Pro" etc).
MacOS Ventura 13.2 boots up just fine from ISO. I can reach the Disk partitioning program, close the Diskutility and click
the Ventura Install button. It takes upto 40 Mins til it finishes. Then comes the first startup after a successfull installation and it gets stuck in Boot loop with a Kernel Panic.

I researched anywhere and on the Virtualbox Forum and Hackintosh Reddit or TonyMac. I checked out somev ersions of Clover Bootloader to overcome the problems, but no luck so far. I even tried to Install Monterey and used the OpenCore Legacy patcher
(which installed fine) but after a upgrade to Monterey it's the same shit as always. Monterey is the last version which worked for me.

**Comment by myspaghetti** [comment]
I haven't done a feature update to the script for quite a while. With WSL2 being able to run QEMU/KVM, this script is no longer required on Windows, and it was never really required on Linux or macOS (though it works). 

While I feel it's certainly possible to get newer versions of macOS to work on VirtualBox, it's now obsolete on all platforms. If someone wishes to [maintain this script](https://github.com/myspaghetti/macos-virtualbox/issues/645), pull requests are welcome.

[In-place upgrades work for Big Sur but no later. Monterey upgrades work but not in-place,](https://github.com/myspaghetti/macos-virtualbox#upgrading-to-big-sur-and-monterey) the installation target has to be an unused (virtual) storage drive.

Please use [issue 619 for Ventura](https://github.com/myspaghetti/macos-virtualbox/issues/618) and [issue 547 for Big Sur and Monterey.](https://github.com/myspaghetti/macos-virtualbox/issues/547)
