### ISSUE TITLE
Anyone got this to work with Intel i7 12700K?

### ISSUE THREAD

**Issue by matale** [myspaghetti/macos-virtualbox#655]
Hello,
The VM didn't boot and told me to try the different cpu profile settings but none of them seem to work for me.

**Comment by CalculonPrime** [comment]
Not sure if this will help you:
Monterey 12.6.5
VirtualBox 7.0.6
CPU 13900K

Hardware declaration in vbox file:
```
    <Hardware>
      <CPU count="4" CpuProfile="Intel Core i7-6700K">
        <PAE enabled="true"/>
        <NestedHWVirt enabled="true"/>
        <LongMode enabled="true"/>
        <HardwareVirtExLargePages enabled="true"/>
      </CPU>
      <Memory RAMSize="6144"/>
      <Firmware type="EFI"/>
      <HID Pointing="USBMultiTouch" Keyboard="USBKeyboard"/>
      <HPET enabled="true"/>
      <Chipset type="ICH9"/>
         :
```
Without the right CpuProfile, it wouldn't even boot with the 13900K.  

As I recall, Monterey itself requires the following in your \<ExtraData\> or it's unstable, on any CPU (this is discussed in another thread here):

`<ExtraDataItem name="VBoxInternal/TM/TSCMode" value="RealTSCOffset"/>`

**Comment by matale** [comment]
Thanks, the config worked, only tried with Catalina though so didn't do the last bit yet.
