### ISSUE TITLE
How to solve harware-supported virtualization when I need Hyper-V for Docker?

### ISSUE THREAD

**Issue by ProgrammerPeter2** [myspaghetti/macos-virtualbox#657]
I'm using Docker for running some CI/CD agents on my PC, so I need Hypver-V. My question is: how can I use the srcipt without turning of hardware-supported virtualization on my windows?

**Comment by myspaghetti** [comment]
You can use the script on WSL2 by compiling the VirtualBox kernel module. But at that point, you're better off using QEMU/KVM on WSL2. If whatever you're running Docker on supports nested virtualization, you might want to run QEMU/KVM on that.
