### ISSUE TITLE
Please make sure the following packages are installed and that they are of the version specified or newer:

### ISSUE THREAD

**Issue by Pengupine** [myspaghetti/macos-virtualbox#661]
The output on my Terminal app (i'm on Mac M1 Monterey, not Ventura cuz i hate it.) is the following:

`The shell appears to be executed non-interactively. If this is not the case,
please press CTRL-C and run the script under an interactive shell, for example
bash -i macos-guest-virtualbox.sh    or    zsh -i macos-guest-virtualbox.sh

Otherwise, the script will continue running non-interactively.
Please wait      

Push-button installer of macOS on VirtualBox

This script installs only open-source software and unmodified Apple binaries,
and requires about 50GB of available storage, of which 25GB are for temporary
installation files that may be deleted when the script is finished.

The script interacts with the virtual machine twice, please do not interact
with the virtual machine manually before the script is finished.

Documentation about optional configuration, iCloud and iMessage connectivity,
resuming the script by stages, and other topics can be viewed with the
following command:

  macos-guest-virtualbox.sh documentation | less -R

Press enter to review the script configuration

vm_name="macOS"
macOS_release_name="Catalina"    # install "HighSierra" "Mojave" "Catalina"
storage_size=80000               # VM disk image size in MB, minimum 22000
storage_format="vdi"             # VM disk image file format, "vdi" or "vmdk"
cpu_profile="host"               # VM CPU profile, see "CPU profiles" in docs
cpu_count=2                      # VM CPU cores, minimum 2
memory_size=4096                 # VM RAM in MB, minimum 2048
gpu_vram=128                     # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution

These values may be customized as described in the documentation.

Press enter to continue, CTRL-C to exit
Please make sure the following packages are installed
and that they are of the version specified or newer:

    coreutils 8.22   wget 1.14   gzip 1.5   unzip 6.0

Please make sure the coreutils and gzip packages are the GNU variant.`

I am slightly troubled because my brew doesn't have any gcoreutils though, i have macports but i'm not sure if i can install them.....

**Comment by Pengupine** [comment]
Could i fork it to M1? Or help to add support to M1?

**Comment by myspaghetti** [comment]
I believe VirtualBox x86 emulation is very slow on M1/M2/Apple Silicon processors. The process of creating a bootable install image should be tolerable enough (an overnight run) but I would not recommend trying to run the OS as a daily driver or even as a development environment.

At any rate [the project is looking for maintainers](https://github.com/myspaghetti/macos-virtualbox/issues/645) so if you wish to maintain it you have to demonstrate a bit of proficiency and it's yours.
